module.exports = {
    'Maelisa': 'Maoilíosa',
    'Mahon': 'Mathúin',
    'Malachy': 'Maoileachlainn',
    'Malcolm': 'Maolcholaim',
    'Manasses': 'Mánas',
    'Mannix': 'Mainchín',
    'Mantan': 'Mantán',
    'Manus': 'Mánas',
    'Naoise': 'Naoise',
    'Marcas': 'Marcas',
    'Mark': 'Marcas',
    'Martin': 'Máirtín',
    'Mat': 'Mait',
    'Matthew': 'Maitiú',
    'Matthais': 'Maitias g. Maitiais',
    'Maurice': 'Muiris',
    'Melaghlin': 'Maoileachlainn',
    'Melchor': 'Meilseoir',
    'Meldan (Mellan)': 'Meallán',
    'Melrone': 'Maolruáin',
    'Myler': 'Maoilir',
    'Michael': 'Mícheál g. Míchíl',
    'Myles': 'Maolmhuire',
    'Morgue': 'Maodhóg',
    'Morgan': 'Murcha',
    'Mortimer': 'Muireartach',
    'Moses': 'Maodhóg',
    'Muirdeach': 'Muireách',
    'Munchin': 'Mainchín',
    'Mundy': 'Réamann',
    'Murrough': 'Murcha',
    'Murry': 'Muirí',
    'Murtough': 'Muirteortach',
    'Myles': 'Maolmhuire'
}