module.exports = {
    'Ralph': 'Ráulbh',
    'Raphael': 'Raphael',
    'Randal': 'Ránall',
    'Randolph': 'Rannulbh',
    'Raymond': 'Réamann',
    'Redmond': 'Réamann',
    'Reginald': 'Ránall',
    'Revelin': 'Raibhilín',
    'Richard': ['Risteard', 'Risteaird'],
    'Rickard': 'Riocard',
    'Robert': ['Riobeard', 'Roibeaird'],
    'Robin': 'Roibín',
    'Roddy': 'Ruairí',
    'Roderick': 'Ruairí',
    'Roland': 'Rólann',
    'Ronald': 'Ránall',
    'Ronan': 'Rónán',
    'Rory': 'Ruairí',
    'Ros': ['Ros', 'Rosa'],
    'Rowan': 'Ruán',
    'Rowland': 'Rólann'
}