module.exports = {
    'Mabbina': 'Méabh',
    'Mabel': 'Máible',
    'Madeline': 'Madailín',
    'Madge': ['Muireann', 'Muirinne'],
    'Maeve': ['Méabh', 'Méibhe'],
    'Marcella': 'Mairsile',
    'Margaret': 'Maighréad',
    'Margery': 'Máille',
    'Maria': 'Máire',
    'Marjory': 'Máille',
    'Marion': ['Muireann', 'Muirinne'],
    'Martha': 'Marta',
    'Mary': 'Máire',
    'Matilda': 'Maitilde',
    'Matty': 'Maití',
    'Mawd': 'Máda',
    'May': 'Máirín',
    'Maureen': 'Máirín',
    'Meeda': 'Míde',
    'Mella': 'Mealla',
    'Miriam': 'Miriam',
    'Moira': 'Máire',
    'Molly': 'Máirín',
    'Mona': 'Muanait',
    'Monica': 'Moncha',
    'More': ['Mór', 'Móire'],
    'Moreen': 'Móirín',
    'Morrin': ['Muireann', 'Muirinne'],
    'Muriel': ['Muireal', 'Muirile']
    'Muriel': ['Muireal', 'Muirile']
}