module.exports = {
    'Gaan': 'Ó Gacháin',
    'Gabbett': 'Gabóid',
    'Gaff': 'Mag Eathach',
    'MacGagh': 'Mag Eathach',
    'Gaillimh': 'Mag Eathach',
    'Mac Gaffey': 'Mac Gaibhidh',
    'Mac Gaffigan': 'Mag Eachagáin',
    'Gaffigan': 'Ó Gáifeacháin',
    'Gavigan': 'Ó Gáifeacháin',
    'O Gaffigan': 'Ó Gáifeacháin',
    'O Gavigan': 'Ó Gáifeacháin',
    'Mac Gaffin': 'Mac Dhuifinn',
    'Gaffney': 'Ó Gamhna',
    'Mac Gaffrey': 'Mac Gafraidh',
    'Mac Gaggy': 'Mag Eachaidh',
    'Mac Gagh': 'Mac Eathach',
    'Gahagan': 'Mag Eochagáin',
    'O Gahagan': 'Mag Eochagáin',
    'Mac Gahan': 'Mag Eacháin',
    'Gahan': 'Ó Gacháin',
    'O Gahan': 'Ó Gacháin',
    'Mac Gaheran': 'Mag Eachráin',
    'Mac Gahern': 'Mag Eachráin',
    'Gahey': 'Mag Eachaidh',
    'Mac Gahey': 'Mag Eachaidh',
    'Mac Gahran': 'Mag Eachráin',
    'Gaine': 'Ó Géibhinn',
    'Gainer': 'Mag Fhionnbhairr',
    'Gaitens': 'Mag Eiteagáin',
    'Galbally': 'de Gallbhaile',
    'Galbriath': 'Mac an Bhreatnaigh',
    'Mac Gale': 'Mac Cathail',
    'Gale': 'Mac an Ghaill',
    'Galesby': 'Mac Giolla Easpaig',
    'Mac Galey': 'Mac Amhalaí',
    'Mac Gawley': 'Mac Amhalaí',
    'Gall': 'Mac an Ghaill',
    'Gaule': 'Mac an Ghaill',
    'Mac Gall': 'Mac Camhaoil',
    'Gallagher': 'Ó Gallchóir',
    'O Gallagher': 'Ó Gallchóir',
    'Gallahue': 'Ó Gallchú',
    'Gallen': 'Ó Gaillín',
    'O Gallen': 'Ó Gaillín',
    'Gallery': 'Mac Giolla Laoire (An Clár)',
    'Mac Gallery': 'Mac Giolla Laoire (An Clár)',
    'Gallery': 'Mac Giolla Riabhaigh',
    'Mac Gallery': 'Mac Giolla Riabhaigh',
    'Galligan': 'Ó Gealagáin', 
    'O Galligan': 'Ó Gealagáin', 
    'Gallina': 'Ó Gailineach',
    'Gallinagh': 'Ó Gailineach',
    'O Gallina': 'Ó Gailineach',
    'O Gallinagh': 'Ó Gailineach',
    'Gallivan': 'Ó Gealbháin',
    'O Gallivan': 'Ó Gealbháin',
    'Gallogly': 'Mac an Ghallóghlaigh',
    'Mac Gallogly': 'Mac an Ghallóghlaigh',
    'Gallon': 'Ó Galáin',
    'O Gallon': 'Ó Galáin',
    'Gallay': 'Gaillí',
    'Galloway': 'Gaillí',
    'Galt': 'Gallda',
    'Galvin': 'Ó Gealbháin',
    'O Galvin': 'Ó Gealbháin',
    'Galway': 'Gaillí',
    'Galway': 'de Gaillí',
    'Gamble': 'Gamal',
    'Gamlin': 'Gaimlín',
    'Gammel': 'Gamal',
    'Gammon': 'Gambún',
    'Mac Gammon': 'Gambún',
    'Ganagher': 'Mac Dhuineachair',
    'Ganley': 'Mag Sheanlaoich',
    'Mac Ganley': 'Mag Sheanlaoich',
    'Mac Gann': 'Mag Annaidh',
    'Gannissy': 'Mag Aonasa',
    'Gannon': 'Mag Fhionnáin',
    'Mac Gannon': 'Mag Fhionnáin',
    'Gantly': 'Mag Sheanlaoich',
    'Gara': 'Ó Gadhra',
    'O Gara': 'Ó Gadhra',
    'Mac Garahan': 'Mac Garacháin',
    'Mac Garaghan': 'Mac Garacháin',
    'Garahy': 'Mag Fhearaigh',
    'Mac Garahy': 'Mag Fhearaigh',
    'Mac Garaty': 'Mac Aireachtaigh',
    'Garde': 'Geard',
    'Gardiner': 'Gairnéir',
    'Gargan': 'Ó Geargáin',
    'Garity': 'Mag Oireachtaigh',
    'Garlan': 'Gearlann',
    'Garland': 'Gearlann',
    'Mac Garr': 'Mac an Gheairr',
    'Garraghan': 'Mag Aracháin',
    'Garraher': 'Mag Fhearchair',
    'Mac Garraher': 'Mag Fhearchair',
    'Mac Garran': 'Mag Aracháin',
    'Mac Garrell': 'Mag Fhearail',
    'Garrett': 'Mac Gearóid',
    'Mac Garrett': 'Mac Gearóid',
    'O’Garriga': 'Ó Gearaga',
    'Garrigan': 'Mac Geargáin',
    'Mac Garrigan': 'Mac Geargáin',
    'Mac Garrigle': 'Mag Fheargail',
    'Mac Garrity': 'Mag Aireachtaigh',
    'Mac Garroll': 'Mag Fhearail',
    'Garry': 'Mag Fhearaigh',
    'Mac Garry': 'Mag Fhearaigh',
    'Garlan': 'Mac Gearlann',
    'Gartlan': 'Mac Gearlann',
    'Mag Garlan': 'Mac Gearlann',
    'Mag Gartlan': 'Mac Gearlann',
    'Garland': 'Mac Gearlann',
    'Gartland': 'Mac Gearlann',
    'Mag Garland': 'Mac Gearlann',
    'Mag Gartland': 'Mac Gearlann',
    'Garvan': 'Ó Garbháin',
    'O Garvan': 'Ó Garbháin',
    'Mac Garvey': 'Mac Gairbheith',
    'Garvey': 'Ó Gairbhith',
    'O Garvey': 'Ó Gairbhith',
    'Garvin': 'Ó Gairbhín',
    'O Garvin': 'Ó Gairbhín',
    'Gascoigne': 'de Gascún',
    'Mac Gaskell': 'Mag Ascaill',
    'Gaskin': 'de Gascún',
    'Gasson': 'Ó Gusáin',
    'Gaston': 'Gastún',
    'Gatchell': 'Gaisteal',
    'Gately': 'Ó Gatlaoich',
    'Gates': 'de Gheata',
    'Gatlin': 'Mag Eiteagáin',
    'Gattins': 'Mag Eiteagáin',
    'Mac Gaugh': 'Mag Eathach',
    'Gaughan': 'Ó Gacháin',
    'O Gaughan': 'Ó Gacháin',
    'Mac Gaughey': 'Mag Eachaidh',
    'Gaughney': 'Mag Fhachtna',
    'Mac Gauige': 'Mac Eachaidh',
    'Gaughran': 'Mag Eachráin',
    'Gaul': 'Mac an Ghaill',
    'Gaule': 'Mac an Ghaill',
    'Mac Gauley': 'Mag Amhalaí',
    'Gault': 'Gallda',
    'Mac Gauran': 'Mag Shamhráin',
    'Gauslin': 'Góislín',
    'Gaussen': 'Ó Gusáin',
    'O Gaussen': 'Ó Gusáin',
    'Gavaghan': 'Ó Gaibhneacháin',
    'O Gavaghan': 'Ó Gaibhneacháin',
    'Gavan': 'Ó Gábháin',
    'Gavin': 'Ó Gábháin',
    'O Gavin': 'Ó Gábháin',
    'O Gavan': 'Ó Gábháin',
    'Mac Gaver': 'Mac Éimhir',
    'Mac Gavick': 'Mag Dhabhaic',
    'Gavigan': 'Mac Gaibheacháin',
    'Mac Gavigan': 'Mac Gaibheacháin',
    'Gavin': 'Ó Gáibhín',
    'Mac Gavock': 'Mac Dhabhóc',
    'Gaw': 'Mag Adhaimh',
    'Mac Gaw': 'Mag Adhaimh',
    'Mac Gawley': 'Mac Amhalaí',
    'Mac Gawran': 'Mag Shamhráin',
    'Gay': 'Mac Giolla Dé',
    'Gayer': 'Mac an Gheairr',
    'Gaynard': 'Ó Gánaird',
    'Gaynor': 'Mag Fhionnbhairr',
    'Mac Gaynor': 'Mag Fhionnbhairr',
    'Mac Geady': 'Mag Céadaigh',
    'Geagan': 'Mac Eochagáin',
    'Mac Geagh': 'Mag Eathach',
    'Gealon': 'Ó Gialláin',
    'Mac Gean': 'Mac Gaoithín',
    'Geane': 'Ó Géibhinn',
    'O Geane': 'Ó Géibhinn',
    'Geaney': 'Mac Géibheannaigh',
    'Mac Geaney': 'Mac Géibheannaigh',
    'Geaney': 'Ó Géibheannaigh',
    'O Geaney': 'Ó Géibheannaigh',
    'Geanor': 'Mag Fhionnbhairr',
    'Mac Geanor': 'Mag Fhionnbhairr',
    'Mac Geany': 'Mac Éanna',
    'Gearn': 'Ó Géaráin',
    'Gearns': 'Ó Géaráin',
    'Gearty': 'Mag Oireachtaigh',
    'Mac Gearty': 'Mag Oireachtaigh',
    'Mac Geary': 'Mac Gadhra',
    'Geary': 'Ó Gadhra',
    'O Geary': 'Ó Gadhra',
    'Geaveney': 'Ó Géibheannaigh',
    'O Geaveney': 'Ó Géibheannaigh',
    'Mac Geaveny': 'Mac Géibheannaigh',
    'Gee': 'Mag Aoidh',
    'Mac Gee': 'Mag Aoidh',
    'Geehan': 'Mac Gaoithín',
    'Mac Geehan': 'Mac Gaoithín',
    'Geehan': 'Ó Gaoithín',
    'O Geehan': 'Ó Gaoithín',
    'Mac Geehee': 'Mac Gaoithe',
    'Geelan': 'Ó Gialláin',
    'O Geelan': 'Ó Gialláin',
    'Mac Geeney': 'Mac Géibheannaigh',
    'Mac Geer': 'Mac an Gheairr',
    'Mac Geever': 'Mag Íomhair',
    'Gegan': 'Mac Eochagáin',
    'Geogan': 'Mac Eochagáin',
    'Mac Gegan': 'Mac Eochagáin',
    'Mac Geogan': 'Mac Eochagáin',
    'Geharan': 'Mag Eachráin',
    'Mac Geharan': 'Mag Eachráin',
    'Mac Gellan': 'Mac Gealáin',
    'Gellan': 'Ó Gealáin',
    'Gelland': 'Ó Gealáin',
    'Mac Gellick': 'Mag Uilic',
    'Gelvarry': 'Mac Giolla Bhearaigh',
    'Mac Genis': 'Mag Aonasa',
    'Gennagh': 'Mag Gineáith',
    'Gennell': 'Mag Fhionnail',
    'Mac Geoghegan': 'Mac Eochagáin',
    'Geoghery': 'Ó Gothraidh',
    'O Geoghery': 'Ó Gothraidh',
    'Mac Geough': 'Mag Eochaidh',
    'Geown': 'Mag Eoghain',
    'Geon': 'Mag Eoghain',
    'Mac Geown': 'Mag Eoghain',
    'Mac Geon': 'Mag Eoghain',
    'Geraghty': 'Mag Oireachtaigh',
    'Mac Geraghty': 'Mag Oireachtaigh',
    'Geran': 'Ó Géaráin',
    'O Geran': 'Ó Géaráin',
    'Gerard': 'Gearard',
    'German': 'Gearmán',
    'Germon': 'Gearmann',
    'Gernon': 'Gearnún',
    'Mac Gerr': 'Mac an Ghirr',
    'Mac Gerrigan': 'Mac Geargáin',
    'Mac Gerry': 'Mag Fhearaigh',
    'Gerty': 'Mag Oireachtaigh',
    'Mac Gerty': 'Mag Oireachtaigh',
    'Gervase': 'Gearbhás',
    'Gethin': 'Mag Eiteagáin',
    'Mac Getrick': 'Mag Shitric',
    'Mac Gettigan': 'Mag Eiteagáin',
    'Gettins': 'Mag Eiteagáin',
    'Getty': 'Mag Eitigh',
    'Ghagan': 'Mag Eachagáin',
    'Ghee': 'Mag Aoidh',
    'Ghegan': 'Mag Eochagáin',
    'Mac Ghoon': 'Mac Gabhann', 
    'Gibb': 'Gib',
    'Gibben': 'Mag Fhibín',
    'Mac Gibben': 'Mag Fhibín',
    'Gibbing': 'Mac Giobúin',
    'Gibbings': 'Mac Giobúin',
    'Mac Gibbon': 'Mac Giobúin',
    'Giblin': 'Ó Gibealláin',
    'O Giblin': 'Ó Gibealláin',
    'Mac Gibney': 'Mac Gibne',
    'Gibney': 'Ó Gibne',
    'Gibsey': 'Ó Gibealláin',
    'Gibson': 'Mac Gib',
    'Gibulawn': 'Ó Gibealláin',
    'Mac Giff': 'Mac Dhuibh',
    'Griffin': 'Mac Dhuifinn',
    'Gifney': 'Ó Gamhna',
    'Mac Gihan': 'Mac Gaoithín',
    'Gihon': 'Ó Gaoithín',
    'Guihen': 'Ó Gaoithín',
    'Gilbert': 'Gilbeirt',
    'Gilberson': 'Mac Gilbeirt',
    'Gilbertson': 'Mac Gilbeirt',
    'Gilbey ilboy': 'Ó Giolla Bhuí',
    'Gilbey OGilboy': 'Ó Giolla Bhuí',
    'Gilbride': 'Mac Giolla Bhríde',
    'Mac Gilbride': 'Mac Giolla Bhríde',
    'Gilchrist': 'Mac Giolla Chríost',
    'Mac Gilchrist': 'Mac Giolla Chríost',
    'Gildea': 'Mac Giolla Dé',
    'Mac Gildea': 'Mac Giolla Dé',
    'Gildowney': 'Mac Gillla Domhnaigh',
    'Mac Gildowney': 'Mac Gillla Domhnaigh',
    'Gilduff': 'Mac Gilla Dhuibh',
    'Mac Gilduff': 'Mac Gilla Dhuibh',
    'Giles (Gaillimh)': 'Mac Goill',
    'Giles': 'Ó Glaisne',
    'Gilfeather': 'Mac Giolla Pheadair',
    'Gilfillan': 'Mac Giolla Fhaoláin',
    'Mac Gilfillan': 'Mac Giolla Fhaoláin',
    'Gilfoyle': 'Mac Giolla Phóil',
    'Mac Gilfoyle': 'Mac Giolla Phóil',
    'Gilgan': 'Ó Giollagáin',
    'O Gilgan': 'Ó Giollagáin',
    'Gilgar': 'Mac Giolla Ghearr',
    'Mac Gilgar': 'Mac Giolla Ghearr',
    'Gilgrinn': 'Mac Giolla Ghrinn',
    'Mac Gilgrinn': 'Mac Giolla Ghrinn',
    'Gilgunn': 'Mac Gillla Dhoinn',
    'Mac Gilgunn': 'Mac Gillla Dhoinn',
    'Mac Gilgunn': 'Mac Gillla Ghunna',
    'Mac Gilharry': 'Mac Giolla Charraigh',
    'Gilheany': 'Mac Gillla Chainnigh',
    'Mac Gilheany': 'Mac Gillla Chainnigh',
    'Gilhool': 'Mac Giolla Chomhaill',
    'Mac Gilhool': 'Mac Giolla Chomhaill',
    'Gilhooly': 'Mac Giolla Shúiligh',
    'Mac Gilhooly': 'Mac Giolla Shúiligh',
    'Gilhooly': 'Mac Gillla Ghuala',
    'Mac Gilhooly': 'Mac Gillla Ghuala',
    'Gilkelly': 'Mac Giolla Cheallaigh',
    'Gilkeson': 'Mag Uilcín',
    'Mac Gill': 'Mac Giolla',
    'Gill': 'Mac an Ghaill',
    'Gill': 'Mac an Ghoill',
    'Mac Gill': 'Mac an Ghoill',
    'Mac Gillacowan': 'Mac Giolla Chomain',
    'Mac Gillacuddy': 'Mac Giolla Ghuda',
    'Mac Gillan': 'Mac Gileáin',
    'Gillan': 'Ó Giolláin',
    'Gilland': 'Ó Giolláin',
    'O Gillan': 'Ó Giolláin',
    'O Gilland': 'Ó Giolláin',
    'Mac Gillanders': 'Mac Giolla Aindréis',
    'Gillaspy': 'Mac Giolla Easpaig',
    'Mac Gilldowie': 'Mac Giolla Dúthaigh',
    'Gilleece': 'Mac Giolla Íosa',
    'Mac Gilleece': 'Mac Giolla Íosa',
    'Gilleen': 'Ó Gilín',
    'O Gilleen': 'Ó Gilín',
    'Gilleen': 'Ó Gillín',
    'O Gilleen': 'Ó Gillín',
    'Gilleland': 'Mac Giolla Fhaoláin',
    'Gilleran': 'Mac Giollaráin',
    'Gilleraj': 'Mac Giollaráin',
    'Mac Gilleraj': 'Mac Giollaráin',
    'Gillespie': 'Mac Giolla Easpaig',
    'Mac Gillespie': 'Mac Giolla Easpaig',
    'Mac Gillian': 'Mac Gileáin',
    'Gillick': 'Mag Uilic',
    'Mac Gillick': 'Mag Uilic',
    'Gilligan': 'Mac Giollagáin',
    'Mac Gilligan': 'Mac Giollagáin',
    'Gillian': 'Ó Giollagáin',
    'O Gillian': 'Ó Giollagáin',
    '(Gillilan': 'Mac Giolla Fhaoláin',
    '(Gilliland': 'Mac Giolla Fhaoláin',
    'Gillinan': 'Mac Giolla Fhionnáin',
    'Gillinnion': 'Mac Giolla Fhinnéin',
    'Gillis': 'Mac Giolla Íosa',
    'Gillivan': 'Mac Giolla Bháin',
    'Mac Gillivray': 'Mac Giolla Bhrátha',
    'Gillon': 'Ó Giolláin',
    'Gilloon': 'Mac Giolla Eoin',
    'Gilloran': 'Mac Giolla Luaithrinn',
    'Mac Gilloran': 'Mac Giolla Luaithrinn',
    'Gilloway': 'Mac Giolla Bhuí',
    'Gillowly': 'Mac Giolla Ghuala',
    'Mac Gillreavy': 'Mac Giolla Riabhaigh',
    'Mac Gilly': 'Mac an Choiligh',
    'Mac Gillycuddy': 'Mac Giolla Chuda',
    'Mac Gilmartin': 'Mac Giolla Mhártain',
    'Gilmary': 'Mac Giolla Mhuire',
    'Gilmer': 'Mac Ghiolla Mhir',
    'Gilmore': 'Mac Giolla Mhir',
    'Mac Gilmore': 'Mac Giolla Mhir',
    'Gilmore': 'Mac Giolla Mhir (Sligeach)',
    'Gilmer': 'Mac Giolla Mhir (Sligeach)',
    'Mac Gilmore': 'Mac Giolla Mhir (Sligeach)',
    'Mac Gilmer': 'Mac Giolla Mhir (Sligeach)',
    'Gilmore': 'Mac Giolla Mhuir',
    'Mac Gilmore': 'Mac Giolla Mhuir',
    'Mac Gilna': 'Mac Giolla na Naomh',
    'Mac Gilnagh': 'Mac Giolla na Naomh',
    'Gilpatrick': 'Mac Giolla Phádraig',
    'Gilpin': 'Mac Giolla Finn',
    'Gilrain': 'Mac Giollaráin',
    'Mac Gilrea': 'Mac Giolla Rua',
    'Mac Gilreevy': 'Mac Giolla Riabhaigh',
    'Gilroy': 'Mac Giolla Rua',
    'Mac Gilroy': 'Mac Giolla Rua',
    'Gilsenan': 'Mac Giolla Seanáin',
    'Gilson': 'Mac Giolla Seanáin',
    'Gilshenan': 'Mac Giolla Seanáin',
    'Mac Gilsenan': 'Mac Giolla Seanáin',
    'Mac Gilson': 'Mac Giolla Seanáin',
    'Mac Gilshenan': 'Mac Giolla Seanáin',
    'Giltenan': 'Mac Giolla tSeanáin',
    'Mac Giltenan': 'Mac Giolla tSeanáin',
    'Gilton': 'Mac Giolla tSeanáin',
    'Mac Gilvane': 'Mac Giolla Bháin',
    'Gilvany': 'Mac Giolla Mheana',
    'Mac Gilvany': 'Mac Giolla Mheana',
    'Gilvarry': 'Mac Giolla Bhearaigh',
    'Mac Gilvarry': 'Mac Giolla Bhearaigh',
    'Mac Gilvie': 'Mac Giolla Bhuí',
    'Mac Gilwee': 'Mac Giolla Bhuí',
    'O’Gilvie': 'Ó Giolla Bhuí',
    'Gilvoy': 'Mac Giolla Bhuí',
    'Gilvoy': 'Mac Giolla Bhuí',
    'Gilway': 'Mac Giolla Bhuí',
    'Mac Gilvoy': 'Mac Giolla Bhuí',
    'Mac Gilway': 'Mac Giolla Bhuí',
    'Mac Gimpsey': 'Mac Dhíomasaigh',
    'Gina': 'Mac Cionaoith',
    'ginnaw': 'Mac Cionaoith',
    'Ginaty': 'Mac Fhinneachtaigh',
    'Mac Gindle': 'Mag Fhionnail',
    'Ginevan': 'Mac Dhuinneabháin',
    'Ginivan': 'Mac Dhuinneabháin',
    'Mac Ginley': 'Mag Fhionnaile',
    'Ginn': 'Mag Fhinn',
    'Ging': 'Mag Fhinn',
    'Mac Ginn': 'Mag Fhinn',
    'Mac Ging': 'Mag Fhinn',
    'Ginnane': 'Ó Coinneáin',
    'O Ginnane': 'Ó Coinneáin',
    'Ginnell': 'Mag Fhionnail',
    'Mac Ginnell': 'Mag Fhionnail',
    'Ginnelly': 'Mag Fhionnaile',
    'Mac Ginnelly': 'Mag Fhionnaile',
    'Mac Ginness': 'Mag Aonais',
    'Ginty': 'Mag Fhinneachta',
    'Ginity': 'Mag Fhinneachta',
    'Mac Ginty': 'Mag Fhinneachta',
    'Mac Ginity': 'Mag Fhinneachta',
    'Mac Ginyer': 'Mag Fhionnbhairr',
    'Ginnevan': 'Ó Ceannuáin',
    'Girey': 'Ó Gadhra',
    'Mac Girl': 'Mag Fhearail',
    'Mac Girr': 'Mac an Ghirr',
    'Mac Girr': 'Mac an Ghearr',
    'Girvan': 'Ó Gairbhín',
    'O Girvan': 'Ó Gairbhín',
    'Gissane': 'Ó Cíosáin',
    'O Gissane': 'Ó Cíosáin',
    'Given': 'Mac Dhuibhín',
    'Mac Given': 'Mac Dhuibhín',
    'Mac Givena': 'Mac Dhuibhín',
    'Mac Givern': 'Mag Uidhrín',
    'Mac Givney': 'Mac Dhuibhne',
    'Glackan': 'Ó Glacáin',
    'Gladdery': 'Mac Gleadra',
    'Mac Gladdery': 'Mac Gleadra',
    'Mac Glade': 'Mag Léid',
    'Glaffey': 'Mag Laithimh',
    'Mac Glaffey': 'Mag Laithimh',
    'Mac Glan': 'Mag Fhlainn',
    'Mac Glanchy': 'Mac Lannchaidh',
    'Mac Glancy': 'Mag Lannchaidh',
    'Glanders': 'Mag Giolla Aindréis',
    'Glanfield': 'de Glainbhíol',
    'Glanny': 'an Ghleanna',
    'Glanton': 'an Ghleanntáin',
    'Glanville': 'de Glainbhíol',
    'Glanvill': 'de Glainbhíol',
    'Glanville': 'de Glainbhíol',
    'Glanfield': 'de Glainbhíol',
    'Mac Glare': 'Mac Giolla Chathair',
    'Glasby': 'Mac Giolla Easpaig',
    'Glasgow': 'Mac Bhloscaigh',
    'Mac Glasgow': 'Mac Bhloscaigh',
    'Mac Glashan': 'Mac Glaisín',
    'Glasheen': 'Ó Glaisín',
    'O Glasheen': 'Ó Glaisín',
    'Glass': 'Glas',
    'Glassett': 'Glaiséid',
    'Mac Glaughlin': 'Mag Lochlainn',
    'Mac Glave': 'Mac Laithimh',
    'Glavey': 'Mac Laithimh',
    'Glavin': 'Mag Láimhín',
    'Mac Glavin': 'Mag Láimhín',
    'Glavin': 'Ó Gláimhín',
    'O Glavin': 'Ó Gláimhín',
    'Glavy': 'Mag Laithimh',
    'Mac Glavy': 'Mag Laithimh',
    'Gleasure': 'Gléasúr',
    'Mac Gleen': 'Mag Fhloinn',
    'Glennan': 'Mac Giolla Fhinnéin',
    'Mac Glennan': 'Mac Giolla Fhinnéin',
    'leeson': 'Ó Gliasáin',
    'OGleeson': 'Ó Gliasáin',
    'Mac Gleish': 'Mac Giolla Íosa',
    'Glenane': 'Mag Leannáin',
    'Glendon': 'Mac Giolla Fhiondáin',
    'Gleneghan': 'Mag Leannacháin',
    'Glenneghan': 'Mag Leannacháin',
    'Glenn': 'an Ghleanna',
    'Glenny': 'an Ghleanna',
    'Glennon': 'Mag Leannáin',
    'Mac Glennon': 'Mag Leannáin',
    'Mac Glew': 'Mac Dhoinnléibhe',
    'Mac Glew': 'Mac Leoid',
    'Mac Leod': 'Mac Leoid',
    'Gilihool': 'Mac Giolla Chomhaill',
    'Mac Glin': 'Mac Fhloinn',
    'Mac Glynn': 'Mac Fhloinn',
    'Mac Glinchy': 'Mag Loingsigh',
    'Glissane': 'Ó Glasáin',
    'Mac Gloin': 'Mac Giolla Eoin',
    'Glone': 'Mac Giolla Eoin',
    'Gloon': 'Mac Giolla Eoin',
    'Mac Glone': 'Mac Giolla Eoin',
    'Mac Gloon': 'Mac Giolla Eoin',
    'Glorney': 'Ó Glóiairn',
    'Glory': 'Ó Glóiairn',
    'Glory': 'Mag Labhraí',
    'Mac Glory': 'Mag Labhraí',
    'Gloughlin': 'Mag Lochlainn',
    'Mac Gloughlin': 'Mag Lochlainn',
    'Glynn': 'Mag Fhloinn',
    'Mac Glynn': 'Mag Fhloinn',
    'Goaley': 'Ó Gabhla',
    'Goan': 'Ó Gobhann',
    'Gobin': 'Ó Gobáin',
    'Godfrey': 'Mac Gothraidh',
    'Godman': 'Gothmann',
    'Godrick': 'Mag Ualghairg',
    'Godwin': 'Ó Deá',
    'Mac Goey': 'Mag Eochaidh',
    'Mac Goff': 'Mag Eochaidh',
    'Gough': 'Mag Eochaidh',
    'Goff': 'Mag Eochaidh',
    'Mac Gofrey': 'Mac Gafraidh',
    'Gogan': 'Gógan',
    'Goggin': 'Gógan',
    'Gogarty': 'Mag Fhógartaigh',
    'Mac Gogarty': 'Mag Fhógartaigh',
    'Mac Goggy': 'Mag Eochaidh',
    'Gohery': 'Ó Gothraidh',
    'O Gohery': 'Ó Gothraidh',
    'Going': 'Mac Gabhann',
    'Golaghley': 'Mac an Ghallóghlaigh',
    'Golden': 'Ó Góilín',
    'Goldie': 'Gúilí',
    'Goldrick': 'Mac Gualraic',
    'Mac Goldrick': 'Mac Gualraic',
    'Goligher': 'Ó Gallchóir',
    'O Goligher': 'Ó Gallchóir',
    'Golightly': 'Mac an Ghallóglaigh',
    'Gollan': 'Ó Galáin',
    'Gomory': 'Mac Iomaire',
    'Mac Gonigal': 'Mac Congail',
    'Gonn': 'Gunna',
    'Gonne': 'Gunna',
    'Mac Gonnell': 'Mac Dhónaill',
    'Gonoude': 'Mag Nuad',
    'Good': 'Gud',
    'Goodfellow': 'Mag Uiginn (Tír Eoghain)',
    'Goodman': 'Mac Giolla Mhaith',
    'Godson': 'Mac Giolla Mhaith',
    'Goodman': 'Mag Uiginn (Tír Eoghain)',
    'Goodwin': 'Mac Gualraic',
    'Googan': 'Mac Guagáin',
    'Mac Googan': 'Mac Guagáin',
    'Mac Goohan': 'Mag Cuacháin',
    'Mac Gool': 'Mag Fhearghail',
    'Goold': 'Gúl',
    'Goolde': 'Gúl',
    'Gooley': 'Ó Gabhla',
    'Goonan': 'Ó Gamhnáin',
    'Goonane': 'Ó Gamhnáin',
    'O Goonan': 'Ó Gamhnáin',
    'O Goonane': 'Ó Gamhnáin',
    'Goonery': 'Ó Gamhnaire',
    'Gooney': 'Ó Gamhnáin',
    'Mac Goorty': 'Mac Dhorchaidh',
    'Gordon': 'Mac Mhuirneacháin',
    'Gore': 'de Gaor',
    'Gorevan': 'Mag Shamhráin Ó Garbháin (Sligeach)',
    'Gorey': 'Ó Guaire',
    'Gorham': 'Ó Guairim',
    'Gorish': 'Mag Fheorais',
    'Mac Gorl': 'Mag Fhearail',
    'Mac Gorley': 'Mag Thoirealaigh',
    'Mac Gorlick': 'Mac Gualraic',
    'Gormagan': 'Ó Gormagáin',
    'Gormally': 'Garmaile',
    'Gorman': 'Mac Gormáin',
    'Mac Gorman': 'Mac Gormáin',
    'O’Gorman': 'Ó Gormáin',
    'Gormican': 'Ó Gormagáin',
    'O Gormican': 'Ó Gormagáin',
    'Gormley': 'Ó Garmaile',
    'Mac Gorrian': 'Mag Corraín',
    'Mac Gorry': 'Mac Gothraidh',
    'Gorry': 'Ó Guaire',
    'Mac Gorty': 'Mac Dhorchaidh',
    'Goslin': 'Góislín',
    'Gosling': 'Góislín',
    'Gosnell': 'Góiséir',
    'Gossan': 'Ó Gusáin',
    'Gough': 'Mag Eochaidh',
    'Mac Gough': 'Mag Eochaidh',
    'Gould': 'Gúl',
    'Goulding': 'Góilin',
    'Goulding': 'Ó Gabhláin',
    'Mac Gouldrick': 'Mac Gualraic',
    'Gouldy': 'Gúilí',
    'Mac Gourkey': 'Mac Dhorchaidh',
    'Gourley': 'Mag Thoirealaigh',
    'Mac Gourley': 'Mag Thoirealaigh',
    'Mac Gourneson': 'Mag Mhuirneacháin',
    'Goveran': 'Mag Shamhráin',
    'Magauran': 'Mag Shamhráin',
    'Mac Goveran': 'Mag Shamhráin',
    'Mac Magauran': 'Mag Shamhráin',
    'Governey': 'Mac Giobheanaigh',
    'Gow': 'Mac Gabha',
    'Gowan': 'Mac Gabhann',
    'Mac Gowan': 'Mac Gabhann',
    'Gowan': 'Ó Gabhann',
    'O Gowan': 'Ó Gabhann',
    'Going': 'Mac Gobhann',
    'Going': 'Mac Gobhann',
    'Gowran': 'Ó Gabhráin',
    'Mac Gowran': 'Mag Shamhráin',
    'Mac Gra': 'Mag Raith',
    'Grace': 'Grás',
    'Graddy': 'Ó Greada',
    'O Graddy': 'Ó Greada',
    'Mac Gread': 'Mag Raith',
    'Mac Grade': 'Mag Raith',
    'Graden': 'Mag Bhradáin',
    'Mac Grady': 'Mag Bhrádaigh',
    'Grady': 'Ó Gráda',
    'O Grady': 'Ó Gráda',
    'Graham': 'Ó Gréacháin',
    'Graham': 'Ó Gréacháin',
    'Grahan': 'Ó Gréacháin',
    'Grailis': 'Mag Riallais',
    'Grainger': 'Gráinséir',
    'Mac Granahan': 'Mag Reannacháin',
    'Grandon': 'Grandún',
    'Mac Grane': 'Mag Ráine',
    'Mac Graney': 'Mag Ráine',
    'Grange': 'Gráinseach',
    'Mac Grann': 'Mag Bhrain',
    'Mac Grann': 'Mag Ráine Ó Gréacháin',
    'Grannell': 'Mag Ránaill',
    'Mac Grannell': 'Mag Ránaill',
    'Mac Grannon': 'Mag Raghnainn',
    'Granny': 'Mag Ráine',
    'Mac Granny': 'Mag Ráine',
    'Grant': 'Grant',
    'Mac Grath': 'Mac Craith',
    'Grattan': 'Mag Reachtain',
    'Mac Grattan': 'Mag Reachtain',
    'Graves': 'Ó Griabháin',
    'Mac Graw': 'Mag Raith',
    'Gray': 'Mac Cathail Riabhnaigh',
    'Grayhan (Grayson)': 'Ó Gréacháin',
    'Greacen': 'Ó Gréacháin',
    'Mac Gready': 'Mag Riada',
    'O Gready': 'Ó Greada',
    'Mac Greal': 'Mag Réill',
    'Grealish': 'Mag Riallais',
    'Mac Grealish': 'Mag Riallais',
    'Greally': 'Mag Raollaigh',
    'Mac Greally': 'Mag Raollaigh',
    'Mac Grean': 'Mag Ráine',
    'Greaney': 'Ó Gráinne',
    'O Greaney': 'Ó Gráinne',
    'Greaven': 'Ó Griabháin',
    'Greaves': 'de Gréibh',
    'Greefa': 'Ó Gríofa',
    'O Greefa': 'Ó Gríofa',
    'Greehy': 'Ó Gríocha',
    'O Greehy': 'Ó Gríocha',
    'Green': 'Ó hUaine',
    'Greenan': 'Ó Grianáin',
    'O Greenan': 'Ó Grianáin',
    'Mac Greer': 'Mac Grioghair',
    'Mac Greevy': 'Mag Riabhaigh',
    'Mac Gregan': 'Mag Riagáin',
    'Gregan': 'Ó Gréacháin',
    'Mac Gregor': 'Mac Griogair',
    'Gregory': 'Mac Gréagair',
    'Grehan': 'Ó Gréacháin',
    'O Grehan': 'Ó Gréacháin',
    'Mac Grellish': 'Mag Riallais',
    'Grenaghan': 'Mag Reannacháin',
    'Mac Grenaghan': 'Mag Reannacháin',
    'Mac Grennahan': 'Mag Reannacháin',
    'Grennan': 'Ó Grianáin',
    'O Grennan': 'Ó Grianáin',
    'Mac Grenor': 'Mag Thréinir',
    'Grew': 'Ó Maolchraoibhe',
    'Grew': 'Mac Riabhaigh (Muineachán)',
    'Grey': 'de Grae',
    'Mac Griana': 'Mac Grianna',
    'Gribben': 'Ó Gribín',
    'O Gribben': 'Ó Gribín',
    'Mac Gribbin': 'Mag Roibín',
    'Grierson': 'Mac Grioghair',
    'Mac Grievy': 'Mag Riabhaigh',
    'Mac Griffin': 'Mac Grífín',
    'Griffith': 'Ó Gríofa',
    'Griffy': 'Ó Gríofa',
    'Griffin': 'Ó Gríofa',
    'O Griffy': 'Ó Gríofa',
    'O Griffin': 'Ó Gríofa',
    'Mac Grillan': 'Mag Rialláin',
    'Mac Grillish': 'Mag Riallais',
    'Grimes': 'Ó Gréacháin',
    'Grimley': 'Ó Garmaile',
    'Mac Griskin': 'Mac Cristín',
    'Mac Groany': 'Mag Carramhna',
    'Groarke': 'Mag Ruairc',
    'Mac Groarty': 'Mag Ruartaigh',
    'Groden': 'Mag Rodáin',
    'Grogan': 'Mac Gruagáin',
    'Mac Grogan': 'Mac Gruagáin',
    'Grogan': 'Ó Gruagáin',
    'O Grogan': 'Ó Gruagáin',
    'Mac Gronan': 'Mag Ránainn',
    'Gronel': 'Mag Ránaill',
    'Mac Grory': 'Mag Ruairí',
    'Mac Grotty': 'Mag Ratha',
    'Grourke': 'Mag Ruairc',
    'Growder': 'Mag Bhruadair',
    'Growney': 'Ó Gramhna',
    'O Growney': 'Ó Gramhna',
    'Gruagan': 'Mac Gruagáin',
    'Mac Gruagan': 'Mac Gruagáin',
    'Grubb': 'Mag Rob',
    'Mac Grudder': 'Mag Bhruadair',
    'Grugan': 'Ó Gruagáin',
    'O Grugan': 'Ó Gruagáin',
    'Grumley': 'Ó Garmaile',
    'Grummell': 'Gromail',
    'Grunnell': 'Gromail',
    'Mac Gruane': 'Mac Dhuáin',
    'Guare': 'de Gaor',
    'Gubbins': 'Ó Goibín',
    'Guckian': 'Mag Eochaín',
    'Mac Guckian': 'Mag Eochaín',
    'Mac Guehan': 'Mac Gaoithín',
    'Mac Gueran': 'Mac Géaráin',
    'Guerin': 'Ó Géaráin',
    'O Guerin': 'Ó Géaráin',
    'Mac Guff': 'Mac Dhuibh',
    'Mac Guffin': 'Mac Dhuifinn',
    'Guidera': 'Mac Giodaire',
    'Mac Guigan': 'Mag Uiginn',
    'Mac Guighan': 'Mag Eocháin',
    'Guihan': 'Ó Gaoithín',
    'O Guihan': 'Ó Gaoithín',
    'Mac Guilan': 'Mac Coilín',
    'Guilchrist': 'Mac Giolla Chríost',
    'Guilfoyle': 'Mac Giolla Phóil',
    'Mac Guilfoyle': 'Mac Giolla Phóil',
    'Mac Guill': 'Mag Coill',
    'Mac Guillian': 'Mag Coilín',
    'Guilliland': 'Mac Giolla Fhaoláin',
    'Guilmartin': 'Mac Giolla Mhártain',
    'Guinan': 'Ó Coinneáin',
    'Guinane': 'Ó Coinneáin',
    'O Guinan': 'Ó Coinneáin',
    'O Guinane': 'Ó Coinneáin',
    'Mac Guinea': 'Mag Cionaoith',
    'Guinevan': 'Mac Dhoinneabháin',
    'Guinevan': 'Ó Ceannuáin',
    'O Guinevan': 'Ó Ceannuáin',
    'Mac Guiney': 'Mac Géibheannaigh',
    'Guiney': 'Ó Guiní',
    'Guinee': 'Ó Guiní',
    'O Guiney': 'Ó Guiní',
    'O Guinee': 'Ó Guiní',
    'Mac Guinn': 'Mag Coinn',
    'Guinnane': 'Ó Coinneáin',
    'Guinnaty': 'Mag Fhionnachta',
    'Mac Guinn': 'Mag Coinn',
    'Guinnane': 'Ó Coinneáin',
    'Guinnaty': 'Mag Fhionnachta',
    'Mac Guinness': 'Mag Aonasa',
    'Mac Guire': 'Mag Uidhir',
    'Mac Guirk': 'Mag Coirc',
    'Mac Gurk': 'Mac Oirc',
    'Mac Guirk': 'Mac Oirc',
    'Guiry': 'Ó Gadhra',
    'Guissane': 'Ó Cíosáin',
    'O Guissane': 'Ó Cíosáin',
    'Gulan': 'Ó Golláin',
    'Gullan': 'Ó Golláin',
    'Gullion': 'Gilleán',
    'Mac Gullion': 'Mac Gilleáin',
    'Gully': 'Ó Gabhla',
    'Gumbleton': 'Gumartún',
    'Gunn': 'Mac Giolla Dhoinn',
    'Gunn': 'Mac Giolla Ghunna',
    'Gunnell': 'Mag Conail',
    'Gunner': 'Gunnar',
    'Mac Gunnigan': 'Mac Dhonnagáin',
    'Gunnigle': 'Mag Congail',
    'Gunning': 'Ó Conaing',
    'O Gunning': 'Ó Conaing',
    'Gunshenan': 'Mac Giolla Seanáin',
    'Gurdan': 'Mac Siúrtáin',
    'Mac Gurgan': 'Mac Dhuarcáin',
    'Mac Gurk': 'Mag Oirc',
    'Mac Gurkin': 'Mac Dhuarcáin',
    'Mac Gurl': 'Mag Fhearail',
    'Mac Gurn': 'Mag Corráin',
    'Mac Gurnaghan': 'Mag Mhuirneacháin',
    'Mac Gurrin': 'Mag Corraín',
    'Mac Gurrell': 'Mag Fhearail',
    'Gurry': 'Mac Gothraidh',
    'Mac Gushion': 'Mag Oisín',
    'Mca Guskin': 'Mag Uiscín',
    'Mac Gusty': 'Mag Oiste',
    'Gutherie': 'Ó Laithimh',
    'Guy': 'Guidh',
    'Gware': 'de Gaor',
    'Gweehin': 'Ó Gaoithín',
    'Gwyn': 'Guin',
    'Gwynn': 'Guin',
    'Gyles': 'Ó Glaisne'
}