module.exports = {
    'Habbagan': 'Hobacán',
    'Habbert': 'Hoibeard',
    'Hackett': 'Haicéid (Theas)',
    'Hackett': 'Mac Eachaidh',
    'Hadden': 'Ó hAidín',
    'Haddigan': 'Ó hEideagáin',
    'O Hadian': 'Ó hÉidín',
    'Hadian': 'Ó hÉidín',
    'Hadnett': 'Mac Searraigh',
    'Hafferon': 'Ó hAmhráin',
    'O Haffey': 'Ó hEachaidh',
    'Haffey': 'Ó hEachaidh',
    'Mac Haffy': 'Mac Dhuifíthe',
    'O Hagans': 'Ó hÁgáin',
    'O Hagan': 'Ó hÁgáin',
    'Hagans': 'Ó hÁgáin',
    'Hagan': 'Ó hÁgáin',
    'Haggart': 'Ó hÁgairt',
    'O Haggerty': 'Ó hEigeartaigh',
    'Haggerty': 'Ó hEigeartaigh',
    'O Haghan': 'Ó hEacháin',
    'Haghan': 'Ó hEacháin',
    'Mac Haghey': 'Mac Eachaigh',
    'O Hahessy': 'Ó hAitheasa',
    'Hahessy': 'Ó hAitheasa',
    'Haidee': 'Ó hAidí',
    'Haide': 'Ó hAidí',
    'Haier': 'Ó hAichir',
    'Mac Haig': 'Mac Thaidhg',
    'Haines': 'Ó hEidhin',
    'Haire': 'Ó hÍr',
    'Hair': 'Ó hÍr',
    'Mac Hale': 'Mac Héil',
    'Hales': 'Mac Héil',
    'Hale': 'Mac Héil',
    'Halferty': 'Ó hAilbheartaigh',
    'Halpenny': 'Ó hAilpíne',
    'Hall': 'de Hál',
    'Mac Hall': 'Mac Cathail',
    'Hall': 'Mac Cathail',
    'O Hallahan': 'Ó hAileacháin',
    'Hallahan': 'Ó hAileacháin',
    'Hallan': 'Ó hAllúin',
    'O Hallihy': 'Ó hAilche',
    'O Halley': 'Ó hAilche',
    'Hallihy': 'Ó hAilche',
    'Halley': 'Ó hAilche',
    'O Halligan': 'Ó hAileagáin',
    'Halligan': 'Ó hAileagáin',
    'O Hallihan': 'Ó hAilleacháin',
    'Hallihan': 'Ó hAilleacháin',
    'O Hallinan': 'Ó hAileanáin',
    'Hallinan': 'Ó hAileanáin',
    'Hallin': 'Ó hAilín',
    'Hallion': 'Ó hAilín',
    'O Hallion': 'Ó hAilín',
    'Hallion': 'Ó hAilín',
    'O Hallissey': 'Ó hÁileasa',
    'Hallissey': 'Ó hÁileasa',
    'O Halloran': 'Ó hAllúráin',
    'Halloran': 'Ó hAllúráin',
    'O Halpenny': 'Ó hAilpíne',
    'Halpenny': 'Ó hAilpíne',
    'O Halpin': 'Ó hAilpín',
    'Halpin': 'Ó hAilpín',
    'Haltigan': 'Ó h Ultacháin',
    'Halton': 'de Haltún',
    'Halton': 'Ó h Ultacháin (Fear Manach)',
    'O Halverty': 'Ó hAilbheartaigh',
    'Halverty': 'Ó hAilbheartaigh',
    'O Halvey': 'Ó hAilmhic',
    'Halvey': 'Ó hAilmhic',
    'O Haly': 'Ó hÉilí',
    'Haly': 'Ó hÉilí',
    'Hambery': 'Ó hAinmhire',
    'Hamell': 'Ó hÁmaill',
    'Hamilton': 'Hamaltún',
    'Hamlin': 'Haimlín',
    'Hammondson': 'Mac Ámainn',
    'Hammond': 'Mac Ámainn',
    'Hamsey': 'Ó hAmhsaigh',
    'Hampson': 'Ó hAmhsaigh',
    'Hampton': 'de Hamtún',
    'Hamrock': 'Hamróg',
    'Hanafey': 'Ó hAinfidh',
    'Hanafin': 'Ó hAinifín',
    'O Hanahan': 'Ó hAnnacháin',
    'Hanahan': 'Ó hAnnacháin',
    'O Hanahoe': 'Ó hEanchaí',
    'Hanahoe': 'Ó hEanchaí',
    'Hanaty': 'Ó hIonnachtaigh',
    'Hanberry': 'Ó hAinmhire',
    'Hancock': 'Hancóc',
    'Hand': 'Mag Laithimh',
    'Handbury': 'de Handbura',
    'Haneen': 'Ó hAinchín',
    'Mac Hanfry': 'Mac Hunfraidh',
    'Hanify': 'Ó hAinfidh',
    'Hanihan': 'Ó hAnnacháin',
    'Hankard': 'Hancard',
    'O Hanley': 'Ó hÁinle',
    'Hanley': 'Ó hÁinle',
    'O Hanlon': 'Ó hAnluain',
    'Hanlon': 'Ó hAnluain',
    'Hanna': 'Ó hAnnaidh',
    'O Hannavan': 'Ó hAinmheáin',
    'Hannavan': 'Ó hAinmheáin',
    'Hannell': 'Ó hIonnáil',
    'Hannerty': 'Ó hIonnachtaigh',
    'Hannick': 'Ó hAilmhic',
    'Hannifin': 'Ó hAinifín',
    'Hannify': 'Ó hAinbhith',
    'O Hannigan': 'Ó hAnnagáin',
    'Hannigan': 'Ó hAnnagáin',
    'Hannon': 'Ó hAnnáin',
    'O Hanrahan': 'Ó hAnracháin',
    'Hanrahan': 'Ó hAnracháin',
    'O Hanratty': 'Ó hAnrachtaigh',
    'Hanratty': 'Ó hAnrachtaigh',
    'Hanrick': 'Ó hAnraic',
    'Hanson': 'Ó hAmhsaigh',
    'O Hanvey': 'Ó hAinbhith',
    'Hanvey': 'Ó hAinbhith',
    'Hanwick': 'Ó hAilmhic',
    'O Hara': 'Ó hEára',
    'Hara': 'Ó hEára',
    'Haraghy': 'Ó hEarchaí',
    'Harahoe': 'Ó hEarchaí',
    'Haran': 'Ó hEáráin',
    'Harberd': 'Hoireabard',
    'Harbin': 'Hoirbín',
    'Harbinson': 'Mac Hoirbín',
    'Hardiman': 'Ó hArgadáin',
    'Harden': 'Mac Giolla Deacair',
    'Harding': 'Hairdín',
    'Hardman': 'Hearman',
    'Hardwood': 'Haróid',
    'Hardy': 'Mac Gilolla Deacair',
    'Mac Hardy': 'Mac Cardaigh',
    'O Hare': 'Ó hÍr',
    'Hare': 'Ó hÍr',
    'Mac Harg': 'Mac Giolla Chairge',
    'O Harhen': 'Ó hEáráin',
    'O Haren': 'Ó hEáráin',
    'Harhen': 'Ó hEáráin',
    'Haren': 'Ó hEáráin',
    'Harford': 'de Hearfort',
    'O Hargadan': 'Ó hArgadáin',
    'O Harkins': 'Ó hEarcáin',
    'O Harkin': 'Ó hEarcáin',
    'Harkins': 'Ó hEarcáin',
    'Harkin': 'Ó hEarcáin',
    'Harkey': 'Ó hEarchaidh',
    'Harley': 'Ó hEaraile',
    'Harman': 'Ó hArgadáin',
    'Harmaigh': 'Ó hArmaigh',
    'Harnedy': 'Ó hAirtnéada',
    'Harnett': 'Ó hAirtnéada',
    'O Harney': 'Ó hAthairne',
    'Harney': 'Ó hAthairne',
    'Mac Harnon': 'Mac Thiarnáin',
    'Harnon': 'Ó hEarnáin',
    'Harold': 'Ó hArailt',
    'O Haroughten': 'Ó hArrachtáin',
    'Haroughten': 'Ó hArrachtáin',
    'Harpur': 'Harpúr',
    'Harraher': 'Ó hEarchair',
    'O’Harran': 'Ó hEaráin',
    'Harrel': 'Ó hEarail',
    'O Harrahil': 'Ó hEarail',
    'O Harrigan': 'Ó hArgáin',
    'Harrigan': 'Ó hArgáin',
    'O Harrihy': 'Ó hEarchaí',
    'Harrihy': 'Ó hEarchaí',
    'O Harrily': 'Ó hEaraile',
    'Harrily': 'Ó hEaraile',
    'Harrington': 'Ó hArrachtáin',
    'Harris': 'Ó hEarchaí',
    'Harrison': 'Ó hEarchaí',
    'Harrity': 'Ó hAireachtaigh',
    'Harroe': 'Ó hEarchaí',
    'Mac Harroll': 'Mac Fhearail',
    'Harron': 'Ó hEaráin',
    'Harrot': 'Haróid',
    'Mac Harry': 'Mac Fhearaigh',
    'O Hart': 'Ó hAirt',
    'Hart': 'Ó hAirt',
    'Hartan': 'Ó hArtáin',
    'Hartery': 'Ó hAirtrí',
    'Hartford': 'de Hearfort',
    'O Hartigan': 'Ó hArtagáin',
    'Hartigan': 'Ó hArtagáin',
    'O Hartley': 'Ó hArtaile',
    'Hartley': 'Ó hArtaile',
    'Hartnane': 'Ó hEarnáin',
    'O Hartnett': 'Ó hAirtnéada',
    'Hartnett': 'Ó hAirtnéada',
    'Hartney': 'Ó hAthairne',
    'Harton': 'Ó hArtáin',
    'O Hartry': 'Ó hAirtrí',
    'Hartry': 'Ó hAirtrí',
    'Harty': 'Mac Artaigh (Maigh Eo)',
    'O Harty': 'Ó hArtaigh',
    'Harty': 'Ó hArtaigh',
    'Harvey': 'Ó hAirmhí',
    'Harwood': 'Haróid',
    'Haskin': 'Ó hUiscín',
    'O Hassan': 'Ó hOsáin',
    'Hassan': 'Ó hOsáin',
    'Hassett': 'Ó hAisí',
    'Hassey': 'Ó hAisí',
    'Hassin': 'Ó hOsáin',
    'Hasson': 'Ó hOsáin',
    'Hastie': 'Mac Oiste',
    'Hastings': 'Ó hOistín',
    'Hasting': 'Ó hOistín',
    'Hatton': 'Mac Giolla Chatáin',
    'O Haugh': 'Ó hEachach',
    'Haugh': 'Ó hEachach',
    'Haughan': 'Ó hEacháin',
    'Mac Haughey': 'Mac Eachaidh',
    'O Haughian': 'Ó hEachaín',
    'Haughian': 'Ó hEachaín',
    'O Haughey': 'Ó hEachaidh',
    'O Haghey': 'Ó hEachaidh',
    'Haughey': 'Ó hEachaidh',
    'Haghey': 'Ó hEachaidh',
    'Haughney': 'Mac Fhachtna',
    'O Haughran': 'Ó hArracháin',
    'Haughran': 'Ó hArracháin',
    'Haughton': 'de Hochtún',
    'O Haveran': 'Ó hAmhráin',
    'O Havern': 'Ó hAmhráin',
    'Haveran': 'Ó hAmhráin',
    'Havern': 'Ó hAmhráin',
    'O Haverty': 'Ó hAbhartaigh',
    'Haverty': 'Ó hAbhartaigh',
    'Havigan': 'Ó hÉimheacháin',
    'Hawe': 'Ó hEachach',
    'Hawkins': 'Ó hEacháin',
    'Mac Hay': 'Mac Aodha',
    'Hay': 'Ó hAodha',
    'O Hayden': 'Ó hEideáin',
    'Hayden': 'Ó hEideáin',
    'Hayes': 'Ó hAodha',
    'Hayles': 'Mac Héil',
    'Haynes': 'Ó hEidhin',
    'Hays': 'de Hae',
    'Hayward': 'Héibheart',
    'Hazlegrove': 'Mac Collchoill',
    'Hazelton': 'Mac Conchollchoille',
    'Hazel': 'Mac Conchollchoille',
    'O Hea': 'Ó hAodha',
    'Hea': 'Ó hAodha',
    'Heagan': 'Mac Aogáin',
    'Heagney': 'Ó hÉignigh',
    'Healihy': 'Ó hÉilithe',
    'Healon': 'Ó hAoláin',
    'O Healy': 'Ó hÉilí',
    'Healy': 'Ó hÉilí',
    'Henahan': 'Ó hÉineacháin',
    'O Heaney': 'Ó hÉanna',
    'Heaney': 'Ó hÉanna',
    'O Heanue': 'Ó hÉanú',
    'Heanue': 'Ó hÉanú',
    'O Heaphy': 'Ó hÉafaigh',
    'Heaphy': 'Ó hÉafaigh',
    'O Heare': 'Ó hÍr',
    'O Hear': 'Ó hÍr',
    'Heare': 'Ó hÍr',
    'Hear': 'Ó hÍr',
    'Hearaghty': 'Ó hOireachtaigh',
    'Hearne': 'Ó hEathírn',
    'Hearn': 'Ó hEathírn',
    'Hearnon': 'Ó hIarnáin',
    'O Hearty': 'Ó hAghartaigh',
    'Hearty': 'Ó hAghartaigh',
    'Heary': 'Ó hIorua',
    'Mac Heath': 'Mac Shíthigh',
    'O Heaven': 'Ó hEimhín',
    'Heaven': 'Ó hEimhín',
    'O Heavy': 'Ó hÉimhigh',
    'Heavy': 'Ó hÉimhigh',
    'Heden': 'de Héadún',
    'O Hederman': 'Ó hEadromáin',
    'Hederman': 'Ó hEadromáin',
    'O Hedian': 'Ó hÉidín',
    'Hedian': 'Ó hÉidín',
    'Hedigan': 'Ó hEideagáin',
    'O Hedivan': 'Ó hEadamháin',
    'Hedivan': 'Ó hEadamháin',
    'O Heelan': 'Ó hAoláin',
    'Heelan': 'Ó hAoláin',
    'Heelon': 'Ó hAoilleacháin',
    'O Heenan': 'Ó hAonáin',
    'Heenan': 'Ó hAonáin',
    'Heery': 'Ó hÍorua',
    'O Heever': 'Ó hÍomhair',
    'Heever': 'Ó hÍomhair',
    'O Heffernan': 'Ó hIfearnáin',
    'Heffernan': 'Ó hIfearnáin',
    'Mac Heffy': 'Mac Eachaidh',
    'O Hefron': 'Ó hÉimhrín',
    'Hefron': 'Ó hÉimhrín',
    'O Hegan': 'Ó hAogáin',
    'Hegan': 'Ó hAogáin',
    'O Hegarty': 'Ó hÉigeartaigh',
    'Hegarty': 'Ó hÉigeartaigh',
    'Heggert': 'Ó hAgairt',
    'O Hegney': 'Ó hÉignigh',
    'Hegney': 'Ó hÉignigh',
    'O Hehir': 'Ó hAichir',
    'Hehir': 'Ó hAichir',
    'Heins': 'Ó hEidhin',
    'Helbert': 'Hoileabard',
    'Helehan': 'Ó hAoilleacháin',
    'O Helen': 'Ó hAoláin',
    'Helen': 'Ó hAoláin',
    'O Helberty': 'Ó hAilbheartaigh',
    'Helberty': 'Ó hAilbheartaigh',
    'Hempsey': 'Ó hAmhsaigh',
    'Hempson': 'Ó hAmhsaigh',
    'O Henaghan': 'Ó hÉineacháin',
    'Henaghan': 'Ó hÉineacháin',
    'O Henchy': 'Ó hAonasa',
    'Henchy': 'Ó hAonasa',
    'Henderson': 'Mac Aindréis',
    'Henderson': 'Mac Éinrí',
    'O Hendley': 'Ó hÁinle',
    'Hendley': 'Ó hÁinle',
    'Hendrick': 'Ó hEanraic',
    'Hendron': 'Mac Éinrí',
    'Mac Hendry': 'Mac Éinrí',
    'Hendry': 'Mac Éinrí',
    'Henebry': 'de Hindeberg',
    'O Henehan': 'Ó hÉanacháin',
    'Henehan': 'Ó hÉanacháin',
    'Mac Henery': 'Mac Innéirí',
    'O Henery': 'Ó hInnéiri',
    'Henery': 'Ó hInnéiri',
    'O Hennelly': 'Ó hIonnaile',
    'Hennelly': 'Ó hIonnaile',
    'Hennerty': 'Ó hIonnachtaigh',
    'O Hennessy': 'Ó hAonasa',
    'Hennessy': 'Ó hAonasa',
    'Hennigan': 'Ó hÉanadáin',
    'O Henrick': 'Ó hEanraic',
    'Henrick': 'Ó hEanraic',
    'Henright': 'Mac Ionrachtaigh',
    'O Henrion': 'Ó hIonráin',
    'Henrion': 'Ó hIonráin',
    'Mac Henry': 'Mac Éinrí',
    'Henry': 'Mac Éinrí',
    'O Henry': 'Ó hInnéirí',
    'Henry': 'Ó hInnéirí',
    'Hensey': 'Ó hAonasa',
    'O Heraghty': 'Ó hOireachtaigh',
    'Heraghty': 'Ó hOireachtaigh',
    'O Heraghy': 'Ó hEarchaí',
    'Heraghy': 'Ó hEarchaí',
    'Herald': 'Ó hEarail',
    'O Heran': 'Ó Earáin',
    'Heran': 'Ó Earáin',
    'Heraty': 'Ó hOireachtaigh',
    'Herbert': 'Hoireabard',
    'Herbertson': 'Mac Hoireabaird',
    'Herdman': 'Hearman',
    'Hereward': 'Hoireabhard',
    'Herford': 'de Hearfort',
    'Herguson': 'Mac Fhearghasa',
    'Herky': 'Ó hEarca',
    'O Herlihy': 'Ó hIarlatha',
    'Herlihy': 'Ó hIarlatha',
    'Hernon': 'Ó hIarnáin',
    'Heron': 'Mac Giolla Chearáin',
    'Herr': 'Ó hAichir',
    'Herran': 'Ó hEaráin',
    'O Herreran': 'Ó Eararáin',
    'Herreran': 'Ó Eararáin',
    'Herrick': 'Ó hEirc',
    'Herrigan': 'Ó hArragáin',
    'Hertnan': 'Ó hEarnáin',
    'Herward': 'Hoireabhard',
    'O Heskin': 'Ó hUiscín',
    'Heskin': 'Ó hUiscín',
    'O Heslin': 'Ó hEislin',
    'Heslin': 'Ó hEislin',
    'O Hession': 'Ó hOisín',
    'Hession': 'Ó hOisín',
    'Hester': 'Ó hOistir',
    'Hestin': 'Ó hOistín',
    'Heuson': 'Mac Aodha',
    'Hevaghan': 'Ó hÉimheacháin',
    'Hever': 'Ó hÍomhair',
    'Heveran': 'Ó hÉimhrín',
    'Hevey': 'Ó hÉimhigh',
    'Hevican': 'Ó hEimheacháin',
    'Heuston': 'Mac Giolla tSeachlainn',
    'Hewett': 'Húighéid',
    'Hewlitt': 'Húiléid',
    'Hewson': 'Mac Aodha',
    'Heyland': 'Ó hAoláin',
    'O Heyne': 'Ó hEidhin',
    'Heyne': 'Ó hEidhin',
    'Hibbard': 'Hibeard',
    'O Hickey': 'Ó hÍcí',
    'Hickey': 'Ó hÍcí',
    'Hiffernan': 'Ó hIlfearnáin',
    'O Higgins': 'Ó hUiginn',
    'Higgins': 'Ó hUiginn',
    'Higginson': 'Mac Uiginn',
    'Highland': 'Ó hAoláin',
    'Hilbert': 'Hoileabard',
    'Hilferty': 'Ó hAilbheartaigh',
    'Hill': 'an Chnoic',
    'Hilland': 'Ó hIoláin',
    'Hillan': 'Ó hIoláin',
    'Hillary': 'Ó hIrile',
    'Hillee': 'Ó hIcheallaigh',
    'Hilligan': 'Ó hAilleagaín',
    'Hinan': 'Ó hEidhneáin',
    'Mac Hinch': 'Mac Aonais',
    'Hinchy': 'Ó hInse',
    'Hiney': 'Ó hAidhne',
    'Hingerdell': 'Ó hIongardail',
    'O Hingerty': 'Ó hInneachtaigh',
    'Hingerty': 'Ó hInneachtaigh',
    'Mac Hinny': 'Mac Coinnigh',
    'Hiraghy': 'Ó hEarchaí',
    'Hirrell': 'Ó hIril',
    'Hirelly': 'Ó hIrile',
    'O Hishon': 'Ó hOisín',
    'Hishon': 'Ó hOisín',
    'O Hiskey': 'Ó hUisce',
    'Hiskey': 'Ó hUisce',
    'Histon': 'Ó hOistín',
    'Hoad': 'Ó hÓdach',
    'Hode': 'Ó hÓdach',
    'Hoare': 'de Hóra',
    'Hoar': 'de Hóra',
    'O Hoban': 'Ó hÚbáin',
    'Hoban': 'Ó hÚbáin',
    'Hobart': 'Hoibeard',
    'Hobbagan': 'Hobacán',
    'Hobbikin': 'Mac Oibicín',
    'Hobbs': 'Hob',
    'Hobkins': 'Mac Oibicín',
    'Hobkin': 'Mac Oibicín',
    'Hobson': 'Mac Hob',
    'Hoctor': 'Ó hEachtair',
    'Hodge': 'Hoiste',
    'Hodgkin': 'Hoisticín',
    'Hodgkins': 'Mac Hoisticín',
    'Hodnett': 'Mac Searraigh',
    'O Hoey': 'Ó hEochaidh',
    'Hoey': 'Ó hEochaidh',
    'O Hogan': 'Ó hÓgáin',
    'Hogan': 'Ó hÓgáin',
    'O Hogart': 'Ó hÓgairt',
    'Hogart': 'Ó hÓgairt',
    'Hogarty': 'Ó hÓgartaigh',
    'Hoggan': 'Ó hÁgáin',
    'Hogg': 'Ó hAogáin',
    'Hoins': 'Ó hEoghain',
    'Holey': 'Ó hUallaigh',
    'O Holian': 'Ó hOláin',
    'Holian': 'Ó hOláin',
    'Holland': 'Ó hAoláin Ó hUallacháin',
    'O Hollegan': 'Ó hAileagáin',
    'Hollegan': 'Ó hAileagáin',
    'O Holleran': 'Ó hAllúráin',
    'Holleran': 'Ó hAllúráin',
    'Holloway': 'Ó hAilmhic',
    'Holly': 'Mac Cuilinn',
    'Hollywood': 'Ó Cuileannáin',
    'Holmes': 'Mac Thómais',
    'Homes': 'Mac Thómais',
    'Holohan': 'Ó hUallacháin',
    'Holoway': 'de Halbhuí',
    'Holt': 'Hólt',
    'Holtan': 'Ó hUltáin',
    'Holywood': 'Halabhóid',
    'Homes': 'Mac Thomáis',
    'Honahan': 'Ó hUanacháin',
    'O Honan': 'Ó hEoghanáin',
    'Honan': 'Ó hEoghanáin',
    'Hone': 'Ó hEoghain',
    'Honeen': 'Ó hUaithnín',
    'Hooban': 'Ó h Úbáin',
    'O Hood': 'Ó hUid',
    'Hood': 'Ó hUid',
    'Hoolahan': 'Ó hUallacháin',
    'O Hoolan': 'Ó hUallacháin',
    'Hoolan': 'Ó hUallacháin',
    'Hoonihan (Hounihan)': 'Ó hUanacháin',
    'O Hooney': 'Ó hUainí',
    'Hooney': 'Ó hUainí',
    'Horriskey': 'Ó hUaruisce',
    'Hope': 'Hob',
    'Hop': 'Hob',
    'Hopkins': 'Ó hOibicín',
    'Hopps': 'Mac Hob',
    'Hopson': 'Mac Hob',
    'O Hora': 'Ó hÓra',
    'Hora': 'Ó hÓra',
    'O Horahan': 'Ó hArracháin',
    'Horahan': 'Ó hArracháin',
    'O Horoghy': 'Ó hEarchaí',
    'O Horahoe': 'Ó hEarchaí',
    'O Horaho': 'Ó hEarchaí',
    'Horahoe': 'Ó hEarchaí',
    'Horaho': 'Ó hEarchaí',
    'Horoghy': 'Ó hEarchaí',
    'O Horan': 'Ó hÓráin',
    'Horan': 'Ó hÓráin',
    'Hore': 'de Hóra',
    'O Horgan': 'Ó hArgáin',
    'Horgan': 'Ó hArgáin',
    'Horish': 'Ó h Uarais',
    'Horisky': 'Ó hUaruisce',
    'O Horkan': 'Ó hOrcáin',
    'Horkan': 'Ó hOrcáin',
    'Horrigan': 'Ó hArragáin',
    'Horseman': 'Mac Eachaidh',
    'Horsey': 'de Hórsaigh',
    'Horton': 'Ó hArtáin',
    'Hosey': 'Ó hEosa',
    'Hoskins': 'Ó hUiscín',
    'Mac Hosty': 'Mac Oiste',
    'Hosty': 'Mac Oiste',
    'Hotchkin': 'Hoisticín',
    'O Hough': 'Ó hEochach',
    'Houghegan': 'Mac Eochagáin',
    'Houghton': 'de Hochtún',
    'Houghy': 'Ó hEochaidh',
    'O Houlahan': 'Ó hUallacháin',
    'Houlahan': 'Ó hUallacháin',
    'O Hourahan': 'Ó hAnracháin',
    'Hourahan': 'Ó hAnracháin',
    'O Hourigan': 'Ó hAnragáin',
    'Hourigan': 'Ó hAnragáin',
    'O Hourihane': 'Ó hAnradháin',
    'O Hourihan': 'Ó hAnradháin',
    'Hourihane': 'Ó hAnradháin',
    'Hourihan': 'Ó hAnradháin',
    'O Houriskey': 'Ó hUaruisce',
    'Houriskey': 'Ó hUaruisce',
    'Houston': 'Mac Úistín',
    'Hoverty': 'Ó hÓghartaigh',
    'Howard': 'Ó hÍomhair',
    'Howay': 'Ó hEochaidh',
    'Howe': 'Ó hEochaidh',
    'Howell': 'Mac Héil',
    'Howels': 'Mac Haol',
    'Howen': 'Ó hEoghain',
    'Howes': 'Ó hEochaidh',
    'Howie': 'Mac Giolla Dhuibh',
    'Howitt': 'Húighéid',
    'Howlet': 'Húiléid',
    'O Howley': 'Ó hUallaigh',
    'Howley': 'Ó hUallaigh',
    'Howling': 'Húilín',
    'Howlin': 'Húilín',
    'O Hoy': 'Ó hEochaidh',
    'Hoy': 'Ó hEochaidh',
    'Hoyles': 'Mac Giolla Choille',
    'Hoyle': 'Mac Giolla Choille',
    'O Hoyne': 'Ó hEoghain',
    'Hoyne': 'Ó hEoghain',
    'O Huadhaigh': 'Ó hUadhaigh',
    'Huban': 'Ó hÚbáin',
    'Hubbard': 'Hobard',
    'Hubbock': 'Hobac',
    'Huddy': 'Ó hUada',
    'Hueson': 'Mac Aodha',
    'Hue': 'Mac Aodha',
    'Huett': 'Húighéid',
    'O Huey': 'Ó hEochaidh',
    'Huey': 'Ó hEochaidh',
    'Huggins': 'Ó hAogáin',
    'Hugginson': 'Mac Huigín',
    'Mac Hugh': 'Mac Aodha',
    'Hughes': 'Ó hAodha',
    'Hughston': 'Mac Úistín',
    'MAc Hugo': 'Mac Cuag',
    'Huleat': 'Húiléid',
    'O Hultaghan': 'Ó h Ultacháin',
    'Hultaghan': 'Ó h Ultacháin',
    'Humfrey': 'Unfraidh',
    'Humphreys': 'Mac Unfraidh',
    'O Huneen': 'Ó hUaithnín',
    'Huneen': 'Ó hUaithnín',
    'Hunt': 'Ó Fiaich',
    'Hunter': 'Ó Fiachra',
    'O Hure': 'Ó hIomhair',
    'Hure': 'Ó hIomhair',
    'O Hurley': 'Ó hUrthuile',
    'Hurley': 'Ó hUrthuile',
    'Hurney': 'Ó hUrnaí',
    'Hurroe': 'Ó hEarchaí',
    'Hurrell': 'Ó hEarail',
    'Hurst': 'Ó hÓrsaigh',
    'O Hussey': 'Ó hEosa',
    'Hussey': 'Ó hEosa',
    'O Hussian': 'Ó hOisín',
    'Hussian': 'Ó hOisín',
    'Huston': 'Mac Úistín',
    'Hutch': 'Huiste',
    'Hutchinson': 'Mac Úistín',
    'Hyde': 'de Híde',
    'O Hyland': 'Ó hAoláin',
    'Hyland': 'Ó hAoláin',
    'Hynan': 'Ó hEidhneáin',
    'Hynes': 'Ó hEidhin',
    'Hyney': 'Ó hAidhne'
}