module.exports = {
    'Iago': 'Iagó',
    'Ianson': 'Mac Iain',
    'Igoe': 'Mac Iagó',
    'Igo': 'Mac Iagó',
    'Mac Ilboy': 'Mac Giolla Bhuí',
    'MAc Ilchon': 'Mac Mhíolchon',
    'Mac Ilderry': 'Mac Giolla Dorcha',
    'Mac Ildoon': 'Mac Mhaoldúin',
    'Mac Ildowie': 'Mac Gilla Dubhaigh',
    'Mac Ildowney': 'Mac Giolla Domhnaigh',
    'Ildowney': 'Mac Giolla Domhnaigh',
    'Mac Ilduff': 'Mac Giolla Dhuibh',
    'Mac Olee': 'Mac an Lia',
    'Mac Ileese': 'Mac Giolla Íosa',
    'Mac Ilfatroci': 'Mac Giolla Phádraig',
    'Mac Ilgorm': 'Mac Giolla Ghoirm',
    'Mac Ilhagga': 'Mac Giolla Chairge',
    'Mac Ilhair': 'Mac Giolla Chathair',
    'Mac Ilhaney': 'Mac Giolla Chainnigh',
    'MAc Ilhargy': 'Mac Gillla Chairge',
    'Mac Ilharry': 'Mac Giolla Charraigh',
    'Mac Ilhatton': 'Mac Giolla Chatáin',
    'Mac Ilhenny': 'Mac Giolla Chainnigh',
    'Ilhenny': 'Mac Giolla Chainnigh',
    'Mac Ilheron': 'Mac Giolla Chiaráin',
    'Mac Ilholm': 'Mac Giolla Cholaim',
    'Mac Ilhone': 'Mac Giolla Chomhain',
    'Mac Ilhoney': 'Mac Giolla Chainnigh',
    'Mac Ilhoyle': 'Mac Giolla Chomhaill',
    'Mac Ilhun': 'Mac Mhíolchon',
    'Mac Illicuddy': 'Mac Giolla Chuda',
    'Mac Ilmatha': 'Mac Giolla Mhaith',
    'Mac Ilmay': 'Mac Giolla Mhaith',
    'Mac Ilmoil': 'Mac Giolla Mhaoil',
    'Mac Ilmoyle': 'Mac Giolla Mhaoil',
    'Mac Ilmunn': 'Mac Giolla Munna',
    'Mac Ilmurray': 'Mac Giolla Mhuire',
    'Mac Ilpatrick': 'Mac Giolla Phádraig',
    'Mac Ilrath': 'Mac Giolla Riabhaigh',
    'Mac Irea': 'Mac Giolla Riabhaigh',
    'Mac Ilreavy': 'Mac Giolla Riabhnaigh',
    'Mac Ilroy': 'Mac Giolla Rua',
    'Ilroy': 'Mac Giolla Rua',
    'Mac Ilvany': 'Mac Giolla Mheana',
    'Mac Ilveen': 'Mac Giolla Mhín',
    'Mac Ilwaine': 'Mac Giolla Bháin',
    'Mac Ilwee': 'Mac Giolla Bhuí',
    'Ilwee': 'Mac Giolla Bhuí',
    'Mac Ilwraith': 'Mac Giolla Riabhaigh',
    'Mac Inally': 'Mac an Fhailigh',
    'Mac Inch': 'Mac Aonais',
    'Mac Indoo': 'Mac Conduibh',
    'Mac Ineely': 'Mac Conghaile',
    'Mac Inerney': 'Mac an Airchinnigh',
    'Mac Inesker': 'Mac an Iascair',
    'Inglis': 'Inglis',
    'Ingoldsby': 'Mac an Ghallóglaigh',
    'Ingram': 'Iongram',
    'Mac Innes': 'Mac Aonais',
    'Innes': 'Mac Aonais',
    'Mac Inoulty': 'Mac an Ultaigh',
    'Mac Ireavy': 'Mac Giolla Riabhaigh',
    'Inright': 'Mac an Ionrachtaigh',
    'Mac Inroe': 'Mac Conrua',
    'Mac Intaggart': 'Mac an tSagairt',
    'Mac Intee': 'Mac an tSaoi',
    'Mac Inteer': 'Mac atn tSaoir',
    'Mac Intosh': 'Mac an Taoisigh',
    'Mac Intyre': 'Mac an tSaoir',
    'Ireland': 'Írleont',
    'Irish': 'Íréis',
    'Irrington': 'Ó hArrachtáin',
    'Irvine': 'Ó hEireamhóin',
    'Irwin': 'Ó hEireamhóin',
    'Isdell': 'Istéil',
    'Mac Iveagh': 'Mac an Bheatha',
    'Mac Ivers': 'Mac Íomhair',
    'Mac Iver': 'Mac Íomhair',
    'Ivis': 'Mac Íomhair',
    'Mac Ivor': 'Mac Íomhair',
    'Ivory': 'Ó hUidhrín',
};