module.exports = {
    'Jack': 'Seac',
    'Jackman': 'Seac',
    'Jackson': 'Mac Siacais',
    'Jacob': 'Iácób',
    'Jacques': 'Siacas',
    'Jaffery': 'Seafraidh',
    'Jago': 'Iagó',
    'James': 'Séamas',
    'Jameson': 'Mac Séamais',
    'Jarman': 'Gearmán',
    'Jarrett': 'Gearóid',
    'Jarvis': 'Gearbhás',
    'Jefferson': 'Mac Seafraidh',
    'Jeffers': 'Mac Seafraidh',
    'Jeffery': 'Seafraidh',
    'Jeffries': 'Mac Seafraidh',
    'Jemison': 'Mac Séamais',
    'Jenkin': 'Seinicín',
    'Jenkins': 'Mac Seinicín',
    'Jenkinson': 'Mac Seinicín',
    'Jennings': 'Mac Sheoinín',
    'Jerety': 'Mag Oireachtaigh',
    'Jermyn': 'Gearmann',
    'Jerrett': 'Gearóid',
    'Jervis': 'Gearbhás',
    'Mac Jimpsey': 'Mac Dhíomasaigh',
    'Johnman': 'Mac Iain',
    'Johnson': 'Mac Seáin',
    'Johnston': 'Mac Seáin',
    'Johnstone': 'Mac Seáin',
    'Joie': 'Seoigh',
    'Jones': 'Mac Seoin',
    'Jordan': 'Mac Shiúrtáin',
    'Jurdan': 'Mac Shiúrtáin',
    'Joyce': 'Seoigh',
    'Joyner': 'Siúnéir',
    'Joynt': 'de Siúnta',
    'Judge': 'Mac an Bhreithiúnaigh',
    'Judge': 'Mac an Bhreithiún',
    'Julien': 'Gilleán',
    'Julian': 'Gilleán'
};