module.exports = {
    'Kaddel': 'Cadal',
    'Mac Kady': 'Mac Ádaigh',
    'Mac Kage': 'Mac Thaidhg',
    'Mac Kague': 'Mac Thaidhg',
    'Mac Kaine': 'Mac Catháin',
    'Kaine': 'Ó Catháin',
    'Kale': 'Mac Cathail',
    'Mac Kalshander': 'Mac Alsandair',
    'Kalshander': 'Mac Alsandair',
    'O Kanavaghan': 'Ó Connmhacáin',
    'Kanavaghan': 'Ó Connmhacáin',
    'Mac Kane': 'Mac Catháin',
    'Kane': 'Mac Catháin',
    'O Kane': 'Ó Catháin',
    'Kane': 'Ó Catháin',
    'Mac Kangley': 'Mac Ceanglaigh',
    'Kangley': 'Mac Ceanglaigh',
    'Kappock': 'de Ceapóg',
    'Mac Karee': 'Mac Fhearaigh',
    'Mac Karel': 'Mac Fhearail',
    'Kavanagh': 'Caomhánach',
    'Mac Kavanagh': 'Mac Caomhánaigh',
    'Mac Kay': 'Mac Aodha',
    'Kay': 'Mac Aodha',
    'Mac Kedian': 'Mac Cadáin',
    'Kedian': 'Mac Cadáin',
    'Mac Keadian': 'Moc Cadáin',
    'Mac Keady': 'Mac Céidigh (Corcaigh)',
    'Mac Keady': 'Mac Céadaigh',
    'Keady': 'Mac Céadaigh',
    'Mac Keague': 'Mac Thaidhg',
    'Mac Keag': 'Mac Thaidhg',
    'Keague': 'Mac Thaidhg',
    'Keag': 'Mac Thaidhg',
    'Mac Keaghery': 'Mac Fhiachra',
    'Keaghery': 'Mac Fhiachra',
    'Keahan': 'Mac Caocháin',
    'O Kealaghan': 'Ó Céileacháin',
    'Kealaghan': 'Ó Céileacháin',
    'O Keally': 'Ó Caollaí',
    'O Kealy': 'Ó Caollaí',
    'Keally': 'Ó Caollaí',
    'Kealy': 'Ó Caollaí',
    'Mac Keamish': 'Mac Shéamais',
    'Mac Kean': 'Mac Eáin (Albanach)',
    'Mac Keane': 'Mac Catháin (An Clár)',
    'Keane': 'Mac Catháin (An Clár)',
    'O Keane': 'O Céin',
    'Keane': 'O Céin',
    'Mac Keany': 'O Cianaigh',
    'Keappock': 'de Ceapóg',
    'Kearnes': 'O Ciaráin',
    'Kearn': 'O Ciaráin',
    'Mac Kearney': 'Mac Cearnaigh',
    'O Kearney': 'Ó Cearnaigh',
    'Kearney': 'Ó Cearnaigh',
    'O Kearney': 'Ó Catharnaigh',
    'Kearney': 'Ó Catharnaigh',
    'Kearon': 'Ó Ciaráin',
    'Kearse': 'Mac Fhiarais',
    'Kearsey': 'Ciarasach',
    'Kearson': 'Mac Fhiarais',
    'Keary': 'Mac Giolla Chéire',
    'Kilkeary': 'Mac Giolla Chéire',
    'Mac Keary': 'Mac Fhiachra',
    'O Keary': 'Ó Ciara',
    'Keary': 'Ó Ciara',
    'Keating': 'Céitinn',
    'Mac Keating': 'Mac Céitín',
    'Keatley': 'O Gatlaoich',
    'O Keaty': 'O Céataí',
    'Keaty': 'O Céataí',
    'Mac Keaveny': 'Mac Géibheannaigh',
    'O Keaveney': 'Ó Géibheannaigh',
    'Keaveney': 'Ó Géibheannaigh',
    'Mac Keaver': 'Mac Íomhair',
    'O Keavy': 'Ó Ciabhaigh',
    'Keavy': 'Ó Ciabhaigh',
    'Keawell': 'Mac Camhaoil',
    'Mac Kechnie': 'Mac Eacharna',
    'Mac Kee': 'Mac Aoidh',
    'Kee': 'Mac Aoidh',
    'O Keeffe': 'Ó Caoimh',
    'Keeffe': 'Ó Caoimh',
    'Mac Keefrey': 'Mac Fhiachra',
    'Mac Keegan': 'Mac Aogáin',
    'Keegan': 'Mac Aogáin',
    'Mac Keehan': 'Mac Caocháin',
    'Keehan': 'Mac Caocháin',
    'O Keelan': 'Ó Céileacháin',
    'Keelan': 'Ó Céileacháin',
    'O Keelty': 'O Caoilte',
    'Keelty': 'O Caoilte',
    'O Keely': 'O Caollaí',
    'Keely': 'O Caollaí',
    'Mac Keeman': 'Mac Shíomóin',
    'Mac Keemon': 'Mac Shíomóin',
    'Mac Keen': 'Mac Catháin',
    'O Keenahan': 'Ó Coinneacháin',
    'Keenahan': 'Ó Coinneacháin',
    'Mac Keenan': 'Mac Fhinín',
    'O Keenan': 'Ó Cianáin',
    'Keenan': 'Ó Cianáin',
    'Keeney': 'Ó Cianaigh',
    'Mac Keeney': 'Mac Éanna',
    'Keerawin': 'Ó Ciarubháin',
    'Keerivick': 'Ó Ciarmhaic',
    'Keeshan': 'Ó Ciseáin',
    'Keesig': 'Cíosóg',
    'O Keevane': 'Ó Ciabháin',
    'O Keevan': 'Ó Ciabháin',
    'Keevane': 'Ó Ciabháin',
    'Keevan': 'Ó Ciabháin',
    'Mac Keever': 'Mac Íomhair',
    'Keevers': 'Mac Íomhair',
    'Keevey': 'Ó Ciabhaigh',
    'Keevlin': 'Ó Cibhlín',
    'Kegg': 'Mac Thaidhg',
    'Keig': 'Mac Thaidhg',
    'Kegley': 'O Coigligh',
    'Mac Kegney': 'Mac Éignigh',
    'Keheerin': 'Mac Eithírn',
    'Keher': 'Ó Cathaoir',
    'Cahir': 'Ó Cathaoir',
    'Kehir': 'Ó Cathaoir',
    'Keherney': 'Ó Catharnaigh',
    'Kehigan': 'Mac Eochagáin',
    'Mac Kehilly': 'Mac Caochlaoich',
    'Kehilly': 'Mac Caochlaoich',
    'Kehoe': 'Mac Eochaidh',
    'O Keighron': 'Ó Cíocharáin',
    'Keighron': 'Ó Cíocharáin',
    'Mac Keighry': 'Mac Fhiachra',
    'Mac Keeghry': 'Mac Fhiachra',
    'Keighry': 'Mac Fhiachra',
    'Mac Keeghry': 'Mac Fhiachra',
    'Keightley': 'Ó Gatlaoich',
    'Keillips': 'Mac Fhilib',
    'O Keiltagh': 'Ó Caoilte',
    'Keiltagh': 'Ó Caoilte',
    'O Keily': 'Ó Cadhla',
    'Keily': 'Ó Cadhla',
    'Keirsey': 'Ciarasach',
    'Mac Keith': 'Mac Shíthigh',
    'Keitley': 'Ó Gatlaoich',
    'Mac Keleghan': 'Mac Ceallacháin',
    'O Kelaghan': 'Ó Céileacháin',
    'Kelaghan': 'Ó Céileacháin',
    'Mac Kellan': 'Mac Coilín',
    'Kellard': 'Ó Céileachair',
    'Keller': 'Ó Céileachair',
    'Kelledy': 'Ó Callada',
    'Kellegher': 'Ó Céileachair',
    'Kellegy': 'Ó Calgaigh',
    'O Kelleher': 'O Céileachair',
    'Kelleher': 'O Céileachair',
    'Mac Kellen': 'Mac Aileáin',
    'Kellerlaan': 'Mac an Fhirléinn',
    'Mac Kellop': 'Mac Fhilib',
    'Mac Kelly': 'Mac Ceallaigh',
    'O Kelly': 'Ó Ceallaigh',
    'Kelly': 'Ó Ceallaigh',
    'Mac Kelshenter': 'Mac Alsandair',
    'Mac Kelvey': 'Mac Giolla Bhuí',
    'Mac Elwee': 'Mac Giolla Bhuí',
    'Mac Kelvey': 'Mac Calbhaigh',
    'Mac Kemmin': 'Mac Ámainn',
    'Kenchyla': 'Cinsealach',
    'O Kendillon': 'Ó Caoindealáir',
    'Kendillon': 'Ó Caoindealáir',
    'Mac Kendrick': 'Mac Eanraic',
    'Kendrick': 'Mac Eanraic',
    'O Kendrigan': 'Ó Cinndeargáin',
    'Kendrigan': 'Ó Cinndeargáin',
    'Mac Kendry': 'Mac Éinrí',
    'Kendry': 'Mac Éinrí',
    'O Kenealy': 'Ó Cinnaolaidh',
    'Kenealy': 'Ó Cinnaolaidh',
    'Kenefick': 'Ciniféic',
    'Kenerney': 'Mac an Airchinnigh',
    'Mac Kenery': 'Mac Éinrí',
    'Mac Keniry': 'Mac Innéirí',
    'Keniry': 'Mac Innéirí',
    'Mac Kenna': 'Mac Cionaoith',
    'Kenna': 'Mac Cionaoith',
    'Mac Keenan': 'Mac Fhionnáin',
    'Kennane': 'Ó Coineáin',
    'Kennealy': 'Ó Cinnaolaidh',
    'O Kennedy': 'Ó Cinnéide',
    'Kennedy': 'Ó Cinnéide',
    'Kennefeck': 'Ciniféic',
    'Kennellan': 'Ó Caoinnealáin',
    'Kennelly': 'Mac an Fhailí',
    'Kenning': 'Mac Coinín',
    'Kennon': 'Mac Coinín',
    'Kennish': 'Mac Naois',
    'Mac Kenny': 'Mac Cionaoith',
    'Kenny': 'Mac Cionaoith',
    'O Kenny': 'Ó Cionaoith',
    'Kenny': 'Ó Cionaoith',
    'Kenrick': 'Mac Eanraic',
    'Kent': 'Ceannt',
    'Mac Kenty': 'Mac an tSaoi',
    'Kenure': 'Mac Fhionnbhairr',
    'Kenyon': 'Mac Coinín',
    'Mac Kenzie': 'Mac Coinnigh',
    'Mac Keo': 'Mac Eochaidh',
    'Keogan': 'Ó Ceogáin',
    'Mac Keogan': 'Mac Eochagáin',
    'Keogan': 'Mac Eochagáin',
    'Mac Keogh': 'Mac Eochaidh',
    'Keogh': 'Mac Eochaidh',
    'Keoghoe': 'Mac Eochaidh',
    'Mac Keohane': 'Ó Ceocháin',
    'Keohane': 'Ó Ceocháin',
    'MacKeo(w)n': 'Mac Eoghain (Tir Chonaill/Connachta)',
    'Mac Keon': 'Mac Eoin (Ulaidh)',
    'Mac Keoneen': 'Mac Sheoinín',
    'Keoneen': 'Mac Sheoinín',
    'O’Keoneen': 'Ó Ceoinín',
    'Keppock': 'de Ceapóg',
    'O’Kerane': 'Ó Ciaráin',
    'Kerans': 'Ó Ciaráin',
    'Kerbin': 'Ó Coirbín',
    'Kerby': 'Ó Ciarba',
    'Kerdiff': 'de Carduibh',
    'Kerdiffe': 'de Carduibh',
    'Kereen': 'Ó Céirín',
    'Mac Kerel': 'Mac Fhearail',
    'Kervan': 'Ó Cearbháin',
    'Kerevan': 'Ó Ciarubháin',
    'Kergan': 'Ó Ciaragáin',
    'Kerins': 'Ó Céirín',
    'Kerin': 'Ó Céirín',
    'Mac Kerley': 'Mac Thoirealaigh',
    'Kerley': 'Mac Thoirealaigh',
    'Kerlin': 'Ó Coirealláin',
    'Kermeen': 'Mac Eireamhóin',
    'Mac Kermode': 'Mac Dhiarmada',
    'Kermode': 'Mac Dhiarmada',
    'Kermody': 'Ó Cearmada',
    'O Kernaghan': 'Ó Cearnacháin',
    'Kernaghan': 'Ó Cearnacháin',
    'Mac Kernan': 'Mac Thiarnáin',
    'Kernan': 'Mac Thiarnáin',
    'Kerney': 'Ó Ceithearnaigh',
    'Mac Kerr': 'Mac Corra',
    'Kerr': 'Mac Giolla Cheara',
    'Kerragher': 'Mac Fhearchair',
    'Kerragy': 'Mac Concharraige',
    'O Kerrane': 'Ó Cearáin',
    'Kerrane': 'Ó Cearáin',
    'Mac Kerribly': 'Mac Geirble',
    'Kerribly': 'Mac Geirble',
    'Mac Kerrigan': 'Mac Ciaragáin',
    'O Kerrigan': 'Ó Ciaragáin',
    'Kerrigan': 'Ó Ciaragáin',
    'Kerrins': 'Ó Céirín',
    'Kerrin': 'Ó Céirín',
    'Mac Kerrisk': 'Mac Fhiarais',
    'Mac Kerris': 'Mac Fhiarais',
    'Kerrisk': 'Mac Fhiarais',
    'Kerris': 'Mac Fhiarais',
    'Kerrison': 'Mac Fhiarais',
    'Mac Kerrow': 'Mac Ciothrua',
    'Mac Kerry': 'Ó Maoilchéire',
    'Kervan': 'Ó Ciarubháin',
    'Mac Kervel': 'Mac Cearbhaill',
    'Mac Kervey': 'Mac Cearrbhaigh',
    'O Kerwick': 'Ó Ciarmhaic',
    'Kerwick': 'Ó Ciarmhaic',
    'Kerwin': 'Ó Ciarubháin',
    'Kessidy': 'Ó Caiside',
    'Mac Ketian': 'Mac Céitín',
    'O Kett': 'Ó Ceit',
    'Kett': 'Ó Ceit',
    'Kettle': 'Mac Coitil',
    'Mac Kettrick': 'Mac Shitric',
    'O Kevane': 'Ó Ciabháin',
    'Kevane': 'Ó Ciabháin',
    'Mac Kevany': 'Ó Géibheannaigh',
    'Kevany': 'Ó Géibheannaigh',
    'Keverney': 'Ó Coibheanaigh',
    'O Keville': 'Ó Cibhil',
    'Keville': 'Ó Cibhil',
    'Mac Kevin': 'Mac Dhuibhín',
    'Kevin': 'Mac Dhuibhín',
    'Kevin': 'Ó Caoimhín',
    'Mac Kevitt': 'Mac Dhaibhéid',
    'Kevlean': 'Ó Cibhlín',
    'Kevlihan': 'Ó Cibhleacháin',
    'Mac Kevor': 'Mac Íomhair',
    'Mac Kew': 'Mac Aodha',
    'Mac Kewen': 'Mac Eoghain',
    'Kewis': 'Mac Uais',
    'Kewley': 'Mac Amhalaí',
    'Mac Key': 'Mac Aoidh',
    'Keys': 'Mac Aoidh',
    'Keyse': 'Mac Aoidh',
    'Mac Kibbon': 'Mac Fhibín',
    'Mac Kibbon': 'Mac Giobúin',
    'O’Kibbon': 'Ó Ciobúin',
    'Kickham': 'Ciceam',
    'Kidney': 'Ó Duáin',
    'Mac Kie': 'Mac Aoidh',
    'O Kielty': 'Ó Caoilte',
    'O Kielt': 'Ó Caoilte',
    'Kielty': 'Ó Caoilte',
    'Kielt': 'Ó Caoilte',
    'O Kiely': 'Ó Cadhla',
    'Kiely': 'Ó Cadhla',
    'Mac Kieran': 'Mac Ciaráin',
    'Kierans': 'Ó Ciaráin',
    'Kieran': 'Ó Ciaráin',
    'Mac Kiernan': 'Mac Thiarnáin',
    'Kiernan': 'Mac Thiarnáin',
    'Kierse': 'Mac Fhiarais',
    'Kiervan': 'Ó Ciarubháin',
    'Mac Kiever': 'Mac Íomhair',
    'Kiggins': 'Mac Aogáin',
    'O Kihegan': 'Mac Eochagáin',
    'Kihegan': 'Mac Eochagáin',
    'Kilahy': 'Mac Giolla Achaidh',
    'Kilamartin': 'Mac Giolla Mhártain',
    'Mac Kilbane': 'Mac Giolla Bháin',
    'Kilbane': 'Mac Giolla Bháin',
    'Kilbeg': 'Mac Giolla Bhig',
    'Mac Kilbouy': 'Mac Giolla Bhuí',
    'Mac Kilboy': 'Mac Giolla Bhuí',
    'Kilboy': 'Mac Giolla Bhuí',
    'Mac Kilbride': 'Mac Giolla Bhríde',
    'Kilbride': 'Mac Giolla Bhríde',
    'Kilby': 'Mac Giolla Bhuí',
    'Kilcarr': 'Mac Giolla Chathair',
    'Kilcar': 'Mac Giolla Chathair',
    'Mac Kilcash': 'Mac Giolla Chais',
    'Kilcash': 'Mac Giolla Chais',
    'Kilchreist': 'Mac Giolla Chríost',
    'Mac Kilcline': 'Mac Giolla Chlaoin',
    'Kilcline': 'Mac Giolla Chlaoin',
    'Kilcommons': 'Mac Giolla Chomáin',
    'Mac Kilcooley': 'Mac Giolla Chúille',
    'Kilcooley': 'Mac Giolla Chúille',
    'Mac Kilcoyle': 'Mac Giolla Chomhaill',
    'Kilcoyle': 'Mac Giolla Chomhaill',
    'Mac Kilcoyne': 'Mac Giolla Chaoin',
    'Kilcoyne': 'Mac Giolla Chaoin',
    'Kilcrow': 'Mac Giolla Ghairbh',
    'Mac Kilcullen': 'Mac Giolla Chaillín',
    'Kilcullen': 'Mac Giolla Chaillín',
    'Mac Kildea': 'Mac Giolla Dé',
    'Kildea': 'Mac Giolla Dé',
    'Mac Kilderry': 'Mac Giolla Dorcha',
    'Mac Kildar': 'Mac Giolla Dorcha',
    'Mac Kilduff': 'Mac Giolla Dhuibh',
    'Kilduff': 'Mac Giolla Dhuibh',
    'Mac Kildunn': 'Mac Giolla Dhoinn',
    'Kildunn': 'Mac Giolla Dhoinn',
    'Kilfedder': 'Mac Giolla Pheadair',
    'Kilfillian': 'Mac Giolla Fhaoláin',
    'Mac Kilgallen': 'Mac Giolla Chaillín',
    'Kilgallen': 'Mac Giolla Chaillín',
    'Mac Kilgnannon': 'Mac Giolla Ghannáin',
    'Kilgnannon': 'Mac Giolla Ghannáin',
    'Kilgar': 'Mac Giolla Ghearr',
    'Mac Kilgarriff': 'Mac Giolla Ghairbh',
    'Kilgarriff': 'Mac Giolla Ghairbh',
    'Mac Kilgray': 'Mac Giolla Riabhaigh',
    'Kilgray': 'Mac Giolla Riabhaigh',
    'Kilgrew': 'Mac Giolla Ghairbh',
    'Kilgrist': 'Mac Giolla Chríost',
    'Kilgunn': 'Mac Giolla Dhoinn',
    'Mac Kilheny': 'Mac Giolla Chainnigh',
    'Mac Kilkelly': 'Mac Giolla Cheallaigh',
    'Kilkelly': 'Mac Giolla Cheallaigh',
    'Mac Kilkenny': 'Mac Giolla Chainnigh',
    'Kilkenny': 'Mac Giolla Chainnigh',
    'Mac Kilkeary': 'Mac Giolla Chéire',
    'Kilkeary': 'Mac Giolla Chéire',
    'Mac Kilker': 'Mac Giolla Ghéir',
    'Kilker': 'Mac Giolla Ghéir',
    'Kilkey': 'Mac Giolla Chaoich',
    'Kilkison': 'Mac Uilcín',
    'Mac Killacky': 'Mac Giolla Aiche',
    'Killacky': 'Mac Giolla Aiche',
    'Killane': 'Ó Cilleáin',
    'Killan': 'Ó Cilleáin',
    'O Killian': 'Ó Cillín',
    'O Killeen': 'Ó Cillín',
    'Killian': 'Ó Cillín',
    'Killeen': 'Ó Cillín',
    'Mac Killen': 'Mac Coilín (Albanach)',
    'Killen': 'Mac Coilín (Albanach)',
    'Killemeade': 'Mac Uilliméid',
    'Mac Killeran': 'Mac Giollaráin',
    'Killeran': 'Mac Giollaráin',
    'Killerlean': 'Mac Fhirléinn',
    'Killery': 'Mac Giolla Riabhaigh',
    'Killevy': 'Mac Dhoinnléibhe',
    'Mac Killgallen': 'Mac Giolla Chaillín',
    'Killgallen': 'Mac Giolla Chaillín',
    'Mac Killgore': 'Mac Giolla Ghearr',
    'Killgore': 'Mac Giolla Ghearr',
    'Mac Killian': 'Mac Coilín',
    'Killiard': 'Mac Giolla Ghearr',
    'Killiger': 'a Cligeoir',
    'Mac Killilea': 'Mac Giolla Léith',
    'Killilea': 'Mac Giolla Léith',
    'Killimith': 'Mac Uilliméid',
    'Killips': 'Mac Fhilib',
    'Killooley': 'Mac Giolla Ghuala',
    'Mac Killop': 'Mac Philib (Albanach)',
    'Mac Killops': 'Mac Fhilib',
    'Mac Killop': 'Mac Fhilib',
    'Killops': 'Mac Fhilib',
    'Killop': 'Mac Fhilib',
    'Mac Killoran': 'Mac Giolla Luairinn',
    'Killoran': 'Mac Giolla Luairinn',
    'Mac Killoughry': 'Mac Giolla Luachaire',
    'Killoughry': 'Mac Giolla Luachaire',
    'Kilmaine': 'Mac Sheoinín',
    'Kilmartin': 'Mac Giolla Mhártain',
    'Kilmary': 'Mac Giolla Mhuire',
    'Kilmet': 'Mac Uilliméid',
    'Kilmore': 'Mac Giolla Mhuire',
    'Mac Kilmurray': 'Mac Giolla Mhuire',
    'Mac Kilmurry': 'Mac Giolla Mhuire',
    'Kilmurray': 'Mac Giolla Mhuire',
    'Kilmurry': 'Mac Giolla Mhuire',
    'Mac Kilpatrick': 'Mac Giolla Phádraig',
    'Kilpatrick': 'Mac Giolla Phádraig',
    'Mac Kilrain': 'Mac Giollaráin',
    'Kilrain': 'Mac Giollaráin',
    'Mac Kilrea': 'Mac Giolla Riabhaigh',
    'Kilrea': 'Mac Giolla Riabhaigh',
    'Mac Kilroe': 'Mac Giolla Rua',
    'Kilroe': 'Mac Giolla Rua',
    'Kilronan': 'Mac Giolla Rónáin',
    'Kilty': 'Ó Caoilte',
    'Mac Kilvant': 'Mac Giolla Mhantaigh',
    'Kilvant': 'Mac Giolla Mhantaigh',
    'Mac Kilveen': 'Mac Giolla Mhín',
    'Kilveen': 'Mac Giolla Mhín',
    'Mac Kilvie': 'Mac Giolla Bhuí',
    'Mac Kilwaine': 'Mac Giolla Bháin',
    'Mac Kilwee': 'Mac Giolla Bhuí',
    'Mac Kim': 'Mac Shim',
    'Mac Kimmie': 'Mac Shimí',
    'Kimmins': 'Mac Coimín',
    'Mac Kimmon': 'Mac Coimín',
    'Mac Kimmins': 'Mac Coimín',
    'Kimmon': 'Mac Coimín',
    'Kimmins': 'Mac Coimín',
    'Mac Kimmon': 'Mac Shíomóin',
    'Kinagan': 'Ó Coinneagáin',
    'O Kinahan': 'Ó Coinneacháin',
    'Kinahan': 'Ó Coinneacháin',
    'Kinane': 'Ó Coinneáin',
    'Kinarney': 'Mac an Airchinnigh',
    'Mac Kinaul': 'Mac Conuladh',
    'Kinavan': 'O Ceannubháin',
    'Kincaid': 'Cinnicéid',
    'Kincart': 'Mac an Cheairt',
    'Mac Kinch': 'Mac Aonais',
    'Kinch': 'Mac Aonais',
    'Kinchela': 'Cinsealach',
    'O Kindelan': 'Ó Caoinnealáin',
    'Kindelan': 'Ó Caoinnealáin',
    'Kindregan': 'Ó Cindeargáin',
    'Kine': 'Ó Cadhain',
    'Kineavy': 'Mac Connámha',
    'Mac Kinerkin': 'Mac an Airchinn',
    'Mac Kinnerk': 'Mac an Airchinn',
    'Mac Kinerkin': 'Mac an Airchinn',
    'Mac Kinerking': 'Mac an Airchinn',
    'Kinerney': 'Mac an Airchinnigh',
    'Mac Kinestry': 'Mac an Aistrigh',
    'King': 'Ó Cionga',
    'Mac King': 'Mac Fhinn',
    'Kingarty': 'Mac Fhinneachta',
    'Kinghan': 'Ó Coinneáin',
    'Kingsley': 'Cinsealach',
    'Kingstone': 'Mac Clochaire',
    'Kingston': 'Mac Clochaire',
    'Mac Kiniff': 'Mac Connuibh',
    'Kinighan': 'Ó Coinneacháin',
    'Kiniry': 'Mac Innéirí',
    'Kinkead': 'Cinnicéid',
    'Kinlan': 'Ó Caoinleáin',
    'Mac Kinlay': 'Mac Fhionnlaoich',
    'Mac Kinley': 'Mac Fhionnlaoich',
    'Kinlough': 'Mac Conlocha',
    'Mac Kinn': 'Mac Fhinn',
    'Kinnan': 'Ó Cianáin',
    'Mac Kinnan': 'Mac Fhionnáin',
    'Kinnane': 'Ó Coinneáin',
    'Mac Kinnarney': 'Mac an Airchinnigh',
    'Kinnarney': 'Mac an Airchinnigh',
    'Mac Kinnaul': 'Mac Conuladh',
    'Kinnavane': 'Ó Ceannubháin',
    'Mac Kinnavy': 'Mac Connámha',
    'Mac Kinnawe': 'Mac Connámha',
    'O Kinnelaly': 'Ó Cinnaolaidh',
    'Kinnelaly': 'Ó Cinnaolaidh',
    'Kinnear': 'Mac an Fhir',
    'Kinneen': 'Mac Coinín',
    'Kinnegan': 'Ó Coinneagáin',
    'Kinnerk': 'Mac an Airchinnigh',
    'Kinnevane': 'Ó Ceannubháin',
    'Mac Kinney': 'Mac Coinnigh',
    'Kinnian': 'Ó Coinín',
    'Kinnier': 'Mac an Fhir',
    'Kinningham': 'Ó Coinneagáin',
    'Kinnirey': 'Mac Innéirí',
    'Kinnock': 'Ó Cuineog',
    'Kinnole': 'Ó Coineoil',
    'Kinnure': 'Mac Fhionnbhairr',
    'Kinoulty': 'Mac an Ultaigh',
    'Kinregan': 'Ó Cinideargáin',
    'Kinrock': 'Mac Eanraic',
    'Kinsella': 'Cinsealach',
    'Mac Kinstry': 'Mac an Aistrigh',
    'Mac Kintosh': 'Mac an Taoisigh',
    'Mac Kinty': 'Mac an tSaoi',
    'Mac Kinucane': 'Mac Fhionnmhacáin',
    'Kinucane': 'Mac Fhionnmhacáin',
    'Kinure': 'Mac Fhionnbhairr',
    'O Kirby': 'Ó Ciarba',
    'Kirby': 'Ó Ciarba',
    'Kirby': 'Mac Geirble (Maigh Eo)', 
    'MacKirdy': 'Mac Mhuireartaigh',
    'Kirivan': 'Ó Ciarubháin',
    'Kirk': 'Mac Giolla Chirce (Thuaidh)',
    'Kirke': 'Ó Coirc (Theas)',
    'Kirk': 'Ó Coirc (Theas)',
    'Kirkpatrick': 'Mac Giolla Phádraig',
    'Kirland': 'Ó Coirealláin',
    'Kirley': 'Mac Thoirealaigh',
    'Kirlin': 'Ó Coirealláin',
    'Kiroy': 'Ó Ciothrua',
    'O Kirrane': 'Ó Cearáin',
    'Kirrane': 'Ó Cearáin',
    'Kirrell': 'Ó Coirill',
    'O Kirwan': 'Ó Ciarubháin',
    'O Kirvan': 'Ó Ciarubháin',
    'Kirwan': 'Ó Ciarubháin',
    'Kirvan': 'Ó Ciarubháin',
    'Kissack': 'Cíosóg',
    'Kissane': 'Ó Cíosáin',
    'Mac Kissock': 'Mac Íosóg',
    'Kitchen': 'Mac Úistín',
    'Kitson': 'Ó Ceit',
    'Mac Kitterick': 'Mac Shitric',
    'Kitterick': 'Mac Shitric',
    'Kivane': 'Ó Ciabháin',
    'Kiville': 'Ó Cibhil',
    'O Kivlehan': 'Ó Cibhleacháin',
    'Kivlehan': 'Ó Cibhleacháin',
    'Mac Klern': 'Mac Giolla Chiaráin',
    'Klisham': 'Cliseam',
    'Klisham': 'Mac Cliseam',
    'Klyne': 'Mac Giolla Chlaoin',
    'Mac Knally': 'Mac an Fhailigh',
    'Knally': 'Mac an Fhailigh',
    'Knavin': 'Mac Cnáimhín',
    'O Kneafsey': 'Ó Cnáimhsí',
    'Kneafsey': 'Ó Cnáimhsí',
    'Kneale': 'Mac Néill',
    'Knee': 'Ó Nia',
    'Kneeland': 'Ó Nialláin',
    'Kneen': 'Mac Cianáin',
    'Mac Kniff': 'Mac Connuibh',
    'Knight': 'Mac an Ridire',
    'Mac Knight': 'Mac Neachtain (Albanach)',
    'Knight': 'Mac Neachtain (Albanach)',
    'Kniland': 'O Nialláin',
    'Knockton': 'Ó Neachtain',
    'Knowd': 'Ó Nuad',
    'Knowell': 'O Tnúthail',
    'Knowles': 'O Tnúthail',
    'Knowland': 'O Nualláin',
    'Knox': 'de Cnoc',
    'Mac Knulty': 'Mac an Ultaigh',
    'Koen': 'Ó Comhain',
    'Mac Koen': 'Mac Eoghain',
    'Mac Konkey': 'Mac Dhonnchaidh',
    'Mac Konnigham': 'Mac Coinneagáin',
    'Korish': 'Mac Fheorais',
    'Mac Kough': 'Mac Eochaidh',
    'Mac Koy': 'Mac Aodha',
    'Mac Krann': 'Mac Bhrain',
    'Mac Kreel': 'Mac Fhearail',
    'Kulkeen': 'Mac Uilcín',
    'Mac Kurdy': 'Mac Mhuireartaigh',
    'Kurdy': 'Mac Mhuireartaigh',
    'Mac Kusker': 'Mac Oscair',
    'Mac Kussack': 'Mac Íosóg',
    'O Kyan': 'Ó Catháin',
    'Kyan': 'Ó Catháin',
    'Kyle': 'Mac Shile',
    'Kyley': 'Ó Cadhla',
    'O Kyne': 'Ó Cadhain',
    'Kyne': 'Ó Cadhain'
}