module.exports = {
    'de Lacy': 'de Léis',
    'de Lacey': 'de Léis',
    'Lacy': 'de Léis',
    'Lacey': 'de Léis',
    'Mac Lachlan': 'Mac Lachlainn',
    'Lachlin': 'Ó Lachlainn',
    'Lacken': 'Ó Lacháin',
    'Lacy': 'Ó Laitheasa',
    'Lade': 'Mag Léid',
    'Laide': 'Mag Léid',
    'Ladden': 'Ó Laideáin',
    'Ladrigan': 'Ó Longargáin',
    'Laffan': 'Lafán',
    'Mac Lafferty': 'Mac Laifeartaigh',
    'O Lafferty': 'Ó Laifeartaigh',
    'Lafferty': 'Ó Laifeartaigh',
    'O Laffey': 'Ó Laithimh',
    'Laffey': 'Ó Laithimh',
    'Lagan': 'Ó Leogáin',
    'Laghlin': 'Ó Lachlainn',
    'Lahan': 'Ó Lacháin',
    'O Laheen': 'O Laithín',
    'Laheen': 'O Laithín',
    'Laherty': 'Mac Laibheartaigh',
    'Lahert': 'Mac Laibheartaigh',
    'O Lahey': 'Ó Laithimh',
    'Lahey': 'Ó Laithimh',
    'Lahiff': 'Ó Laithimh',
    'Lahive': 'Ó Laithimh',
    'Mac Lain': 'Mac Giolla Eáin',
    'Laine': 'Ó Leatháin',
    'Laing': 'Ó Lainn',
    'Laird': 'Ó Tiarnaigh',
    'Lally': 'Ó Maolalaidh',
    'Lalor': 'Ó Leathlobhair',
    'Laman': 'Mac Laghmainn',
    'Lambe': 'Ó Luain',
    'Lambert': 'Laimbeart',
    'Lambie': 'Mac Laghmainn',
    'Lammie': 'Mac Laghmainn',
    'Lambin': 'Laimbín',
    'Mac Lamont': 'Mac Laghmainn',
    'Mac Lamond': 'Mac Laghmainn',
    'Lamport': 'Laimbeart',
    'Lambert': 'Laimbeart',
    'Landers': 'de Londras',
    'Landers': 'Mac Giolla Aindréis',
    'Landon': 'de Londún',
    'Landrey': 'de Londra',
    'O Landrigan': 'Ó Longargáin',
    'Landrigan': 'Ó Longargáin',
    'Mac Landrish': 'Mac Giolla Aindréis',
    'Landy': 'Leaindí',
    'Mac Lane': 'Mac Giolla Eáin',
    'Lane': 'Ó Laighin',
    'Laney': 'Ó Dúláinne',
    'Lang': 'Ó Lainn',
    'O Langan': 'Ó Langáin',
    'Langan': 'Ó Langáin',
    'Langford': 'Langfort',
    'Langin': 'Ó Longáin',
    'Langton': 'Langtún',
    'O Lanigan': 'Ó Lonagáin',
    'Lanigan': 'Ó Lonagáin',
    'O Lannon': 'Ó Leannáin',
    'Lannon': 'Ó Leannáin',
    'Lant': 'Lant',
    'Laphin': 'Lafáin',
    'O Lappin': 'Ó Lapáin',
    'Lappin': 'Ó Lapáin',
    'Laracy': 'Ó Learasa',
    'Lardner': 'Ó Lorgnain',
    'Mac Larty': 'Mac Laitheartaigh',
    'Mac Lardy': 'Mac Laitheartaigh',
    'Mac Laren': 'Mac Labhrainn',
    'Mac Larenon': 'Mac Giolla Earnáin',
    'Larens': 'Labhrás',
    'O Largan': 'Ó Lairgneáin',
    'Largan': 'Ó Lairgneáin',
    'Large': 'Ó Duílearga',
    'Largey': 'Ó Duílearga',
    'O Larkin': 'Ó Lorcáin',
    'Larkin': 'Ó Lorcáin',
    'Larney': 'Ó Maoilearna',
    'Mac Larnon': 'Mac Giolla Earnáin',
    'O Larrissey': 'Ó Learasa',
    'Larrissey': 'Ó Learasa',
    'Mac Larry': 'Mac Giolla Arraith',
    'O Losty': 'Ó Loiste',
    'O Lasty': 'Ó Loiste',
    'Losty': 'Ó Loiste',
    'Lasty': 'Ó Loiste',
    'Latten': 'Laitín',
    'Lauder': 'Láidir',
    'O Laugheran': 'Ó Luachráin',
    'Laugheran': 'Ó Luachráin',
    'Laughland': 'Mac Lachláin',
    'Mac Laughlin': 'Mac Lochlainn',
    'O Laughnane': 'Ó Lachtnáin',
    'O Laughnan': 'Ó Lachtnáin',
    'Laughnane': 'Ó Lachtnáin',
    'Laughnan': 'Ó Lachtnáin',
    'Launders': 'de Londras',
    'Mac Lauren': 'Mac Labhrainn',
    'Laurence': 'Labhrás',
    'Laurison': 'Mac Labhráis',
    'Lavallin': 'Labhailin',
    'O Lavan': 'Ó Laimhín',
    'Lavan': 'Ó Laimhín',
    'Mac Lave': 'Mac Laithimh',
    'Lavelle': 'Ó Maolábhail',
    'Mac Laverty': 'Mac Laibheartaigh',
    'O Laverty': 'Ó Laibheartaigh',
    'Laverty': 'Ó Laibheartaigh',
    'Mac Lavery': 'Mac Labhraí',
    'O Lavery': 'Ó Labhraí',
    'Lavery': 'Ó Labhraí',
    'Mac Lavin': 'Ó Maoiléimhín',
    'Mac Lavins': 'Mac Dhoinnléibhín',
    'Mac Lavin': 'Mac Dhoinnléibhín',
    'Law': 'de Lá',
    'Lawdet': 'Láidir',
    'Lawell': 'Ó Maolábhail',
    'Lawlee': 'Lálaí',
    'Lawler': 'Ó Leathlobhair',
    'Lawless': 'Laighléis',
    'Lawn': 'Ó Liatháin',
    'Lawrenson': 'Mac Labhráis',
    'Lawson': 'Mac Labhráin',
    'Lawton': 'Ó Lachtnáin',
    'Layne': 'Ó Laighin',
    'Layng': 'Ó Lainn',
    'Lea': 'Ó Laoi',
    'Mac Lea': 'Mac an Lia',
    'Leacy': 'Ó Laitheasa',
    'Leader': 'Léadar',
    'League': 'Ó Laoghóg',
    'O Leahy': 'Ó Laocha',
    'Leahy': 'Ó Laocha',
    'O Leamy': 'Ó Léime',
    'Leamy': 'Ó Léime',
    'Mac Lean': 'Mac Giolla Eáin',
    'O Lean': 'Ó Liain',
    'Lean': 'Ó Liain',
    'O Leane': 'Ó Laighin',
    'Leane': 'Ó Laighin',
    'O Leany': 'Ó Laighnigh',
    'Leany': 'Ó Laighnigh',
    'Mac Lear': 'Mac Giolla Uír',
    'Learhinan': 'Ó Loirgneáin',
    'Mac Leary': 'Mac Giolla Arraith',
    'O Leary': 'Ó Laoire',
    'Leary': 'Ó Laoire',
    'Mac Leavy': 'Mac Dhoinnéibhe',
    'Leavy': 'Mac Dhoinnéibhe',
    'Mac Leavy': 'Mac Conléibhe',
    'Leavy': 'Mac Conléibhe',
    'Leckie': 'Mac an Chléirigh',
    'Leckie': 'Mac an Chléirigh',
    'Leddan': 'Ó Loideáin',
    'Leddy': 'Ó Lidí',
    'Ledger': 'de Sailigéir',
    'Ledwich': 'Léadús',
    'Mac Lee': 'Mac an Lia',
    'Lee': 'Mac an Lia',
    'O Lee': 'Ó Laoi',
    'Lee': 'Ó Laoi',
    'Leeane': 'Ó Liatháin',
    'Leech': 'Lia',
    'Leehane': 'Ó Liatháin',
    'Leehan': 'Ó Liatháin',
    'Leehy': 'Ó Laocha',
    'Leeman': 'Mac Laghmainn',
    'Leen': 'Ó Laighin',
    'Leyne': 'Ó Laighin',
    'Leeney': 'Ó Laighnigh',
    'Leeogue': 'Ó Laoghóg',
    'O’Leery': 'Ó Laoire',
    'Lees': 'Mac an Lia',
    'Mac Lees': 'Mac Giolla Íosa',
    'Leeson': 'Ó Gliasáin',
    'Leevy': 'Mac Dhoinnléibhe',
    'Legge': 'Mac Coise',
    'O Lehane': 'Ó Liatháin',
    'Lehane': 'Ó Liatháin',
    'Mac Lehenny': 'Mac Giolla Chainnigh',
    'Mac Leheron': 'Mac Giolla Chiaráin',
    'Leicester': 'de Leastar',
    'Leigh': 'Mac an Lia',
    'Mac Leise': 'Mac Giolla Íosa',
    'Leishman': 'Mac Giolla Íosa',
    'Mac Leister': 'Mac Alastair',
    'Leitch': 'Mac Giolla Íosa',
    'Mac Leland': 'Mac Giolla Fhaoláin',
    'Mac Lellan': 'Mac Giolla Fhaoláin',
    'O Lemasney': 'Ó Lomasna',
    'Lemasney': 'Ó Lomasna',
    'Lemass': 'Lemass',
    'Mac Lement': 'Mac Laghmainn',
    'Lemmon': 'Mac Laghmainn',
    'Lemondson': 'Mac Laghmainn',
    'Lenagan': 'O Loineagáin',
    'Mac Lenaghan': 'Mac Leannacháin',
    'Lenard': 'Ó Linneáin',
    'Lenden': 'Ó Leandáin',
    'Lenigan': 'Ó Loineagáin',
    'O Lenihan': 'Ó Loingeacháin',
    'Lenihan': 'Ó Loingeacháin',
    'O Lenihan': 'Ó Leannacháin',
    'Lenihan': 'Ó Leannacháin',
    'Lennane': 'Ó Linneáin',
    'Lenane': 'Ó Linneáin',
    'O Lennane': 'Ó Linneáin',
    'O Lenane': 'Ó Linneáin',
    'Mac Lennan': 'Mac Giolla Fhinnéin',
    'Mac Lennon': 'Mac Leannáin',
    'Lennon': 'Ó Leannáin',
    'Lennox': 'Mac Caisealáin',
    'Lenton': 'Mac Giolla Fhionntáin',
    'Leo': 'de Liath',
    'Mac Leod': 'Mac Leoid',
    'Leogue': 'Ó Laoghóg',
    'Leonard': 'Mac Giolla Fhinnéin',
    'Leonard': 'Ó Loinín',
    'O Lerkinan': 'Ó Loirgneáin',
    'O Lerihan': 'Ó Loirgneáin',
    'Lerkinan': 'Ó Loirgneáin',
    'Lerihan': 'Ó Loirgneáin',
    'Mac Lerney': 'Mac Giolla Earna',
    'O Lernihan': 'Ó Loirgneáin',
    'Lernihan': 'Ó Loirgneáin',
    'Mac Lernon': 'Mac Giolla Earnáin',
    'Mac Leroy': 'Mac Giolla Rua',
    'Leslie': 'Leaslaoi',
    'Mac Lester': 'Mac Alastair',
    'Lester': 'Mac Alastair',
    'Lestrange': 'Mac Conchoigrí',
    'Letters': 'Mac Conleitreach',
    'Letter': 'Mac Conleitreach',
    'Levens': 'Mac Dhoinnléibhín',
    'Levett': 'Luibhéid',
    'Leviston': 'Mac Dhoinnléibhín',
    'Levinge': 'Mac Dhoinnléibhín',
    'Levis': 'Mac Dhoinnléibhe',
    'Mac Levy': 'Mac Dhoinnléibhe',
    'Levy': 'Mac Dhoinnléibhe',
    'Lewis': 'Lobhaois',
    'Leycester': 'de Leastar',
    'O Leyden': 'Ó Loideáin',
    'Leyden': 'Ó Loideáin',
    'Leyhane': 'Ó Liatháin',
    'Leynagh': 'Laighneach',
    'Leyne': 'Ó Laighin',
    'Mac Wilmore': 'Mac Liammóir',
    'Mac Liammoir': 'Mac Liammóir',
    'Mac Lice': 'Mac Giolla Íosa',
    'O Liddane': 'Ó Loideáin',
    'Liddane': 'Ó Loideáin',
    'O Liddy': 'Ó Lidí',
    'Liddy': 'Ó Lidí',
    'Lidwich': 'Léadús',
    'Lihane': 'Ó Liatháin',
    'Mac Lilley': 'Mac Ailile',
    'Lilley': 'Mac Ailile',
    'Lillis': 'Laighléis',
    'Liman': 'Mac Laghmainn',
    'Limerick': 'Ó Luimbric',
    'Linagh': 'Laighneach',
    'O Linchy': 'Ó Loingsigh',
    'Linchy': 'Ó Loingsigh',
    'Lincolm': 'de Lioncól',
    'Lind': 'Ó Loinn',
    'Linden': 'Mac Giolla Fhiondáin',
    'Lindon': 'Ó Leandáin',
    'Lindsay': 'Mac Giolla Iontóg',
    'Lindsay': 'Ó Loingsigh',
    'O Linehan': 'Ó Léanacháin',
    'Linehan': 'Ó Léanacháin',
    'Lines': 'Ó Loighin',
    'Lingane': 'Ó Linneáin',
    'Lingard': 'Líongard',
    'Linn': 'Ó Loinn',
    'O Linnane': 'Ó Linneáin',
    'Linnane': 'Ó Linneáin',
    'O Linneen': 'Ó Loinín',
    'Linneen': 'Ó Loinín',
    'O Linnegar': 'O Loinín',
    'Linnegar': 'O Loinín',
    'Linnex': 'Leamhnach',
    'O Linskey': 'Ó Loinscigh',
    'Linskey': 'Ó Loinscigh',
    'Mac Lintock': 'Mac Giolla Iontóg',
    'Lindon': 'Mac Giolla Fhionntáin',
    'Linton': 'Mac Giolla Fhionntáin',
    'Lions': 'Ó Laighin',
    'Lion': 'Ó Laighin',
    'Mac Lister': 'Mac an Leastair', 
    'Mac Alastair': 'Mac an Leastair', 
    'Lister, Mac Alastair': 'Mac an Leastair', 
    'Liston': 'Liostún',
    'Little': 'Ó Beig',
    'Little': 'Ó Beacháin',
    'Little': 'Ó Beagáin',
    'Littleton': 'Ó Beagáin',
    'Livingstone': 'Mac Dhoinnléibhín',
    'Livott': 'Liobhóid',
    'Lloyd': 'Lóid',
    'Loag': 'Ó Laoghóg',
    'O Loane': 'Ó Luain',
    'O Loan': 'Ó Luain',
    'Loane': 'Ó Luain',
    'Loan': 'Ó Luain',
    'Lochlin': 'Ó Lochlainn',
    'Mac Lochlin': 'Mac Lochlainn',
    'O Lochrane': 'Ó Luachráin',
    'Lochrane': 'Ó Luachráin',
    'Lockard': 'Locard',
    'Lockery': 'Ó Luathéirí',
    'Lofte': 'de Lochtús',
    'Loftus': 'Ó Lachtnáin',
    'Loftis': 'Ó Lachtnáin',
    'Logan': 'Ó Leocháin',
    'Loghan': 'Ó Leocháin',
    'O Loghlen': 'Ó Lochlainn',
    'Loghlen': 'Ó Lochlainn',
    'O Logue': 'Ó Laoghóg',
    'Logue': 'Ó Laoghóg',
    'Lohan': 'Ó Leocháin',
    'Lomand': 'Mac Laghmainn',
    'Loman': 'Mac Laghmainn',
    'O Lomasney': 'Ó Lomasna',
    'Lomasney': 'Ó Lomasna',
    'Lombard': 'Lombard',
    'London': 'de Londras',
    'O Lonergan': 'Ó Longargáin',
    'Lonergan': 'Ó Longargáin',
    'O Loney': 'Ó Luinigh',
    'Loney': 'Ó Luinigh',
    'Long': 'Ó Longáin',
    'O Longan': 'Ó Longáin',
    'Longan': 'Ó Longáin',
    'Lonican': 'Ó Loingeacháin',
    'O Looby': 'Ó Lubaigh',
    'Looby': 'Ó Lubaigh',
    'O Loonane': 'Ó Luanáin',
    'Loonane': 'Ó Luanáin',
    'Mac Loone': 'Mac Giolla Eoin',
    'Mac Looney': 'Mac Cluanaigh',
    'O Looney': 'Ó Luanaigh',
    'Looney': 'Ó Luanaigh',
    'O Loran': 'Ó Labhráin',
    'Loran': 'Ó Labhráin',
    'Lord': 'Ó Tiarnaigh',
    'O Lordan': 'Ó Lordáin',
    'Lordan': 'Ó Lordáin',
    'Mac Lorinan': 'Mac Giolla Earnáin',
    'O Lorkan': 'Ó Lorcáin',
    'Lorkan': 'Ó Lorcáin',
    'O Lorrigan': 'Ó Longargáin',
    'Lorrigan': 'Ó Longargáin',
    'Mac Loskey': 'Mac Bhloscaidh',
    'O Losty': 'Ó Loiste',
    'Losty': 'Ó Loiste',
    'Loudan': 'Mac Cailín',
    'Lough': 'Mac Conlocha',
    'O Loughan': 'Ó Leocháin',
    'Loughan': 'Ó Leocháin',
    'Lougheed': 'Ceann an Locha',
    'Mac Loughlin': 'Mac Lochlainn',
    'Loughlin': 'Mac Lochlainn',
    'O Loughlin': 'Ó Lochlain',
    'Loughlin': 'Ó Lochlain',
    ')': 'Ó Lachtnáinoughnane': 'Ó Lachtnáin',
    ')': 'Ó Lachtnáinoughnan': 'Ó Lachtnáin',
    'Mac Loughney': 'Mac Lachtna',
    'O Loughney': 'Ó Lachtna',
    'Loughney': 'Ó Lachtna',
    'O Loughney': 'Ó Maolachtna',
    'Loughney': 'Ó Maolachtna',
    'O Loughran': 'Ó Luachráin',
    'Loughran': 'Ó Luachráin',
    'Mac Loughrey': 'Mac Conluachra',
    'O Loughrey': 'Ó Luachra',
    'Loughrey': 'Ó Luachra',
    'Mac Louis': 'Mac Lúaidh',
    'Lovat': 'Luibhéid',
    'Love': 'Mac Craith',
    'Love': 'Ó Gadhra',
    'Lovell': 'Luibhéil',
    'Lovett': 'Mac Lomhaid',
    'O Lowan': 'Ó Luain',
    'Lowan': 'Ó Luain',
    'Lowe': 'Mac Lú',
    'Lowney': 'na Leamhna',
    'Lowrison': 'Mac Labhraí',
    'Mac Lowry': 'Mac Labhraí',
    'Lowry': 'Mac Labhraí',
    'Lowry': 'Ó Labhraí',
    'Loy': 'Mac Luaidh',
    'O Luby': 'Ó Lúbaigh',
    'Luby': 'Ó Lúbaigh',
    'Mac Lucas': 'Mac Lúcáis',
    'Lucas': 'Mac Lúcáis',
    'Lucet': 'Lúiséid',
    'O Lucey': 'Ó Luasaigh',
    'Lucey': 'Ó Luasaigh',
    'Lucid': 'Ó Luasaigh',
    'O Ludden': 'Ó Loideáin',
    'Ludden': 'Ó Loideáin',
    'O Luddy': 'Ó Loidigh',
    'Luddy': 'Ó Loidigh',
    'Ludwig': 'Léadús',
    'Mac Lugash': 'Mac Lúcáis',
    'Lukas': 'Mac Lúcáis',
    'Lucas': 'Mac Lúcáis',
    'Luke': 'Mac Lúcáis',
    'Lumbard': 'Lombard',
    'Lumley': 'Ó Lomaile',
    'Lundergan': 'Ó Longargáin',
    'Lundon': 'de Londrais',
    'Lundy': 'Mac Giolla Fhiondáin',
    'Mac Lune': 'Mac Giola Eoin',
    'O Luneen': 'Ó Loinín',
    'Luneen': 'Ó Loinín',
    'Mac Luney': 'Mac Giolla Domhnaigh',
    'Mac Lung': 'Mac Loinge',
    'O Lunney': 'Ó Luinigh',
    'Lunney': 'Ó Luinigh',
    'O Lunney': 'Ó Loinín',
    'Lunney': 'Ó Loinín',
    'Lupane': 'Ó Lapáin',
    'Mac Lure': 'Mac Giollaír',
    'Mac Lurg': 'Mac Loirg',
    'O Lurigan': 'Ó Longargáin',
    'Lurigan': 'Ó Longargáin',
    'Mac Luskey': 'Mc Bhloscaidh',
    'Lusty': 'Ó Loiste',
    'Luttrell': 'Lotrail',
    'O Lydon': 'Ó Loideáin',
    'Lydon': 'Ó Loideáin',
    'O Lyhane': 'Ó Liatháin',
    'Lyhane': 'Ó Liatháin',
    'Lyhane': 'Ó Liatháin',
    'Lyhan': 'Ó Liatháin',
    'Lyle': 'Ó Laoill',
    'Lynagh': 'Laighneach',
    'O Lynam': 'Ó Laigheanáin',
    'Lynam': 'Ó Laigheanáin',
    'Lynas': 'Mac Giolla Fhionnáin',
    'O Lynch': 'Ó Liongsigh',
    'Lynch': 'Ó Liongsigh',
    'Mac Lynchehan': 'Mac Loingseacháin',
    'Lynchehan': 'Mac Loingseacháin',
    'O Lynchehan': 'Ó Loingseacháin',
    'Lynchehan': 'Ó Loingseacháin',
    'Mac Lynchy': 'Mac Loingsigh',
    'O Lynchy': 'Ó Loingsigh',
    'Lynchy': 'Ó Loingsigh',
    'O Lyne': 'Ó Laighin',
    'Lyne': 'Ó Laighin',
    'Lynegan': 'Ó Loineagáin',
    'Lynegar': 'Ó Loinín',
    'Lyness': 'Mac Giolla Fhinnéin',
    'Lyng': 'Ó Loinn',
    'Mac Lynn': 'Mac Loinn',
    'O Lynn': 'Ó Loinn',
    'Lynn': 'Ó Loinn',
    'Lynott': 'Lionóid',
    'O Lynskey': 'Ó Loinscigh',
    'Lynskey': 'Ó Loinscigh',
    'Lynton': 'de Liontún',
    'Lyons': 'Ó Laighin',
    'Lyons': 'Ó Liatháin',
    'Mac Lysaght': 'Mac Giolla Iasachta',
    'Lysaght': 'Mac Giolla Iasachta',
    'Lyster': 'Leastar',
    'Lyttle': 'Ó Beig',
    'Lyttle': 'Ó Beagáin',
    'Lyvet': 'Liobhóid'
}