module.exports = {
    'Mac Magh': 'Mac Matha',
    'Mac Ma': 'Mac Matha',
    'Mabe': 'Máb',
    'Mack': 'Mac Conmara',
    'Mackel': 'Mac an Ghoill',
    'Macklebreed': 'Mac Giolla Bhríde',
    'Macken': 'Ó Maicín',
    'Mackrell': 'Mac Fhearail',
    'Mackerel': 'Mac Fhearail',
    'Mackey': 'Ó Maca',
    'Mac Mackin': 'Mac Maicín',
    'Mackin': 'Ó Maicin',
    'Macklehatton': 'Mac Giolla Chatáin',
    'Mackessy': 'Ó Macasa',
    'O Mackle': 'Ó Machail',
    'Mackle': 'Ó Machail',
    'Macklemoyle': 'Mac Giolla Mhaoil',
    'Macklewaine': 'Mac Giolla Bháin',
    'Macnair': 'Mac an Uidhir',
    'O Madden': 'Ó Madáin',
    'Madden': 'Ó Madáin',
    'Maddigan': 'Ó Madagáin',
    'Maddocks': 'Mac Mhadóg',
    'Maddock': 'Mac Mhadóg',
    'Maddy': 'Ó Madaidh',
    'Madole': 'Mac Dúghaill',
    'O Madeen': 'Ó Madáin',
    'Madeen': 'Ó Madáin',
    'Magahan': 'Mag Eacháin',
    'Magaharan': 'Mag Eachráin',
    'magall': 'Mac Cathail',
    'Magann': 'Mag Annaidh',
    'Magan': 'Mag Annaidh',
    'Magarry': 'Mag Fhearaigh',
    'Magauley': 'Mag Amhalaí',
    'Magauran': 'Mag Shamhráin',
    'Magaw': 'Mag Adhaimh',
    'Magee': 'Mag Aoidh',
    'Mageean': 'Mag Aedhín',
    'Mageehan': 'Mag Gaoithín',
    'Magennis': 'Mag Aonasa',
    'Mageogh': 'Mag Eothach',
    'Mageown': 'Mag Eoghain',
    'Magetty': 'Mag Eitigh',
    'Maghan': 'Ó Macháin',
    'Magher': 'Ó Meachair',
    'Maghery': 'an Mhachaire',
    'Magill': 'Mac an Ghoill',
    'Magilligan': 'Mac Giollagáin',
    'Magillowy': 'Mac Giolla Bhuí',
    'Magilly': 'Mac an Choiligh',
    'Maginn': 'Mag Fhinn',
    'Maginver': 'Mac Fhionnbhairr',
    'Maglade': 'Mag Léid',
    'Maglamery': 'Mac Giolla Domhnaigh',
    'Maglanchy': 'Mag Lannchaidh',
    'Maglennon': 'Mag Leannáin',
    'Maglinn': 'Mag Fhloinn',
    'Maglin': 'Mag Fhloinn',
    'Magner': 'Maingnéir',
    'Magone': 'Mag Eoghain',
    'Magournahan': 'Mag Cuarnacháin',
    'Magourtey': 'Mag Dhorchaidh',
    'Magrane': 'Mag Ráine',
    'Magreavy': 'Mag Riabhaigh',
    'Magreece': 'Mag Raois',
    'Magrery': 'Mag Ruairí',
    'Magroarty': 'Mag Ruartaigh',
    'Magroder': 'Mag Bhruadair',
    'Magrory': 'Mag Ruairí',
    'Magrudden': 'Mag Rodáin',
    'Maguane': 'Mag Dhuáin',
    'Maguigan': 'Mag Uiginn',
    'Maguire': 'Mag Uidhir',
    'Maguirke': 'Mag Coirc',
    'Magullion': 'Mac Coilín',
    'Mahady': 'Ó Moithide',
    'Mahaffy': 'Mac Dhuifíthe',
    'Magarg': 'Mac Giolla Chairge',
    'Maharry': 'Mac Fhearaigh',
    'Mahedy': 'Ó Moithide',
    'O Maher': 'Ó Meachair',
    'Maher': 'Ó Meachair',
    'Mahew': 'Mac Máighiú',
    'Maholland': 'Ó Maolchallann',
    'Mahollum': 'Ó Maolcholaim',
    'Mac Mahon': 'Mac Mathúna',
    'Mahon': 'Mac Mathúna',
    'O Mahony': 'Ó Mathúna',
    'Mahony': 'Ó Mathúna',
    'Mahood': 'Mac Uid',
    'Mailey': 'Ó Máille',
    'Mayne': 'Mac Mánais',
    'Main': 'Mac Mánais',
    'O Meany': 'Ó Maonaigh',
    'O Mainey': 'Ó Maonaigh',
    'Meany': 'Ó Maonaigh',
    'Mainey': 'Ó Maonaigh',
    'Mainwaring': 'Ó Manaráin',
    'Mears': 'Ó Mír',
    'Maires': 'Ó Mír',
    'Mears': 'Ó Mír',
    'Maires': 'Ó Mír',
    'Makem': 'Ó Maolcholaim',
    'Makin': 'Mac Coinn',
    'Makinson': 'Mac Miacháin',
    'O Malady': 'Ó Maoiléidigh',
    'Malady': 'Ó Maoiléidigh',
    'Malaniffe': 'Ó Maolainfe',
    'Malarky': 'Ó Maoilearca',
    'Malcolm': 'Ó Maolcholaim',
    'Malcolmson': 'Mac Maolcholaim',
    'Maley': 'Ó Máille',
    'Melia': 'Ó Máille',
    'Malia': 'Ó Máille',
    'Mallick': 'Mac Míoluic',
    'Malick': 'Mac Míoluic',
    'Maliffe': 'Ó Maoluibh',
    'O Malin': 'Ó Maoilinn',
    'Malin': 'Ó Maoilinn',
    'Malise': 'Mac Maoilíosa',
    'Mallagh': 'Máilleach',
    'Mallaghan': 'Ó Molacháin',
    'Mallon': 'Ó Mealláin',
    'Mallan': 'Ó Mealláin',
    'O Mallane': 'Ó Maoláin',
    'Mallane': 'Ó Maoláin',
    'Mallavin': 'Ó Maoiléimhín',
    'Mallew': 'Ó Maolaodha',
    'Malley': 'Ó Máille',
    'O Mallin': 'Ó Mealláin',
    'O Mallon': 'Ó Mealláin',
    'Mallin': 'Ó Mealláin',
    'Mallon': 'Ó Mealláin',
    'O Malmona': 'Ó Maolmóna',
    'Malmona': 'Ó Maolmóna',
    'O Malone': 'Ó Maoileoin',
    'Malone': 'Ó Maoileoin',
    'O Malony': 'Ó Maolomhnaigh',
    'Malony': 'Ó Maolomhnaigh',
    'O Maloughney': 'Ó Maolachtna',
    'Maloughney': 'Ó Maolachtna',
    'O Maloy': 'Ó Maolmhuaidh',
    'Maloy': 'Ó Maolmhuaidh',
    'O Malynn': 'Ó Maoilinn',
    'O Malyn': 'Ó Maoilinn',
    'Malynn': 'Ó Maoilinn',
    'Malyn': 'Ó Maoilinn',
    'O Manahan': 'Ó Manacháin',
    'Manahan': 'Ó Manacháin',
    'O Manihan': 'Ó Mainchín',
    'O Manahan': 'Ó Mainchín',
    'Manihan': 'Ó Mainchín',
    'Manahan': 'Ó Mainchín',
    'Manally': 'Mac an Fhailí',
    'Mac Manaman': 'Mac Meanman',
    'Mac Manamon': 'Mac Meanman',
    'Manamon': 'Mac Meanman',
    'Mac Manamy': 'Mac Meanma',
    'Manary': 'Mac Náraigh',
    'Manasses': 'Mac Mánasa',
    'Manaway': 'Mac Meanma',
    'de Mandeville': 'Móinbhíol',
    'Mandeville': 'Móinbhíol',
    'Maneely': 'Mac an Fhile',
    'Manellis': 'Mac Niallais',
    'Manelis': 'Mac Niallais',
    'O Mangan': 'Ó Mongáin',
    'Mangan': 'Ó Mongáin',
    'Mangner': 'Maingnéir',
    'Manice': 'Mac Naois',
    'Manihin': 'Ó Mainchín',
    'Mac Manus': 'Mac Mánais',
    'Mac Manis': 'Mac Mánais',
    'Manley': 'Ó Maonaile',
    'Manley': 'Ó Corcaigh',
    'Manley': 'Ó Máinle',
    'Mac Mann': 'Mac Mathúna',
    'Mann': 'Ó Macháin',
    'Mannering': 'Ó Manaráin',
    'Mannight': 'Mac Neachtain',
    'O Mannion': 'Ó Mainnín',
    'O Mannin': 'Ó Mainnín',
    'Mannion': 'Ó Mainnín',
    'Mannin': 'Ó Mainnín',
    'Manning': 'Ó Mainnín',
    'Mannin': 'Ó Mainnín',
    'Mannis': 'Mac Naois',
    'Mannix': 'Ó Mainchín',
    'Meany': 'Ó Maine',
    'Manny': 'Ó Maine',
    'Manogue': 'Ó Manóg',
    'Manron': 'Ó Manaráin',
    'Mansell': 'Móinséil',
    'Mansfield': 'Móinbhíol',
    'Mintin': 'Ó Mantáin',
    'Manton': 'Ó Mantáin',
    'Mac Manus': 'Mac Mánais',
    'Manus': 'Mac Mánais',
    'Many': 'Ó Maine',
    'Mape': 'Máp',
    'Maqueen': 'Mac Shuibhne',
    'O Mara': 'Ó Meára',
    'Mara': 'Ó Meára',
    'Maragan': 'Ó Muireagáin',
    'O Marey': 'Ó Mearaigh',
    'O Maree': 'Ó Mearaigh',
    'Marey': 'Ó Mearaigh',
    'Maree': 'Ó Mearaigh',
    'O Markha': 'Ó Marcacháin',
    'O Markahan': 'Ó Marcacháin',
    'Markha': 'Ó Marcacháin',
    'Markahan': 'Ó Marcacháin',
    'Marks': 'Mac Marcais',
    'Mark': 'Mac Marcais',
    'O Markey': 'Ó Marcaigh',
    'Markey': 'Ó Marcaigh',
    'Marlborough': 'Ó Maoilbhearaigh',
    'O Marley': 'Ó Mearthaile',
    'Marley': 'Ó Mearthaile',
    'Marmion': 'Mac Meanman',
    'Marnane': 'Ó Murnáin',
    'O Marnon': 'Ó Mearnáin',
    'O Marnen': 'Ó Mearnáin',
    'Marnon': 'Ó Mearnáin',
    'Marnen': 'Ó Mearnáin',
    'O Marriga': 'Ó Meardha',
    'Marriga': 'Ó Meardha',
    'Marrilly': 'Ó Muraile',
    'O Marrinan': 'Ó Marannáin',
    'Marrinan': 'Ó Marannáin',
    'O Marron': 'Ó Mearáin',
    'Marron': 'Ó Mearáin',
    'Marry': 'Ó Mearaigh',
    'Marsh': 'de Moiréis',
    'Marshall': 'Marascal',
    'Martell': 'Moirtéill',
    'Martin': 'Ó Máirtín',
    'Martinson': 'Mac Máirtín',
    'Mason': 'Masún',
    'Massey': 'Measaigh',
    'Mac Master': 'Mac an Mháistir',
    'Masterson': 'Mac an Mháistir',
    'Master': 'Mac an Mháistir',
    'Mateer': 'Mac an tSaoir',
    'Mac Math': 'Mac Matha',
    'Matheson': 'Mac Matha',
    'Mathew': 'Maitiú',
    'Mathews': 'Mac Mathúna',
    'Mathewson': 'Mac Matha',
    'Mathias': 'Mac Maithís',
    'Mattimoe': 'Ó Maolmuaidh',
    'O Maughan': 'Ó Macháin',
    'Maughan': 'Ó Macháin',
    'Maune': 'Mághún',
    'Maunsel': 'Móinséil',
    'Maurice': 'Mac Muiris',
    'Mavity': 'Mac an Bhiataigh',
    'Mac Mawe': 'Mac Máighe',
    'Mawe': 'Mac Máighe',
    'Mawhannon': 'Ó Buacháin',
    'Mawhinny': 'Mac Shuibhne',
    'Mawhirter': 'Mac Artair',
    'Mawne': 'Mághún',
    'Maxwell': 'Ó Meiscill',
    'Maxel': 'Ó Meiscill',
    'Maxey': 'Ó Mascasa',
    'Mac May': 'Mac Máighe',
    'May': 'Ó Miadhaigh',
    'Maybin': 'Máibín',
    'Maydole': 'Mac Dúghaill',
    'Mayduck': 'Madóg',
    'Mayers': 'O Mír',
    'Mayhew': 'Máighiú',
    'Maynard': 'Méanart',
    'Mac Mayo': 'Mac Máighiú',
    'Mayo': 'Mac Máighiú',
    'Mayrick': 'Ó Mearaigh',
    'O Mea': 'Ó Miadhaigh',
    'Mea': 'Ó Miadhaigh',
    'Meade': 'Miach',
    'O Meagher': 'Ó Meachair',
    'Meagher': 'Ó Meachair',
    'Meally': 'Ó Meallaigh',
    'O Mealue': 'Ó Maolaoidh',
    'Mealue': 'Ó Maolaoidh',
    'O Meany': 'Ó Maonaigh',
    'Meany': 'Ó Maonaigh',
    'O Mara': 'Ó Meára',
    'O Meara': 'Ó Meára',
    'Mara': 'Ó Meára',
    'Meara': 'Ó Meára',
    'Meares': 'Ó Mír',
    'Mearn': 'Ó Mearáin',
    'Mac Mearty': 'Mac Briartaigh',
    'Meath': 'Mac Matha',
    'Meath': 'Mac Con Midhe',
    'Mecmeckin': 'Mac Miacháin',
    'MacReady': 'Mac Riada',
    'Mecredy': 'Mac Riada',
    'O Mee': 'Ó Miadhaigh',
    'Mee': 'Ó Miadhaigh',
    'O Meegan': 'Ó Miagáin',
    'Meegan': 'Ó Miagáin',
    'Meehagan': 'Ó Maothagáin',
    'Mac Meehan': 'Mac Miacháin',
    'O Meehan': 'Ó Miacháin',
    'Meehan': 'Ó Miacháin',
    'Mac Meekan': 'Mac Miacháin',
    'Mac Meekin': 'Mac Miacháin',
    'Meekan': 'Mac Miacháin',
    'Meekin': 'Mac Miacháin',
    'Mac Meel': 'Mac Giolla Mhichil',
    'Meelderry': 'Ó Maoldoraidh',
    'Meenagh': 'Muíneach',
    'O Meenaghan': 'Ó Muíneacháin',
    'Meenaghan': 'Ó Muíneacháin',
    'O Meenan': 'Ó Mianáin',
    'Meenan': 'Ó Mianáin',
    'O Meeney': 'Ó Maonaigh',
    'Meeney': 'Ó Maonaigh',
    'O Meere': 'Ó Mír',
    'Meere': 'Ó Mír',
    'Megahan': 'Mag Eacháin',
    'Magall': 'Mag Cathail',
    'Megall': 'Mag Cathail',
    'Megan': 'Mag Annaidh',
    'Magaw': 'Mag Adhaimh',
    'Magaw': 'Mag Adhaimh',
    'Maghan': 'Ó Miacháin',
    'Meglamry': 'Mag Labhraidh',
    'Mehan': 'Ó Miacháin',
    'Meharg': 'Mac Giolla Chairge',
    'Mehigan': 'Ó Maothagáin',
    'Meickle': 'Mac Michil',
    'Meighan': 'Ó Miacháin',
    'Melaghlin': 'Ó Maoileachlainn',
    'O Melaghlin': 'Ó Maoileachlainn',
    'Melampy': 'Ó Maolanfaidh',
    'Melane': 'Ó Maoláin',
    'Melanphy': 'Ó Maolanfaidh',
    'Melarkey': 'Ó Maoilearca',
    'Melaugh': 'Ó Maolaodhóg',
    'Melay': 'Ó Maolaodha',
    'Meldon': 'Ó Maoldúin',
    'Meleady': 'Ó Maoiléidigh',
    'Melia': 'Ó Máille',
    'Melican': 'Ó Maoileacháin',
    'Melland': 'Ó Mealláin',
    'Mellan': 'Ó Mealláin',
    'O Mellerick': 'Ó Maoilgheiric',
    'Mellerick': 'Ó Maoilgheiric',
    'Mellit': 'Méalóid',
    'Mellet': 'Méalóid',
    'Meliffe': 'Ó Maolluibh',
    'Mellis': 'Mac Maoilíosa',
    'Mellon': 'Ó Mealláin',
    'Mellowes': 'Mac Maoilíosa',
    'Melly': 'Ó Meallaigh',
    'Melody': 'Ó Maoiléidigh',
    'Melroy': 'Ó Maolrua',
    'Melvenny': 'Ó Maoilmheana',
    'Melville': 'Ó Maoilmhichil',
    'Melvin': 'Ó Maoilmhín',
    'Menaght': 'Mac Neachtain',
    'Menahan': 'Ó Muineacháin',
    'Mac Menamin': 'Mac Meanman',
    'Menamin': 'Mac Meanman',
    'Mac Menamy': 'Mac Meanma',
    'Menarry': 'Mac Náraigh',
    'Menary': 'Mac Náraigh',
    'Menautt': 'Mac Neachtain',
    'Meneese': 'Mac Naois',
    'Mac Menim': 'Mac Meanman',
    'Menocher': 'Mac Conchúir',
    'Menton': 'Ó Mantáin',
    'Meran': 'Ó Mearáin',
    'Mergach': 'Meirgeach',
    'Mergin': 'Ó Meirgín',
    'Merlehan': 'Ó Meirleacháin',
    'Mernagh': 'Meirtneach',
    'Mernin': 'Ó Meirnín',
    'Merrick': 'Mac Meiric',
    'Merrigan': 'Ó Muireagáin',
    'Merriman': 'Mac Meanman',
    'Merry': 'Ó Mearaigh',
    'Merwick': 'Mac Meiric',
    'Mac Merty': 'Mac Muireartaigh',
    'O Mescal': 'Ó Meiscill',
    'Mescal': 'Ó Meiscill',
    'O Mescell': 'Ó Meiscill',
    'Mescell': 'Ó Meiscill',
    'Meskella': 'Mac Scalaí',
    'Meskelly': 'Mac Scalaí',
    'Mac Mey': 'Mac Maighe',
    'Meyers': 'Ó Mír',
    'Meyer': 'Ó Mír',
    'Meyler': 'Mac Maoilir',
    'Michael': 'Ó Maoilmhichil',
    'Miall': 'Ó Maoilmhichil',
    'Mac Michael': 'Mac Michil',
    'Mac Michalin': 'Mac Michilín',
    'Mac Michan': 'Mac Miacháin',
    'Micklebride': 'Mac Giolla Bhríde',
    'Mac Mighall': 'Mac Michil',
    'Miland': 'Ó Maoileáin',
    'Miles': 'Ó Maolmhuire',
    'Miley': 'Ó Maolaoidh',
    'Milford': 'Ó Maolómhair',
    'Mihair': 'Ó Maoilchéire',
    'Maliffe': 'Ó Maoluibh',
    'Miliffe': 'Ó Maoluibh',
    'Miligan': 'Ó Maoileagáin',
    'Mac Millan': 'Mac Maoláin',
    'O Millane': 'Ó Maoláin',
    'Millane': 'Ó Maoláin',
    'Milar': 'Muilleoir',
    'O Millbride': 'Ó Maoilbhríde',
    'Millbride': 'Ó Maoilbhríde',
    'O Millea': 'Ó Maolaoidh',
    'Millea': 'Ó Maolaoidh',
    'Millen': 'Ó Maoilín',
    'Millerick': 'Ó Maoilgheiric',
    'Millet': 'Méalóid',
    'Milligan': 'Ó Maoileagáin',
    'Millican': 'Ó Maoileagáin',
    'Millikin': 'Ó Maoileagáin',
    'Mac Millin': 'Mac Maoilín',
    'Millin': 'Ó Maoilín',
    'Milne': 'Mac Maoláin',
    'Milling': 'Mac Maoláin',
    'Mills': 'an Mhuilinn',
    'Milmo': 'Ó Maolmuaidh',
    'Milreavy': 'Ó Maoilriabhaigh',
    'Milroy': 'Ó Maolrua',
    'Minagh': 'Muíneach',
    'Minahane': 'Ó Mionacháin',
    'Minahan': 'Ó Mionacháin',
    'Mac Minamy': 'Mac Meanma',
    'Mineely': 'Mac an Fhile',
    'Minch': 'Mac Naois',
    'Minchin': 'Mac Naois',
    'Minch': 'Mac Naois',
    'Mines': 'Ó Muín',
    'Minett': 'Mac Neachtain',
    'Mingane': 'Ó Muineagáin',
    'Miniece': 'Mac Naois',
    'O Minihane': 'Ó Muíneacháin',
    'Minihane': 'Ó Muíneacháin',
    'Mac Minimin': 'Mac Meanman',
    'Miniter': 'Minitéir',
    'Mac Minn': 'Mac Minne',
    'Minnagh': 'Muíneach',
    'O Minnock': 'Ó Muineog',
    'Minnock': 'Ó Muineog',
    'Minnis': 'Mac Naois',
    'Minochor': 'Mac Conchúir',
    'Minogue': 'Ó Muineog',
    'Minorgan': 'Mac Norgáin',
    'Minteer': 'Mac an tSaoir',
    'Mintin': 'Ó Mantáin',
    'Mireen': 'Ó Mirín',
    'Missett': 'Miséid',
    'Mitchell': 'Mistéil',
    'Moakley': 'Ó Mathlaigh',
    'Moan': 'Ó Mocháin',
    'Moany': 'Ó Maonaigh',
    'Mockler': 'Móicléir',
    'Moen': 'Ó Mocháin',
    'Moffett': 'Moiféid',
    'Moghan': 'Ó Mocháin',
    'O Mohan': 'Ó Mocháin',
    'Mohan': 'Ó Mocháin',
    'O Moher': 'Ó Mothair',
    'Moher': 'Ó Mothair',
    'Mohide': 'Ó Muichide',
    'O Mohilly': 'Ó Mothlaigh',
    'Mohilly': 'Ó Mothlaigh',
    'O Molahan': 'Ó Mothlacháin',
    'Molahan': 'Ó Mothlacháin',
    'Molamphy': 'Ó Maolanfaidh',
    'O Molan': 'Ó Mothlacháin',
    'Molan': 'Ó Mothlacháin',
    'Moley': 'Ó Mothlaigh',
    'Mollarky': 'Ó Maoilearca',
    'O Molloy': 'Ó Maolmhuaidh',
    'Molloy': 'Ó Maolmhuaidh',
    'O Mologhney': 'Ó Maolfhachtna',
    'Mologhney': 'Ó Maolfhachtna',
    'O Molohan': 'Ó Maolacháin',
    'Molohan': 'Ó Maolacháin',
    'O Moloney': 'Ó Maolomhnaigh',
    'O Molony': 'Ó Maolomhnaigh',
    'Moloney': 'Ó Maolomhnaigh',
    'Molony': 'Ó Maolomhnaigh',
    'Molphy': 'Ó Murchú',
    'Molumby': 'Ó Maolchomadh',
    'Molvin': 'Ó Maoilmhín',
    'Molyneaux': 'Ó Maolagáin',
    'Monaboe': 'Mac Anabaí',
    'Mac Monagle': 'Mac Maonghail',
    'Monagle': 'Mac Maonghail',
    'O Monahan': 'Ó Manacháin',
    'Monahan': 'Ó Manacháin',
    'O Monaher': 'Ó Manachair',
    'Monaher': 'Ó Manachair',
    'Monday': 'Mac Giolla Eoin',
    'Monegan': 'Ó Managáin',
    'Money': 'Ó Maonaigh',
    'O Mongan': 'Ó Mongáin',
    'Mongan': 'Ó Mongáin',
    'Mongavan': 'Ó Mongabháin',
    'O Mongey': 'Ó Mongaigh',
    'Mongey': 'Ó Mongaigh',
    'Mac Monigal': 'Mac Maonghail',
    'Monks': 'Ó Manacháin',
    'Monk': 'Ó Manacháin',
    'O Monnelly': 'Ó Maonaile',
    'Monnelly': 'Ó Maonaile',
    'Monroe': 'Mac an Róthaich',
    'Monsell': 'Móinséil',
    'Montague': 'Mac Taidhg',
    'Montane': 'Ó Mantáin',
    'Montgomery': 'Mac Iomaire',
    'Moody': 'Ó Muadaigh',
    'Moohan': 'Ó Mocháin',
    'Moon': 'Ó Mocháin',
    'O Moonan': 'Ó Muanáin',
    'Moonan': 'Ó Muanáin',
    'O Mooney': 'Ó Maonaigh',
    'Mooney': 'Ó Maonaigh',
    'O Moore': 'Ó Móra',
    'Moore': 'Ó Móra',
    'O Morahan': 'Ó Murcháin',
    'Morahan': 'Ó Murcháin',
    'O Moran': 'Ó Móráin',
    'Moran': 'Ó Móráin',
    'Mac Morans': 'Mac Móráin',
    'Mac Moran': 'Mac Móráin',
    'O Morchoe': 'Ó Murchú',
    'Morchoe': 'Ó Murchú',
    'Mac Mordie': 'Mac Muireartaigh',
    'O More': 'Ó Móra',
    'Moreen': 'Ó Móirin',
    'Moreland': 'Mac Muraláin',
    'Morell': 'Ó Murail',
    'Moren': 'Ó Móirín',
    'Moreton': 'Mortún',
    'Morey': 'Ó Móra',
    'Morgan': 'Ó Muireagáin',
    'O Moriarty': 'Ó Muireartaigh',
    'Moriarty': 'Ó Muireartaigh',
    'Morice': 'Ó Muiris',
    'Morisey': 'Ó Muireasa',
    'Morrison': 'Ó Muireasáin',
    'Morison': 'Ó Muireasáin',
    'Moriss': 'Ó Muiris',
    'Morkan': 'Ó Murcháin',
    'Morland': 'Mac Muraláin',
    'Morley': 'Ó Muraile',
    'Mornan': 'Ó Murnáin',
    'Morney': 'Ó Murnáin',
    'Morohan': 'Ó Murcháin',
    'O Moroney': 'Ó Maolruanaidh',
    'Moroney': 'Ó Maolruanaidh',
    'Morphy': 'Ó Murchú',
    'Mac Morray': 'Mac Muirí',
    'Morresh': 'Moiréis',
    'Morrin': 'Ó Muirín',
    'Morris': 'Ó Muiris',
    'Mac Morris': 'Mac Muiris',
    'Morrison': 'Ó Muireasáin',
    'Mac Morrisroe': 'Mac Muiris Rua',
    'Morrisroe': 'Mac Muiris Rua',
    'Morrissey': 'Ó Muireasa',
    'Morrolly': 'Ó Muraile',
    'Morrough': 'Mac Murchú',
    'Mac Morrow': 'Mac Muirí',
    'Morrow': 'Mac Muirí',
    'Morrowson': 'Mac Murchú',
    'Mac Morry': 'Mac Muirí',
    'Morry': 'Mac Muirí',
    'Mortagh': 'Mac Muireartaigh',
    'Mortell': 'Moirtéil',
    'Mortimer': 'Ó Muireartaigh',
    'Mortland': 'Mac Muraláin',
    'Mortimer': 'Mac Muireartaigh',
    'Morton': 'Mortún',
    'Moss': 'Ó Maolmóna',
    'Motherway': 'Modartha',
    'Motley': 'Moitlé',
    'Moughan': 'Ó Mocháin',
    'Moughty': 'Ó Mochta',
    'Mountain': 'Ó Mantáin',
    'Mountcashel': 'Ó Maolchaisil',
    'Mowen': 'Ó Mocháin',
    'Moy': 'Ó Muighe',
    'Mac Moyer': 'Mac an Mhaoir',
    'Moyers': 'Mac an Mhaoir',
    'O Moylan': 'Ó Maoileáin',
    'Moylan': 'Ó Maoileáin',
    'Moyle': 'Ó Maolmhuire',
    'de Moylens': 'Ó Maoláin',
    'Moylens': 'Ó Maoláin',
    'Mac Moyler': 'Maoilir',
    'Moyles': 'Ó Maolmhuire',
    'Moylet': 'Méalóid',
    'Moynagh': 'Muíneach',
    'Moynes': 'Ó Muín',
    'Moyney': 'Ó Muínigh',
    'O Moynihan': 'Ó Muíneacháin',
    'Moynihan': 'Ó Muíneacháin',
    'Mac Mrearty': 'Mac Muireartaigh',
    'Mucbrin': 'Mac Broin',
    'Muckady': 'Mac Ádaidh',
    'Muckaran': 'Mac Eachráin',
    'Muckedan': 'Mac Cadáin',
    'O Muckeen': 'Ó Mochaín',
    'Muckeen': 'Ó Mochaín',
    'O Muckian': 'Ó Mochaín',
    'Muckian': 'Ó Mochaín',
    'Muckilbouy': 'Mac Giolla Bhuí',
    'Mucklebreed': 'Mac Giolla Bhríde',
    'Muckle': 'Mac Ghiolla Bhríde',
    'Mucklebreed': 'Mac Ghiolla Bhríde',
    'Muckler': 'Moicléir',
    'O Mulclahy': 'Ó Maolchluiche',
    'O Muckley': 'Ó Maolchluiche',
    'Mulclahy': 'Ó Maolchluiche',
    'Muckley': 'Ó Maolchluiche',
    'Mugan': 'Ó Mocháin',
    'Muggevan': 'Ó Mongalbháin',
    'Muir': 'de Múra',
    'Muirland': 'Mac Muraláin',
    'O Mulally': 'Ó Maolalaidh',
    'Mulally': 'Ó Maolalaidh',
    'Mulavil': 'Ó Maolábhail',
    'Mulberry': 'Ó Maoilbhearaigh',
    'O Mulbrandon': 'Ó Maoilbhreandáin',
    'Mulbrandon': 'Ó Maoilbhreandáin',
    'Mulbride': 'Ó Maoilbhríde',
    'Mulbreedy': 'Ó Maoilbhríde',
    'O Mulcahy': 'Ó Maolchathaigh',
    'Mulcahy': 'Ó Maolchathaigh',
    'O Mulcair': 'Ó Maoilchéire',
    'Mulcair': 'Ó Maoilchéire',
    'Mulcashel': 'Ó Maolchaisil',
    'O Mulchrone': 'Ó Maolchróin',
    'Mulchrone': 'Ó Maolchróin',
    'O Mulclohy': 'Ó Maolchluiche',
    'Mulclohy': 'Ó Maolchluiche',
    'Mulconry': 'Ó Maolchonaire',
    'O Mulcreevy': 'Ó Maolchraoibhe',
    'Mulcreevy': 'Ó Maolchraoibhe',
    'O Mulcrowney': 'Ó Maolchróine',
    'Mulcrowney': 'Ó Maolchróine',
    'O Mulderry': 'Ó Maoldoraidh',
    'O Muldarry': 'Ó Maoldoraidh',
    'Mulderry': 'Ó Maoldoraidh',
    'Muldarry': 'Ó Maoldoraidh',
    'O rig': 'Ó Maoildeirg',
    'O Muldeg': 'Ó Maoildeirg',
    'rig': 'Ó Maoildeirg',
    'Muldeg': 'Ó Maoildeirg',
    'O Muldoon': 'Ó Maoldúin',
    'O Muldon': 'Ó Maoldúin',
    'Muldoon': 'Ó Maoldúin',
    'Muldon': 'Ó Maoldúin',
    'O Muldowney': 'Ó Maoldomhnaigh',
    'O Muldoony': 'Ó Maoldomhnaigh',
    'Muldowney': 'Ó Maoldomhnaigh',
    'Muldoony': 'Ó Maoldomhnaigh',
    'O Mulfaal': 'Ó Maolábhail',
    'Mulfaal': 'Ó Maolábhail',
    'O Mulgan': 'Ó Maolagáin',
    'Mulgan': 'Ó Maolagáin',
    'O Mulgeehy': 'Ó Maolghaoithe',
    'Mulgeehy': 'Ó Maolghaoithe',
    'O Mulgrew': 'Ó Maolchraoibhe',
    'O Mulgrave': 'Ó Maolchraoibhe',
    'Mulgrew': 'Ó Maolchraoibhe',
    'Mulgrave': 'Ó Maolchraoibhe',
    'Mulgrievy': 'Ó Maolchraoibhe',
    'O Mulhall': 'Ó Maolchathail',
    'Mulhall': 'Ó Maolchathail',
    'O Mulhallen': 'Ó Maolchallann',
    'Mulhallen': 'Ó Maolchallann',
    'O Mulhane': 'Ó Maoláin',
    'Mulhane': 'Ó Maoláin',
    'O Mulhare': 'Ó Maoilchéire',
    'Mulhare': 'Ó Maoilchéire',
    'O Mulhartach': 'Ó Maolathartaigh',
    'Mulhartach': 'Ó Maolathartaigh',
    'O Mulhatton': 'Ó Maolchatáin',
    'Mulhatton': 'Ó Maolchatáin',
    'O Mulhearn': 'Ó Maoilchiaráin',
    'Mulhearn': 'Ó Maoilchiaráin',
    'O Mulholland': 'Ó Maolchallann',
    'O Mulhollan': 'Ó Maolchallann',
    'Mulholland': 'Ó Maolchallann',
    'Mulhollan': 'Ó Maolchallann',
    'O Mulhollum': 'Ó Maolcholaim',
    'Mulhollum': 'Ó Maolcholaim',
    'O Mulholn': 'Ó Maolchallann',
    'Mulholn': 'Ó Maolchallann',
    'O Mulkearns': 'Ó Maoilchiaráin',
    'O Mulkearn': 'Ó Maoilchiaráin',
    'Mulkearns': 'Ó Maoilchiaráin',
    'Mulkearn': 'Ó Maoilchiaráin',
    'Mulkeen': 'Ó Maolchaoin',
    'Mulkere': 'Ó Maoilchéire',
    'O Mulkerril': 'Ó Maolchairill',
    'Mulkerril': 'Ó Maolchairill',
    'O Mulkerrin': 'Ó Maoilchiaráin',
    'Mulkerrin': 'Ó Maoilchiaráin',
    'Mac Mulkin': 'Mac Maolchaoin',
    'O Mullagan': 'Ó Maolagáin',
    'Mullagan': 'Ó Maolagáin',
    'O Mullahy': 'Ó Maolaiche',
    'Mullahy': 'Ó Maolaiche',
    'O Mullally': 'Ó Maolalaidh',
    'Mullally': 'Ó Maolalaidh',
    'Mac Mullan': 'Mac Maoláin',
    'O Mullane': 'Ó Maoláin',
    'O Mullan': 'Ó Maoláin',
    'Mullane': 'Ó Maoláin',
    'Mullan': 'Ó Maoláin',
    'O Mullaney': 'Ó Maoileanaigh',
    'Mullaney': 'Ó Maoileanaigh',
    'O Mullanphy': 'Ó Maolainfe',
    'Mullanphy': 'Ó Maolainfe',
    'O Mullany': 'Ó Maoileanaigh',
    'Mullany': 'Ó Maoileanaigh',
    'O Mullarkey': 'Ó Maoilearca',
    'Mullarkey': 'Ó Maoilearca',
    'Mullarney': 'Ó Maoilearna',
    'O Mullavin': 'Ó Maoiléimhín',
    'Mullavin': 'Ó Maoiléimhín',
    'O Mullavogue': 'Ó Maolmhadhóg',
    'Mullavogue': 'Ó Maolmhadhóg',
    'O Mulbride': 'Ó Maoilbhríde',
    'Mulbride': 'Ó Maoilbhríde',
    'O Mulleady': 'Ó Maoiléidigh',
    'Mulleady': 'Ó Maoiléidigh',
    'Mulleague': 'Mac Míoluic',
    'O Mullee': 'Ó Maolaoidh',
    'Mullee': 'Ó Maolaoidh',
    'O Mulleen': 'Ó Maoilín',
    'Mulleen': 'Ó Maoilín',
    'O Mullen': 'Ó Maoláin',
    'Mullen': 'Ó Maoláin',
    'O Mullerick': 'Ó Maoilgheiric',
    'Mullerick': 'Ó Maoilgheiric',
    'O Mullery': 'Ó Maolmhuire',
    'Mullery': 'Ó Maolmhuire',
    'Mullet': 'Méalóid',
    'O Múlligan': 'Ó Maolagáin',
    'Múlligan': 'Ó Maolagáin',
    'O Mullihan': 'Ó Maolacháin',
    'Mullihan': 'Ó Maolacháin',
    'Mullins': 'Ó Maoláin',
    'Mullin': 'Ó Maoláin',
    'Mullock': 'Mac Míoluic',
    'O Mullogan': 'Ó Maolagáin',
    'Mullogan': 'Ó Maolagáin',
    'O Mullon': 'Ó Maoláin',
    'Mullon': 'Ó Maoláin',
    'Mulloon': 'Ó Maoileoin',
    'O Mulloughney': 'Ó Maolfhachtna',
    'Mulloughney': 'Ó Maolfhachtna',
    'O Mullover': 'Ó Maolómhair',
    'Mullover': 'Ó Maolómhair',
    'O Mulloy': 'Ó Maoimhuaidh',
    'Mulloy': 'Ó Maoimhuaidh',
    'O Mullreavy': 'Ó Maoilriabhaigh',
    'Mullreavy': 'Ó Maoilriabhaigh',
    'O Mullveen': 'Ó Maoilmhín',
    'Mullveen': 'Ó Maoilmhín',
    'O Mulvihill': 'Ó Maoilmhichil',
    'Mulvihill': 'Ó Maoilmhichil',
    'O Mulmohery': 'Ó Maolmochéirí',
    'Mulmohery': 'Ó Maolmochéirí',
    'O Mulmona': 'Ó Maolmóna',
    'Mulmona': 'Ó Maolmóna',
    'Mulogue': 'Mac Míoluic',
    'O Mulooly': 'Ó Maoluala',
    'Mulooly': 'Ó Maoluala',
    'O Mulpatrick': 'Ó Maolphádraig',
    'Mulpatrick': 'Ó Maolphádraig',
    'O Mulpeters': 'Ó Maoilpheadair',
    'O Mulpeter': 'Ó Maoilpheadair',
    'Mulpeters': 'Ó Maoilpheadair',
    'Mulpeter': 'Ó Maoilpheadair',
    'O Mulqueen': 'Ó Maolchaoin',
    'Mulqueen': 'Ó Maolchaoin',
    'O Mulqueeny': 'Ó Maolchaoine',
    'Mulqueeny': 'Ó Maolchaoine',
    'O Mulquin': 'Ó Maolchaoin',
    'Mulquin': 'Ó Maolchaoin',
    'O Mulrain': 'Ó Maoilriain',
    'Mulrain': 'Ó Maoilriain',
    'O Mulready': 'Ó Maoilbhríde',
    'Mulready': 'Ó Maoilbhríde',
    'O Mulreany': 'Ó Maoilréana',
    'Mulreany': 'Ó Maoilréana',
    'O Mulreavy': 'Ó Maoilriabhaigh',
    'Mulreavy': 'Ó Maoilriabhaigh',
    'O Mulreannan': 'Ó Maoilbhréanainn',
    'Mulreannan': 'Ó Maoilbhréanainn',
    'O Mulrine': 'Ó Maoilriain',
    'Mulrine': 'Ó Maoilriain',
    'O Mulroe': 'Ó Maolrua',
    'Mulroe': 'Ó Maolrua',
    'O Mulrooney': 'Ó Maolruanaidh',
    'O Mulroney': 'Ó Maolruanaidh',
    'Mulrooney': 'Ó Maolruanaidh',
    'Mulroney': 'Ó Maolruanaidh',
    'O Mulroy': 'Ó Maolrua',
    'O Mulrow': 'Ó Maolrua',
    'Mulroy': 'Ó Maolrua',
    'Mulrow': 'Ó Maolrua',
    'O Mulryan': 'Ó Maoilriain',
    'Mulryan': 'Ó Maoilriain',
    'O Mulshinock': 'Ó Maoilsionóg',
    'Mulshinock': 'Ó Maoilsionóg',
    'O Multilly': 'Ó Maoltuile',
    'Multilly': 'Ó Maoltuile',
    'Mulumphy': 'Ó Maolanfaidh',
    'Mulumy': 'Ó Maolchomadh',
    'Mulvagh': 'Ó Maoilmheá',
    'O Mulvanaughty': 'Ó Maoilbheannachta',
    'Mulvanaughty': 'Ó Maoilbheannachta',
    'O Mulvane': 'Ó Maolbháin',
    'Mulvane': 'Ó Maolbháin',
    'Mulvanerton': 'O Maoibheannachta',
    'Mulvanerty': 'O Maoibheannachta',
    'O Mulvenna': 'Ó Maoilmheanna',
    'O Mulvanny': 'Ó Maoilmheanna',
    'Mulvenna': 'Ó Maoilmheanna',
    'Mulvanny': 'Ó Maoilmheanna',
    'O Mulvenna': 'Ó Maoilmhána',
    'O Mulvanny': 'Ó Maoilmhána',
    'Mulvenna': 'Ó Maoilmhána',
    'Mulvanny': 'Ó Maoilmhána',
    'O Mulveen': 'Ó Maoilmhin',
    'Mulveen': 'Ó Maoilmhin',
    'O Mulvennon': 'Ó Maoilbheanóin',
    'Mulvennon': 'Ó Maoilbheanóin',
    'O Mulvey': 'Ó Maoilmhiaigh',
    'Mulvey': 'Ó Maoilmhiaigh',
    'O Mulverhill': 'Ó Maoilmhichil',
    'O Mulvihill': 'Ó Maoilmhichil',
    'Mulverhill': 'Ó Maoilmhichil',
    'Mulvihill': 'Ó Maoilmhichil',
    'O Mulvin': 'Ó Maoilmhín',
    'Mulvin': 'Ó Maoilmhín',
    'O Mulvogue': 'Ó Maolmhaodhóg',
    'Mulvogue': 'Ó Maolmhaodhóg',
    'Mundan': 'Mac Giolla Eoin',
    'Munday': 'Mac Giolla Eoin',
    'O Mungavan': 'Ó Mongabháin',
    'Mungavan': 'Ó Mongabháin',
    'O Mungey': 'Ó Mongaigh',
    'Mungey': 'Ó Mongaigh',
    'Mungle': 'Mac Maongail',
    'Mac Munigal': 'Mac Maongail',
    'Munketterick': 'Mac Shitric',
    'Mac Munn': 'Mac Munna',
    'O Munnelly': 'Ó Maonaile',
    'Munnelly': 'Ó Maonaile',
    'Munroe': 'Mac an Róthaich',
    'Munster': 'Ó Muíneacháin',
    'O Murchan': 'Ó Murcháin',
    'Murchan': 'Ó Murcháin',
    'Murchie': 'Mac Murchaidh',
    'Murchison': 'Mac Murchaidh',
    'O Murchoe': 'Ó Murchú',
    'Murchoe': 'Ó Murchú',
    'Murdock': 'Mac Muireartaigh',
    'Murdoch': 'Mac Muireartaigh',
    'Murdy': 'Mac Muireartaigh',
    'Murdow': 'Mac Muireartaigh',
    'Mac Murdy': 'Mac Muireartaigh',
    'Murley': 'Ó Murthuile',
    'Murhilla': 'Ó Murthuile',
    'Murkin': 'Ó Murcháin',
    'Mac Murland': 'Mac Muraláin',
    'Mac Murlan': 'Mac Muraláin',
    'Murland': 'Ó Muraláin',
    'O Murnaghan': 'Ó Muirneacháin',
    'Murnaghan': 'Ó Muirneacháin',
    'O Murnane': 'Ó Murnáin',
    'Murnane': 'Ó Murnáin',
    'Murney': 'Ó Morna',
    'Mac Murran': 'Mac Móráin',
    'O Murphy': 'Mac Murchaidh Ó Murchú',
    'Murphy': 'Mac Murchaidh Ó Murchú',
    'O Murrane': 'Ó Muireáin',
    'O Murran': 'Ó Muireáin',
    'Murrane': 'Ó Muireáin',
    'Murran': 'Ó Muireáin',
    'Mac Murray': 'Mac Muirí',
    'O Murray': 'Ó Muirí',
    'Murray': 'Ó Muirí',
    'O Murready': 'Ó Maoilbhríde',
    'Murready': 'Ó Maoilbhríde',
    'Murrer': 'Ó Muirir',
    'O Murrigan': 'Ó Muireagáin',
    'O Murricane': 'Ó Muireagáin',
    'Murrigan': 'Ó Muireagáin',
    'Murricane': 'Ó Muireagáin',
    'Murricohu': 'Ó Murchú',
    'Murrihy': 'Ó Muirithe',
    'O Murrin': 'Ó Muireáin',
    'Murrin': 'Ó Muireáin',
    'O Murroney': 'Ó Maolruanaidh',
    'Murroney': 'Ó Maolruanaidh',
    'Mac Murrough': 'Mac Murchú',
    'Murrough': 'Mac Murchú',
    'Mac Murrough Kavanagh': 'Mac Murchú Caomhánach',
    'Murrow': 'Mac Murchú',
    'Murta': 'Mac Muireartaigh',
    'Murt': 'Mac Muireartaigh',
    'Murtagh': 'Mac Muireartaigh',
    'O Murtagh': 'Ó Muireartaigh',
    'Murtagh': 'Ó Muireartaigh',
    'Mac Murtery': 'Mac Muireartaigh',
    'Murtland': 'Mac Muraláin',
    'Mustay': 'Ó Maoilsté',
    'Myall': 'Ó Maoilmhichil',
    'Myers': 'Ó Mír',
    'Myhan': 'Ó Miacháin',
    'Myhill': 'Ó Maoilmhichil',
    'O Mylan': 'Ó Maoileáin',
    'Mylan': 'Ó Maoileáin',
    'Myler': 'Mac Maoilir',
    'Myles': 'Ó Maolmhuire',
    'Mylett': 'Méalóid',
    'Mynahan': 'Ó Muíneacháin',
    'Myniter': 'Minitéir',
    'Myres': 'Ó Mír',

}