module.exports = {
    'Mac Nabb': 'Mac an Aba',
    'Mac Naboe': 'Mac Anabaí',
    'Mac Naboola': 'Mac Con na Búille',
    'O Naughton': 'Ó Neachtain',
    'O Naghten': 'Ó Neachtain',
    'Naughton': 'Ó Neachtain',
    'Naghten': 'Ó Neachtain',
    'Nagel': 'de Nógla',
    'Nagle': 'de Nógla',
    'Nagle': 'Mac an Oglaoich',
    'Neill': 'Ó Néill',
    'Nail': 'Ó Néill',
    'Mac Nern': 'Mac an Airchinn',
    'Mac Nairn': 'Mac an Airchinn',
    'Mac Nairney': 'Mac an Airchinnigh',
    'Naish': 'de Nais',
    'Nash': 'de Nais',
    'Neale': 'Ó Néill',
    'Nale': 'Ó Néill',
    'Mac Nall': 'Mac Conuladh',
    'Nallen': 'Mac Nailín',
    'Mac Nally': 'Mac an Fhailí',
    'Mac Nalty': 'Mac Conallta',
    'Mac Nama': 'Mac Conmidhe',
    'Mac Namara': 'Mac Conmara',
    'Mca Namee': 'Mac Con Midhe',
    'Nanany': 'Mac Conaonaigh',
    'Nangle': 'de Nógla',
    'Nannery': 'Mac Náraigh',
    'Nary': 'Ó Náraigh',
    'Nash': 'de Nais',
    'Nathan': 'Ó Náthan',
    'Nawn': 'Ó Náthan',
    'Nahan': 'Ó Náthan',
    'Mac Naught': 'Mac Neachtain',
    'Mac Naughtan': 'Mac Neachtain',
    'Naughtan': 'Mac Neachtain',
    'Mac Naughter': 'Mac Conchúir',
    'Naughter': 'Mac Conchúir',
    'Mac Naul': 'Mac Conuladh',
    'Mac Naulty': 'Mac Conallta',
    'Naulty': 'Mac Conallta',
    'Mac Navan': 'Mac Cnáimhín',
    'Navan': 'Mac Cnáimhín',
    'Natton': 'Mac Neachtain',
    'Mac Nea': 'Mac Nia',
    'Mac Neagh': 'Mac Né',
    'Mac Nea': 'Mac Né',
    'Neagh': 'Mac Né',
    'Nea': 'Mac Né',
    'Neagle': 'de Nógla',
    'Neale': 'Mac Néill',
    'Nealis': 'Mac Niallais',
    'Mac Neally': 'Mac an Fhile',
    'Nealon': 'Ó Nialláin',
    'Mac Neany': 'Mac Conaonaigh',
    'Neaphsy': 'Ó Cnáimhsí',
    'Mac Neary': 'Mc Náraigh',
    'O Neary': 'Ó Náraigh',
    'Neary': 'Ó Náraigh',
    'Neavin': 'Mac Cnáimhín',
    'Mac Nee': 'Mac Né',
    'O Nee': 'Ó Nia',
    'Nee': 'Ó Nia',
    'Mac Neece': 'Mac Naois',
    'Neecy': 'Ó Cnáimhsí',
    'Needham': 'Ó Nia',
    'Neehan': 'Ó Niatháin',
    'Neelands': 'Ó Niallain',
    'Neeland': 'Ó Niallain',
    'O Neenan': 'Ó Naíonáin',
    'Neenan': 'Ó Naíonáin',
    'Neeson': 'Mac Aonasa',
    'Nehill': 'Ó Neighill',
    'Mac Neigh': 'Mac Né',
    'Neight': 'Mac Neachtain',
    'Mac Neilage': 'Mac Niallais',
    'Neiland': 'Ó Nialláin',
    'Neilan': 'Ó Nialláin',
    'Mac Neill': 'Mac Néill',
    'O Neill': 'Ó Néill',
    'Neill': 'Ó Néill',
    'Mac Neilly': 'Mac an Fhile',
    'Neilly': 'Mac an Fhile',
    'Nelson': 'Mac Neighill',
    'Neilson': 'Mac Neighill',
    'Mac Neive': 'Mac Connuibh',
    'Neive': 'Mac Connuibh',
    'O Neligan': 'Ó Niallagáin',
    'Neligan': 'Ó Niallagáin',
    'Mac Nellis': 'Mac Niallais',
    'Nellis': 'Mac Niallais',
    'Mac Nelly': 'Mac Conaola',
    'Mac Neela': 'Mac Conaola',
    'Mc Nerland': 'Mac an Fhirléinn',
    'Mc Nerlin': 'Mac an Fhirléinn',
    'Nertney': 'Mac an Airchinnigh',
    'Mac Nespy': 'Mac an Easpaig',
    'Mac Nestor': 'Mac an Adhastair',
    'Nestor': 'Mac an Adhastair',
    'Mac Nestry': 'Mac an Aistrigh',
    'Nestry': 'Mac an Aistrigh',
    'Netterfield': 'de Neadraibhíol',
    'Netterville': 'de Neadraibhíol',
    'Neville': 'Ó Nia',
    'Mac Nevins': 'Mac Cnáimhin',
    'Mac Nevin': 'Mac Cnáimhin',
    'Nevin': 'Mac Cnáimhin',
    'Nevins': 'Mac Cnáimhin',
    'Newcombe': 'Ó Nia',
    'O Newells': 'Ó Tnúthail',
    'O Newell': 'Ó Tnúthail',
    'Newells': 'Ó Tnúthail',
    'Newell': 'Ó Tnúthail',
    'Newman': 'Nuaman',
    'Newman': 'Ó Nuanáin',
    'Newton': 'Ó Nútáin',
    'O Neyland': 'Ó Nialláin',
    'O Neylan': 'Ó Nialláin',
    'Neyland': 'Ó Nialláin',
    'Neylan': 'Ó Nialláin',
    'Mac Nicholas': 'Mac Niocláis',
    'Mac Nicholls': 'Mac Niocáill',
    'Mac Nicholl': 'Mac Niocáill',
    'Nicholls': 'Mac Niocáill',
    'Nicholl': 'Mac Niocáill',
    'Mac Niece': 'Mac Naois',
    'Nielson': 'Mac Neighill',
    'Mac Niffe': 'MacConnuibh',
    'Night': 'Mac Neachtain',
    'O Nihan': 'Ó Niatháin',
    'Nihan': 'Ó Niatháin',
    'Nihill': 'Ó Neighill',
    'O Niland': 'Ó Nialláin',
    'O Nilan': 'Ó Nialláin',
    'Niland': 'Ó Nialláin',
    'Nilan': 'Ó Nialláin',
    'Mac Nilly': 'Mac an Fhile',
    'Mac Ninch': 'Mac Aonais',
    'Nirney': 'Mac an Airchinnigh',
    'Mac Nish': 'Mac Aonais',
    'Mac Nix': 'Mac Niocais',
    'Nix': 'Mac Niocais',
    'Nixon': 'Mac Nic',
    'O Noakley': 'Ó Neothallaigh',
    'Noakley': 'Ó Neothallaigh',
    'Nocher': 'Mac Conchúir',
    'Nocter': 'Ó Conchúir',
    'Nocker': 'Ó Conchúir',
    'Nocton': 'Ó Neachtain',
    'Nogher': 'Mac Conchúir',
    'Noghar': 'Mac Conchúir',
    'Nohilly': 'Ó Neothallaigh',
    'Nohally': 'Ó Neothallaigh',
    'Knowlan': 'Ó Nualláin',
    'Nolan': 'Ó Nualláin',
    'O Noland': 'Ó Nualláin',
    'O Nolans': 'Ó Nualláin',
    'Nolans': 'Ó Nualláin',
    'Noland': 'Ó Nualláin',
    'O Noonan': 'Ó Nuanáin',
    'Noonan': 'Ó Nuanáin',
    'O Noone': 'Ó Nuáin',
    'Noone': 'Ó Nuáin',
    'O Nooney': 'Ó hIonúine',
    'Nooney': 'Ó hIonúine',
    'Mac Normoyle': 'Mac Conormaoile',
    'Mac Normile': 'Mac Conormaoile',
    'Normile': 'Mac Conormaoile',
    'Normoyle': 'Mac Conormaoile',
    'Norris': 'Noiréis',
    'North': 'Ultach',
    'North': 'Noiréis',
    'Northridge': 'Noiréis',
    'Norton': 'Ó Neachtain',
    'Norway': 'de Noraidh',
    'Mac Noud': 'Mac Nuad',
    'O Nowd': 'Ó Nuad',
    'O Noud': 'Ó Nuad',
    'Nowd': 'Ó Nuad',
    'Noud': 'Ó Nuad',
    'Noughton': 'Ó Neachtain',
    'Nowry': 'de Noraidh',
    'Noury': 'de Noraidh',
    'Mac Nuff': 'Mac Connuibh',
    'Nugent Nuinseann': 'Mag Uinseannáin',
    'Mac Nully': 'Mac Conuladh',
    'Mac Nulty': 'Mac an Ultaigh',
    'Nulty': 'Mac an Ultaigh',
    'O Noonan': 'Ó Nuanáin',
    'O Nunan': 'Ó Nuanáin',
    'Noonan': 'Ó Nuanáin',
    'Nunan': 'Ó Nuanáin',
    'Nurse': 'Noiréis',
    'Nourse': 'Noiréis',
    'Mac Nutt': 'Mac Nuat',
    'Nutt': 'Mac Nuat',
    'O Nyhane': 'O Niatháin',
    'O Nyhan': 'O Niatháin',
    'Nyhane': 'O Niatháin',
    'Nyhan': 'O Niatháin',
    'Nyland': 'Ó Nialláin',
    'Nyhill': 'Ó Neighill',
    'Nynan': 'Ó Naíonáin'
}