module.exports = {
    'Oaks': 'Mac Darach',
    'Oak': 'Mac Darach',
    'Oats': 'Ó Coirc',
    'Ogan': 'Úgáin',
    'Ogilvy': 'Mac Giolla Bhuí',
    'Ogle': 'de Nógla',
    'Oliffe': 'Mac Amhlaoibh',
    'Oliver': 'Oilibhéar',
    'Olligan': 'Ó hAileacháin',
    'Olus': 'Ó hEolasa',
    'Oogan': 'Úgán',
    'Oolahan': 'Ó hUallacháin',
    'Oonin': 'Ó hUaithnín',
    'Orchard': 'Áirséir',
    'Organ': 'Ó hArgáin',
    'Ormond': 'Ó Rua',
    'Ormsby': 'Armas',
    'Mac Oscar': 'Mac Oscair',
    'Mac Ostrich': 'Mac Osraic',
    'Oswell': 'Ó hEosa',
    'Mac Oubrey': 'Mac Cúibreith',
    'Ounihan': 'Ó hOnchon',
    'Mac Owen': 'Mac Eoghain',
    'Owens': 'Ó hEoghain',
    'Owen': 'Ó hEoghain',
}