module.exports = {
    'Mac Padin': 'Mac Páidín'
    'Mac Padden': 'Mac Páidín'
    'Padin': 'Mac Páidín'
    'Padden': 'Mac Páidín'
    'Paine': 'Paghan'
    'Paisley: 'Paislig': Péaslaí'
    'Pallas': 'Pailís'
    'Palmer': 'Ó Maolómhair'
    'Panneen': 'Painín'
    'Parill': 'Pearail'
    'Parish': 'de Páiris'
    'Parker': 'Páircéir'
    'Parkins': 'Mac Peáircín'
    'Parkinson': 'Mac Peáircín'
    'Parle': 'Pearail'
    'Parlon': 'Mac Parthaláin'
    'Parrican': 'Mac Páraicín'
    'Parogan': 'Mac Páraicín'
    'Patrican': 'Mac Giolla Phádraig'
    'Patchy': 'Mac Giolla Phádraig'
    'Parrott': 'Pearóid'
    'Parsons': 'Mac an Phearsúin'
    'Mac Partland': 'Mac Parthaláin'
    'Mac Partlan': 'Mac Parthaláin'
    'Partland': 'Mac Parthaláin'
    'Partlan': 'Mac Parthaláin'
    'Patchy': 'Mac Giolla Phádraig'
    'Patten': 'Ó Peatáin'
    'Paton': 'Ó Peatáin'
    'Patrician': 'Mac Pháraicín'
    'Patrick': 'Ó Maolphádraig'
    'Patten': 'Ó Peatáin'
    'Patterson': 'Mac Pháidín'
    'Pattinson': 'Mac Pháidín'
    'Mac Paul': 'Ó Maolábhail'
    'Paul': 'Ó Maolábhail'
    'Paulett': 'Póiléid'
    'Paulson': 'Mac Póil'
    'Payne': 'Paghan'
    'Payton': 'Ó Peatáin'
    'Peacock': 'Péacóg'
    'Mac Peake': 'Mac Péice'
    'Peake': 'Mac Péice'
    'Pierce': 'Mac Piarais'
    'Pearse': 'Mac Piarais'
    'Pearson': 'Mac Piarais'
    'Peck': 'Ó Béice'
    'Pedian': 'Mac Páidín'
    'Peden': 'Mac Páidín'
    'Peelan': 'Ó Faoláin'
    'Pegum': 'Péagam'
    'Pembroke': 'Piombróg'
    'Penders': 'Piondar'
    'Pender': 'Piondar'
    'Pendeville': 'de Prionnbhíol'
    'Pentony': 'Mac Antaine'
    'Peoples': 'Ó Duibhne'
    'Peebles': 'Ó Duibhne'
    'Pepper': 'Piobart'
    'Peppard': 'Piobart'
    'Perkins': 'Mac Peáircín'
    'Perrott': 'Pearóid'
    'Perry': 'de Poire'
    'Peterson': 'Mac Pheadair'
    'Peters': 'Mac Pheadair'
    'Petite': 'Peitíd'
    'Petit': 'Peitíd'
    'Peyton': 'Ó Peatáin'
    'Mac Phail': 'Mac Pháil'
    'Phair': 'Mac Fhinn'
    'Fair': 'Mac Fhinn'
    'Pharis': 'Ó Fearais'
    'O Phelon': 'Ó Faoláin'
    'O Phelan': 'Ó Faoláin'
    'Phelon': 'Ó Faoláin'
    'Phelan': 'Ó Faoláin'
    'Mac Phelan': 'Mac Faoláin'
    'Phelim': 'Mac Feidhlim'
    'Mac Phelimy': 'Mac Feilimí'
    'Pherson': 'Mac an Phearsúin'
    'Mac Phettridge': 'Mac Pheadrais'
    'Phibbs': 'Mac Phib'
    'Philan': 'Ó Fialáin'
    'Mac Philbin': 'Mac Philbín'
    'Philbin': 'Mac Philbín'
    'Philips': 'Mac Philib'
    'Philipson': 'Mac Philib'
    'Phillipin': 'Mac Philibín'
    'Mac Philips': 'Mac Philib'
    'Philmey': 'Mac Feidhlimidh'
    'Philomy': 'Mac Feidhlimidh'
    'Philpin': 'Mac Philbín'
    'Philson': 'Mac Philib'
    'Phippen': 'Mac Phibín'
    'Phippson': 'Mac Phib'
    'Phipps': 'Mac Phib'
    'Phylan': 'Ó Faoláin'
    'Pidgeon': 'Mac Uiginn'
    'Pigeon': 'Mac Uiginn'
    'Pierse': 'Mac Piarais'
    'Pierce': 'Mac Piarais'
    'Pierson': 'Mac Piarais'
    'Pigeon': 'Mac Uiginn'
    'Pigot': 'Piogóid'
    'Piggott': 'Piogóid'
    'Pillin': 'Pilin'
    'Pike': 'Píc'
    'Pyke': 'Píc'
    'Pike': 'Mac Péice (Ulaidh)'
    'Pimley': 'Mac Feidhlimidh'
    'Piper': 'Piobaire'
    'Pipper': 'Piobaire'
    'Pirrie': 'de Poire'
    'Plover': 'Mac Philibín'
    'Plunket': 'Pluincéid'
    'Plunkett': 'Pluincéid'
    'le Poer': 'de Paor'
    'Poer': 'de Paor'
    'Mac Polin': 'Mac Póilín'
    'Mac Poland': 'Mac Póilín'
    'Polin': 'Mac Póilín'
    'Poland': 'Mac Póilín'
    'Mac Polin': 'Mac Póilín'
    'Pollard': 'Polard'
    'Pollen': 'Póilín'
    'Pollett': 'Póiléid'
    'Pollick': 'Polóc'
    'Pollock': 'Polóc'
    'Poison': 'Mac Póil'
    'Pomeroy': 'de Pomrae'
    'Pomroy': 'de Pomrae'
    'Poor': 'de Paor'
    'Portabello': 'Poirtingéil'
    'Porter': 'Póirtéir'
    'Potter': 'Potar'
    'Powderly': 'Púdarlaigh'
    'Powell': 'Mac Giolla Phóil'
    'Powel': 'Mac Giolla Phóil'
    'Power': 'de Paor'
    'Powlett': 'Póiléid'
    'Powlson': 'Mac Póil'
    'Poyne': 'Paghan'
    'Oyntz': 'Púinse'
    'Prate': 'de Prát'
    'Prat': 'de Prát'
    'Pray': 'a Préith'
    'Prendergast': 'de Priondragás'
    'Prenderville': 'de Prionnbhíol'
    'Preston': 'Preastún'
    'Prey': 'a Préith'
    'Priall': 'Priodháil'
    'Priel': 'Priodháil'
    'Pryse': 'Prís'
    'Pryce': 'Prís'
    'Price': 'Prís'
    'Prichard': 'a Priocaird'
    'Prindergast': 'de Priondragás'
    'Prinderville': 'dePrionnbhíol'
    'Prior': 'Mac an Phríora'
    'Pritchard': 'a Phristeaird'
    'Prout': 'Prút'
    'Prunty': 'Ó Prionntaigh'
    'Pryall': 'Príodháil'
    'Pryle': 'Príodháil'
    'Pryse': 'Prís'
    'Pryce': 'Prís'
    'Punch': 'Púinse'
    'Purcell': 'Puirséil'
    'Pursell': 'Puirséil'
    'Purtill': 'Puirséil'
    'Pyke': 'Píc'
    'Pyne': 'Paghan'
    'Pyper': 'Piobaire'
}