module.exports = {
    'Qua': 'Mac Uaid',
    'Mac Quaid': 'Mac Uaid',
    'Mac Quade': 'Mac Uaid',
    'Quaid': 'Mac Uaid',
    'Quade': 'Mac Uaid',
    'Quayle': 'Mac Fhail',
    'Quail': 'Mac Fhail',
    'Quaine': 'Ó Cuain',
    'Qualey': 'Ó Caollaí',
    'Qualter': 'Mac Ualtair',
    'Qualters': 'Mac Ualtair',
    'O Quane': 'Ó Cuain',
    'O Quan': 'Ó Cuain',
    'Quane': 'Ó Cuain',
    'Quan': 'Ó Cuain',
    'Quaney': 'Ó Maolchaoine',
    'Quaney': 'Mac Shuibhne',
    'Mac Quarry': 'Mac Guaire',
    'Quarry': 'Mac Guaire',
    'Mac Watt': 'Mac Uait',
    'Mac Quatt': 'Mac Uait',
    'Watt': 'Mac Uait',
    'Quatt': 'Mac Uait',
    'Mac Quatters': 'Mac Uaitéir',
    'Mac Quatter': 'Mac Uaitéir',
    'Quay': 'Mac Aodha',
    'Queale': 'Quail' 
    'O Queally': 'Ó Caollaí',
    'Queally': 'Ó Caollaí',
    'Quee': 'Mac Aoidh',
    'Queelty': 'Ó Caoilte',
    'Mac Queen': 'Mac Shuibhne',
    'O Queenan': 'Ó Cuineáin',
    'Queenan': 'Ó Cuineáin',
    'Mac Queeney': 'Mac Shuibhne',
    'Mac Queen': 'Mac Shuibhne',
    'Quick': 'Ó Coirc',
    'Querk': 'Ó Coirc',
    'Mac Question': 'Mac Úistín',
    'Mac Quiston': 'Mac Úistín',
    'Question': 'Mac Úistín',
    'Quiston': 'Mac Úistín',
    'Quey': 'Mac Aodha',
    'Quay': 'Mac Aodha',
    'O Quiddihy': 'Ó Cuidithe',
    'Quiddihy': 'Ó Cuidithe',
    'O Quigg': 'Ó Cuaig',
    'Quigg': 'Ó Cuaig',
    'Mac Quiggin': 'Mac Guaigín',
    'O Quigley': 'Ó Coigligh',
    'Quigley': 'Ó Coigligh',
    'Quigney': 'Ó Coigligh',
    'Quilkin': 'Mac Ulcín',
    'O Quill': 'Ó Coill',
    'Quill': 'Ó Coill',
    'Mac Quillan': 'Mac Uilín',
    'O Quillenane': 'Ó Cuileannáin',
    'Quillenane': 'Ó Cuileannáin',
    'Quilliam': 'Mac Uiliam',
    'O Quilligan': 'Ó Cuileagáin',
    'Quilligan': 'Ó Cuileagáin',
    'Mac Quilly': 'Mac an Choiligh',
    'Quilter': 'Cuiltéir',
    'O Quilty': 'Ó Caoilte',
    'Quilty': 'Ó Caoilte',
    'O Quinane': 'Ó Cinneáin',
    'Quinane': 'Ó Cinneáin',
    'O Quinlan': 'Ó Caoinnealáin',
    'Quinlan': 'Ó Caoinnealáin',
    'O Quinlan': 'Ó Caoinleáin',
    'Quinlan': 'Ó Caoinleáin',
    'O Quinlevan': 'Ó Caoinnealbháin',
    'Quinlevan': 'Ó Caoinnealbháin',
    'O Quinlish': 'Ó Cuinlis',
    'Quinlish': 'Ó Cuinlis',
    'Quinn': 'Ó Coinne (Ulaidh)',
    'Mac Quinn': 'Mac Coinn',
    'Mac Quin': 'Mac Coinn',
    'Quinn': 'Mac Coinn',
    'Quin': 'Mac Coinn',
    'O Quinn': 'Ó Coinn',
    'O Quin': 'Ó Coinn',
    'Quinn': 'Ó Coinn',
    'Quin': 'Ó Coinn',
    'Quinnell': 'Ó Coinnill',
    'O Quinnelly': 'Ó Coinneallaigh',
    'Quinnelly': 'Ó Coinneallaigh',
    'Mac Quinnelly': 'Mac Coinneallaigh',
    'Quinnelly': 'Mac Coinneallaigh',
    'O Quinney': 'Ó Coinne',
    'Quinney': 'Ó Coinne',
    'Mac Quinney': 'Mac Shuibhne',
    'Mac Quinniff': 'Mac Connuibh',
    'Quinniff': 'Mac Connuibh',
    'Quirke': 'Ó Coirc',
    'Quirk': 'Ó Coirc',
    'Mac Quish': 'Mac Coise',
    'Quish': 'Ó Coise',
    'Mac Quitty': 'Mac Faoitigh',
    'Quoid': 'Mac Uaid',
}