module.exports = {
    'Rabbit': 'Ó Coinín',
    'Rabbitt': 'Ó Coinín',
    'Rackard': 'Mac Riocaird',
    'O Ractigan': 'Ó Rachtagáin',
    'Ractigan': 'Ó Rachtagáin',
    'Mac Rae': 'Mac Raith',
    'Rae': 'Mac Raith',
    'Rafe': 'Ráulbh',
    'O Rafferty': 'Ó Raifeartaigh',
    'Rafferty': 'Ó Raifeartaigh',
    'O Raftiss': 'Ó Reachtair',
    'O Rafter': 'Ó Reachtair',
    'Raftiss': 'Ó Reachtair',
    'Rafter': 'Ó Reachtair',
    'O Raftery': 'Ó Reachtaire',
    'Raftery': 'Ó Reachtaire',
    'Ragget': 'Raghat',
    'Rahenny': 'Ó Raithne',
    'Raher': 'Ó Reachair',
    'Mac Raghteen': 'Mac Raichtín',
    'O Rahill': 'Ó Rághaill',
    'Rahill': 'Ó Rághaill',
    'O Rahilly': 'Ó Raithile',
    'Rahilly': 'Ó Raithile',
    'Raikes': 'Ó hAnracháin',
    'Rails': 'Ó Rághaill',
    'Rail': 'Ó Rághaill',
    'Rainey': 'Ó Ráine',
    'Raleigh': 'Rálaigh',
    'Ralf': 'Ráuibh',
    'Rall': 'Ó Ráill',
    'Rally': 'Ó Rállaigh',
    'Ramsey': 'Ramsaigh',
    'Ranaghan': 'Ó Reannacháin',
    'Randall': 'Randal',
    'Randalson': 'Mac Ránaill',
    'Randals': 'Mac Ránaill',
    'Raney': 'Ó Ráine',
    'Rankin': 'Mac Raing',
    'Mac Rann': 'Mac Bhrain',
    'Mac Rannal': 'Mac Ránaill',
    'Ranny': 'Ó Raithne',
    'Ranolds': 'Mac Ránaill',
    'Ratchford': 'de Rosfort',
    'Rashford': 'de Rosfort',
    'Rath': 'de Ráth',
    'O Ratigan': 'Ó Reachtagáin',
    'Ratigan': 'Ó Reachtagáin',
    'Ratty': 'Ó hAnrachtaigh',
    'Raverty': 'Ó Rabhartaigh',
    'Ravery': 'Ó Raifearthaigh',
    'Ravey': 'Ó Riabhaigh',
    'O Rawe': 'Ó Rímheá',
    'Rawe': 'Ó Rímheá',
    'Rawley': 'Rálaigh',
    'Ray': 'Ó Riabhaigh',
    'Rayhill': 'Ó Raghaill',
    'Raymond': 'Réamann',
    'Raynard': 'Raghnard',
    'Rea': 'Ó Riabhaigh',
    'Reade': 'Ó Maoildeirg',
    'Read': 'Ó Maoildeirg',
    'Readdy': 'Ó Riada',
    'Ready': 'Ó Riada',
    'Reagh': 'Riabhach',
    'Real': 'Roghaill',
    'Ryle': 'Roghaill',
    'Realy': 'Ó Raghailligh',
    'O Reaney': 'Ó Ráine',
    'Reaney': 'Ó Ráine',
    'Reap': 'Ó Réabaigh',
    'O Reardan': 'Ó Riordáin',
    'Reardan': 'Ó Riordáin',
    'O Reavey': 'Ó Riabhaigh',
    'Reavey': 'Ó Riabhaigh',
    'Mac Reavy': 'Mac Riabhaigh',
    'Reavy': 'Mac Riabhaigh',
    'Reckle': 'Ó Raigill',
    'O Reckle': 'Ó Reighill',
    'Reckle': 'Ó Reighill',
    'O Redhan': 'Ó Roideacháin',
    'Redhan': 'Ó Roideacháin',
    'O Reddan': 'Ó Rodáin',
    'Reddan': 'Ó Rodáin',
    'O Reddan': 'Ó Roideáin',
    'Reddan': 'Ó Roideáin',
    'Reddington': 'Ó Maoildeirg',
    'Reddy': 'Ó Roidigh',
    'Redmond': 'Réamonn Séan Réamonn',
    'Mac Redmond': 'Mac Réamainn',
    'Redmond': 'Mac Réamainn',
    'Mac Redmon': 'Mac Réamainn',
    'Redmon': 'Mac Réamainn',
    'Redican': 'Ó Roideacháin',
    'Reede': 'Ó Maoildeirg',
    'Reed': 'Ó Maoildeirg',
    'Mac Reedy': 'Mac Riada',
    'Reedy': 'Mac Riada',
    'O Reel': 'Ó Raghaill',
    'Reel': 'Ó Raghaill',
    'Reely': 'Raghailligh',
    'Reen': 'Ó Rinn',
    'Reeves': 'Ó Rímheá',
    'O Regan': 'Ó Riagáin',
    'Regan': 'Ó Riagáin',
    'Rehan': 'Ó Criocháin',
    'Reid': 'Ó Maoildeirg',
    'O Reidy': 'Ó Riada',
    'Reidy': 'Ó Riada',
    'Reigh': 'Ó Riabhaigh',
    'Reighill': 'Ó Raghaill',
    'Reighill': 'Ó Reighill',
    'Reihill': 'Ó Reighill',
    'Reighney': 'Mac Raighne',
    'Rellis': 'Mag Riallais',
    'Relis': 'Mag Riallais',
    'O Reilly': 'Ó Raghallaigh',
    'Reilly': 'Ó Raghallaigh',
    'O Reilly': 'Ó Raghailligh',
    'Reilly': 'Ó Raghailligh',
    'O Reiny': 'Ó Raighne',
    'Reiny': 'Ó Raighne',
    'O Relehan': 'Ó Roileacháin',
    'Relehan': 'Ó Roileacháin',
    'Rellis': 'Mac Riallais',
    'Renaghan': 'Ó Reannacháin',
    'Renan': 'Ó Maoilbhréanainn',
    'Renard': 'Raghnard',
    'Renken': 'Mac Raing',
    'Renilson': 'Mac Ránaill',
    'Rennie': 'Ó Raighne',
    'Renolds': 'Mac Ránaill',
    'Reordan': 'Ó Ríordáin',
    'Restrick': 'Raistric',
    'Rastrick': 'Raistric',
    'Reville': 'Roibheal',
    'Rewan': 'Ó Ruáin',
    'Reynalds': 'Mac Ránaill',
    'Reynard': 'Raghnard',
    'Reynolds': 'Mac Ránaill',
    'Reynoldson': 'Mac Ránaill',
    'Rhategan': 'Ó Reachtagáin',
    'Riach': 'Riabhach',
    'Riall': 'Ó Raghaill',
    'Ribbon': 'Ó Roibín',
    'Rice': 'Ó Maolchraoibhe',
    'Rhys': 'Rís',
    'Rice': 'Rís',
    'Richardson': 'Mac Risteaird',
    'Richards': 'Mac Risteaird',
    'Richmond': 'de Riseamann',
    'Rickards': 'Mac Ricéid',
    'Rickard': 'Mac Ricéid',
    'Ricketson': 'Mac Ricéid',
    'Rickets': 'Mac Ricéid',
    'Riddell': 'Rideal',
    'Ridge': 'Mac Iomaire',
    'Mac Rifferty': 'Mac Rifeartaigh',
    'Rigley': 'Ó Raigilligh',
    'O Rigney': 'Ó Roigne',
    'Rigney': 'Ó Roigne',
    'O Rinaghan': 'Ó Reannacháin',
    'Rinaghan': 'Ó Reannacháin',
    'O Riney': 'Ó Raighne',
    'Riney': 'Ó Raighne',
    'O Ring': 'Ó Rinn',
    'Ring': 'Ó Rinn',
    'Rinn': 'Ó Rinn',
    'Mac Rinn': 'Mac Bhroin',
    'Rinn': 'Mac Bhroin',
    'O Reardan': 'Ó Ríordáin',
    'O Riordan': 'Ó Ríordáin',
    'Reardan': 'Ó Ríordáin',
    'Riordan': 'Ó Ríordáin',
    'Mac Ritchie': 'Mac Riocaird',
    'Roache': 'de Róiste',
    'Roane': 'Ó Ruáin',
    'Roan': 'Ó Ruáin',
    'Roantree': 'O Caorthannáin',
    'O Roarke': 'Ó Ruairc',
    'O Roark': 'Ó Ruairc',
    'Roarke': 'Ó Ruairc',
    'Roark': 'Ó Ruairc',
    'Mac Roarty': 'Mac Robhartaigh',
    'Roarty': 'Mac Robhartaigh',
    'O Roarty': 'Ó Robhartaigh',
    'Roarty': 'Ó Robhartaigh',
    'Mac Robin': 'Mac Roibín',
    'Mac Robbin': 'Mac Roibín',
    'Robbins': 'Mac Roibín',
    'Robbinson': 'Mac Roibín',
    'Robb': 'Mac Rob',
    'Robbs': 'Mac Rob',
    'Robert': 'Roibeard',
    'Roberts': 'Mac Roibeaird',
    'Robertson': 'Mac Roibeaird',
    'Robinson': 'Mac Roibín',
    'Robson': 'Mac Rob',
    'Roche': 'de Róiste',
    'Rochefort': 'de Rosfort',
    'Rochneen': 'Ó Reachtnín',
    'Rocks': 'Mac Concharraige',
    'Rock': 'Mac Concharraige',
    'O Rodden': 'Ó Rodáin',
    'O Roden': 'Ó Rodáin',
    'Rodden': 'Ó Rodáin',
    'Roden': 'Ó Rodáin',
    'O Roddy': 'Ó Rodaigh',
    'Roddy': 'Ó Rodaigh',
    'O Rodehan': 'Ó Rodacháin',
    'Rodehan': 'Ó Rodacháin',
    'Rodgers': 'Mac Ruairí',
    'Rodger': 'Mac Ruairí',
    'Rodmont': 'Rodhmann',
    'Roe': 'Ó Rua',
    'O Rogan': 'Ó Ruagáin',
    'Rogan': 'Ó Ruagáin',
    'Rogerson': 'Mac Ruairí',
    'Rogers': 'Mac Ruairí',
    'O Rohan': 'Ó Ruacháin',
    'Rohan': 'Ó Ruacháin',
    'O Roland': 'Ó Rothláin',
    'O Rolan': 'Ó Rothláin',
    'Roland': 'Ó Rothláin',
    'Rolan': 'Ó Rothláin',
    'Rolf': 'Rodhulbh',
    'O Ronaghan': 'Ó Reannacháin',
    'Ronaghan': 'Ó Reannacháin',
    'Ronaldson': 'Mac Ránaill',
    'Ronalds': 'Mac Ránaill',
    'O Ronayne': 'Ó Rónáin',
    'O Ronan': 'Ó Rónáin',
    'Ronayne': 'Ó Rónáin',
    'Ronan': 'Ó Rónáin',
    'Rone': 'Ó Ruáin',
    'Roney': 'Ó Ruanaidh',
    'O Rohan': 'O Ruacháin',
    'O Roohan': 'O Ruacháin',
    'Roohan': 'Ruacháin',
    'Rohan': 'Ruacháin',
    'Rooke': 'Ó Ruairc',
    'Roon': 'Ó Ruáin',
    'Roonan': 'Ó Ruanaín',
    'O Rooneen': 'Ó Ruanaín',
    'Rooneen': 'Ó Ruanaín',
    'O Rooney': 'Ó Ruanaidh',
    'Rooney': 'Ó Ruanaidh',
    'Roonoo': 'Ó Ruandha',
    'O Rorke': 'Ó Ruairc',
    'Rorke': 'Ó Ruairc',
    'Mac Rory': 'Mac Ruairí',
    'Rory': 'Ruirí',
    'Rose': 'Rós',
    'O Rosney': 'Ó Rosna',
    'Rosney': 'Ó Rosna',
    'Ross': 'Rosach',
    'Rossiter': 'Rosaitear',
    'Rostig': 'Róisteach',
    'Rothe': 'Rút',
    'Roth': 'Rút',
    'Rounane': 'Ó Ruáin',
    '(O0 Roughan': 'Ó Ruacháin',
    'Roughasy': 'Ó Rughasa',
    'O Roughneen': 'Ó Reachtnín',
    'Roughneen': 'Ó Reachtnín',
    'O Rouine': 'Ó Ruaáin',
    'Rouine': 'Ó Ruaáin',
    'Rountree': 'Ó Caorthannáin',
    'O Rourke': 'Ó Ruairc',
    'Rourke': 'Ó Ruairc',
    'Routh': 'Rút',
    'Rowan': 'Ó Ruáin',
    'Rowe': 'Ó Rua',
    'Roe': 'Ó Rua',
    'Rowen': 'Ó Ruaín',
    'Rowland': 'Ó Rothláin',
    'Rowlan': 'Ó Rothláin',
    'Rowley': 'Ó Rothláin',
    'Rowney': 'Ó Ruanaidh',
    'O Royan': 'Ó Ruáin',
    'Royan': 'Ó Ruáin',
    'Roy': 'Mac Rua',
    'Royce': 'Rice',
    'O Ruane': 'Ó Ruáin',
    'O Ruan': 'Ó Ruáin',
    'Ruane': 'Ó Ruáin',
    'Ruan': 'Ó Ruáin',
    'Ruarke': 'Ó Ruairc',
    'Mac Rub': 'Mac Rob',
    'Mac Ruba': 'Mac Rob',
    'Ruckston': 'Rucstún',
    'Rudden': 'Ó Rodáin',
    'Ruddle': 'Riodal',
    'Ruddal': 'Riodal',
    'Mac Ruddery': 'Mac an Ridire',
    'Ruddy': 'Ó Rodaigh',
    'Rudican': 'Ó Rodacháin',
    'Rudihan': 'Ó Rodacháin',
    'Mac Rum': 'Mac Croim',
    'Runey': 'Ó Ruanaidh',
    'de Rupe': 'de Róiste',
    'Rush': 'Ó Rois',
    'Rush': 'Ó Luachra ',
    'Rushford': 'de Rosfort',
    'Russell': 'Ruiséil',
    'Ruth': 'Rút',
    'Rutledge': 'Ó Maoildeirg',
    'Ruttle': 'Riodal',
    'O Ruvane': 'Ó Ruadháin',
    'Ruvane': 'Ó Ruadháin',
    'Ryall': 'Ó Raghaill',
    'O Ryan': 'Ó Riain',
    'Ryan': 'Ó Riain',
    'Ryder': 'Ó Marcaigh',
    'Mac Rynn': 'Mac Bhroin',
    'O Rynne': 'Ó Rinn',
    'O Rynn': 'Ó Rinn',
    'Rynne': 'Ó Rinn',
    'Rynn': 'Ó Rinn',
    'O Riall': 'Ó Raghaill',
    'O Ryle': 'Ó Raghaill',
    'Riall': 'Ó Raghaill',
    'Ryle': 'Ó Raghaill',
}