module.exports = {
    'Sage': 'Sabhaois',
    'St Clare': 'Sincléir',
    'St John': 'Suingean',
    'St Leger': 'Sailingéir',
    'Sall': 'deSál',
    'Sallinger': 'Sailingéir',
    'Salmon': 'Ó Bradáin',
    'Mac Sally': 'Mac Salaigh',
    'Sally': 'Mac Salaigh',
    'Sampson': 'Samsún',
    'Samson': 'Samsún',
    'Samuels': 'Mac Samuel',
    'Sandall': 'de Sandal',
    'Sanderson': 'Mac Sandair',
    'Sanders': 'Mac Sandair',
    'Sandys': 'Ó Seachnasaigh',
    'Sandes': 'Ó Seachnasaigh',
    'Sanford': 'de Sanfort',
    'Santry': 'de Seantrabh',
    'O Sarahan': 'Ó Soracháin',
    'Sarahan': 'Ó Soracháin',
    'Sargent': 'Sáirgeant',
    'Sarseil': 'Sáirséil',
    'Sarsfield': 'Sáirséil',
    'Saul': 'de Sál',
    'Saunderson': 'Mac Sandair',
    'Saunders': 'Mac Sandair',
    'Saurin': 'de Sabhrainn',
    'Sausheil': 'Sáiséil',
    'Savage': 'Sabhaois',
    'Savin': 'Ó Sabháin',
    'Sayers': 'Saoghar',
    'Sayer': 'Saoghar',
    'Scadding': 'Ó Scadáin',
    'Scaddan': 'Ó Scadáin',
    'Mac Schail': 'Mac Scaithil',
    'Mac Scahill': 'Mac Scaithil',
    'Schail': 'Mac Scaithil',
    'Scahill': 'Mac Scaithil',
    'O Scahill': 'Ó Scaithil',
    'Scahill': 'Ó Scaithil',
    'Scales': 'de Scéalas',
    'O Scallan': 'Ó Scealláin',
    'Scallan': 'Ó Scealláin',
    'Mac Scally': 'Mac Scalaí',
    'Scally': 'Mac Scalaí',
    'Scarnaton': 'Scamatún',
    'Mac Scanlan': 'Mac Scannláin (Lú)',
    'Scanlan': 'Mac Scannláin (Lú)',
    'O Scanlan': 'Ó Scannláin (Mumhain)',
    'Scanlan': 'Ó Scannláin (Mumhain)',
    'O Scannell': 'Ó Scannail',
    'Scannell': 'Ó Scannail',
    'Scurry': 'Ó Scurra',
    'Scarry': 'Ó Scurra',
    'Scholfield': 'Ó Scoful',
    'Scolard': 'Scolard',
    'Scollin': 'Ó Scolláin',
    'Scollan': 'Ó Scolláin',
    'Mac Scollog': 'Mac Scolóige',
    'Scott': 'Albanach',
    'Scott': 'Scot',
    'Scriven': 'de Scribhin',
    'Scuffil': 'Scoful',
    'O Skoolin': 'Ó Scolláin',
    'O Scullion': 'Ó Scolláin',
    'Skoolin': 'Ó Scolláin',
    'Scullion': 'Ó Scolláin',
    'O Scully': 'Ó Scolaí',
    'Scully': 'Ó Scolaí',
    'Scurlock': 'Scorlóg',
    'Scurry': 'Ó Scurra',
    'Sdundon': 'Stondún',
    'Seagrave (Seagrove)': 'de Saográbh',
    'Seares': 'Mac Saoghair (Ciarraí)',
    'Sear': 'Mac Saoghair (Ciarraí)',
    'Sayers': 'Saoghar',
    'Sear': 'Saoghar',
    'Searson': 'Mac Saoghair',
    'Seath': 'Mac Síthigh',
    'Seth': 'Mac Síthigh',
    'Seaver': 'Saomhar',
    'Seaward': 'Saobhard',
    'O Seery': 'Ó Saoraí',
    'Seery': 'Ó Saoraí',
    'Segrave': 'de Saograobh',
    'Segrue': 'Ó Siochrú',
    'Seix': 'Saghas',
    'Selinger': 'Sailingéir',
    'Semour': 'Saomar',
    'Semore': 'Saomar',
    'Sergeant': 'Sairgeant',
    'Mac Seveney': 'Mac Suibhne',
    'Seward': 'Ó Suaird',
    'Sewell': 'Ó Súiligh',
    'O Sexton': 'Ó Seasnáin',
    'Sexton': 'Ó Seasnáin',
    'Seymore': 'Saomar',
    'Mac Shaffrey': 'Mac Seafraigh',
    'Shaffrey': 'Mac Seafraigh',
    'Shahan': 'Ó Séacháin',
    'Sheils': 'Ó Siail',
    'Shails': 'Ó Siail',
    'Shairp': 'Ó Géaráin',
    'Shally': 'Ó Sealbhaigh',
    'Shalloe': 'Ó Sealbhaigh',
    'Shalvey': 'Ó Sealbhaigh',
    'Shamrock': 'Seamróg',
    'Mac Shan': 'Mac Seáin',
    'O Shanaghan': 'Ó Seanacháin',
    'Shanaghan': 'Ó Seanacháin',
    'O Shanagher': 'Ó Seanachair',
    'Shanagher': 'Ó Seanachair',
    'Mac Shanaghy': 'Mac Seancha',
    'Shanaghy': 'Mac Seancha',
    'Shanahan': 'Ó Seancháin',
    'Mac Shane': 'Mac Seáin',
    'Shanessy': 'Ó Seachnasaigh',
    'Mac Shanley': 'Mac Seanlaoich',
    'Shanley': 'Mac Seanlaoich',
    'Shannagh': 'Ó Seanaigh',
    'Mac Shannon': 'Mac Seanáin',
    'O Shannon': 'Ó Seanáin',
    'Shannon': 'Ó Seanáin',
    'Shanny': 'Ó Seanaigh',
    'Sharket': 'Ó Searcóid',
    'O Sharkey': 'Ó Searcaigh',
    'Sharkey': 'Ó Searcaigh',
    'Sharman': 'Searman',
    'Sharpe': 'Ó Géaráin',
    'Mac Sharry': 'Mac Searraigh',
    'Sharry': 'Mac Searraigh',
    'O Sharvin': 'Ó Searbháin',
    'Sharvin': 'Ó Searbháin',
    'O Shasnan': 'Ó Seasnáin',
    'Shasnan': 'Ó Seasnáin',
    'Shaughness': 'Ó Seachnais',
    'O Shaughnessy': 'Ó Seachnasaigh',
    'Shaughnessy': 'Ó Seachnasaigh',
    'Shaw': 'Seách',
    'Shaw': 'Mac Giolla Seathanaigh',
    'O Shea': 'Ó Sé',
    'Shea': 'Ó Sé',
    'Sheahan': 'Ó Síocháin',
    'Sheales': 'Ó Siail',
    'Sheals': 'Ó Siail',
    'Shealy': 'Ó Sealbhaigh',
    'Shean': 'Ó Síocháin',
    'Shearhoon': 'Mac Séarthúin',
    'Shearlock': 'Scorlóg',
    'Shearman': 'Searman',
    'Shee': 'Ó Sé',
    'Sheean': 'Ó Siocháin',
    'O Sheedy': 'Ó Síoda',
    'Sheedy': 'Ó Síoda',
    'Mac Sheedy': 'Mac Síoda',
    'O Sheehan': 'Ó Síocháin',
    'Sheehan': 'Ó Síocháin',
    'Mac Sheehy': 'Mac Síthigh',
    'Sheehy': 'Mac Síthigh',
    'Sheen': 'Ó Síocháin',
    'O Sheenan': 'Ó Sionáin (Tír Eoghain)',
    'Sheenan': 'Ó Sionáin (Tír Eoghain)',
    'Mac Shera': 'Mac Séartha',
    'Mac Sheera': 'Mac Séartha',
    'Shera': 'Mac Séartha',
    'Sheera': 'Mac Séartha',
    'O Sheeran': 'Ó Síoráin',
    'Sheeran': 'Ó Síoráin',
    'Shegrue': 'Ó Siochrú',
    'O Shehegane': 'Ó Seitheacháin',
    'Shehegane': 'Ó Seitheacháin',
    'Sheilds': 'Ó Siail',
    'O Sheilds': 'Ó Siail',
    'Sheil': 'Ó Siail',
    'O Sheil': 'Ó Siail',
    'Sheily': 'Ó Sealbhaigh',
    'Mac Shekish': 'Mac Siacais',
    'Shellew': 'Ó Sealbhaigh',
    'Shelloe': 'Ó Sealbhaigh',
    'Shelly': 'Ó Sealbhaigh',
    'Sheridan': 'Ó Sirideáin',
    'Sherdan': 'Ó Sirideáin',
    'Sherin': 'Ó Sírín',
    'Sherlock': 'Scorlóg',
    'Sherman': 'Searman',
    'Mac Sherry': 'Mac Searraigh',
    'Sherry': 'Mac Searraigh',
    'Sherwin': 'Ó Searbháin',
    'O Shevlin': 'Ó Seibhleáin',
    'Shevlin': 'Ó Seibhleáin',
    'O Shineagh': 'Ó Sionnaigh',
    'Shineagh': 'Ó Sionnaigh',
    'O Shine': 'Ó Seighin',
    'Shine': 'Ó Seighin',
    'Shinkwin': 'Sinicín',
    'Shinnahan': 'Ó Sionacháin',
    'Shinnan': 'Ó Sionáin',
    'Shilmick': 'Ó Sionnaigh',
    'Shinnock': 'Ó Sionnaigh',
    'Shinnors': 'Sionúir',
    'Shinnor': 'Sionúir',
    'Shinwick': 'Ó Sionnaigh',
    'Shinny': 'Ó Sionnaigh',
    'Shirdan': 'Ó Sirideáin',
    'Shortt': 'Mac an Gheairr',
    'Short': 'Mac an Gheairr',
    'Shortall': 'Soirtéil',
    'Shortle': 'Soirtéil',
    'Shorten': 'Seartáin',
    'Shortle': 'Soirtéil',
    'Shorthall': 'Soirtéil',
    'Shortice': 'Seortús',
    'Shortis': 'Seortús',
    'O Shovelin': 'Ó Seibhleáin',
    'Shovelin': 'Ó Seibhleáin',
    'Shoye': 'Seoigh',
    'O Shryhane': 'Ó Sraitheáin',
    'Shryhane': 'Ó Sraitheáin',
    'Mac Shufrey': 'Mac Seafraidh',
    'Shunny': 'Ó Sionnaigh',
    'Shughrue': 'Ó Siochrú',
    'Shurdáin': 'Ó Siordáin',
    'Sigerson': 'Mac Síoghair',
    'Siggins': 'Sigín',
    'Silke': 'Ó Síoda',
    'Silk': 'Ó Síoda',
    'Silver': 'Ó hAirgeadáin',
    'Simcox': 'Siomcóg',
    'Sinkins': 'Simicín',
    'Sinkin': 'Simicín',
    'Simmonds': 'Mac Síomóin',
    'Simmond': 'Mac Síomóin',
    'Simpkins': 'Simicín',
    'Simpkin': 'Simicín',
    'Simpson': 'Mac Shim',
    'Simson': 'Mac Shim',
    'Sims': 'Mac Shim',
    'Sinclair': 'Sincléir',
    'Singen': 'Suingean ',
    'Singleton': 'Ó Siondaile',
    'Singleton': 'de Singealtún',
    'Sinjohn': 'Suingean',
    'Sinnott': 'Sionóid',
    'Sitric': 'Mac Shitric',
    'Size': 'Saghas',
    'Seix': 'Saghas',
    'Skahill': 'Ó Scathail',
    'Skally': 'Ó Scalaí',
    'Scally': 'Ó Scalaí',
    'Skarkett': 'Ó Searcóid',
    'Skeaghan': 'Mac Sceacháin',
    'Mac Skeaghan': 'Mac Sceacháin',
    'Mac Skehan': 'Mac Sceacháin',
    'Skehan': 'Mac Sceacháin',
    'O Skehan': 'Ó Sceacháin',
    'Skehan': 'Ó Sceacháin',
    'Skeffington': 'Sceimhealtún',
    'Skelly': 'Ó Scealaí',
    'Skelton': 'de Scealtún',
    'Skerrett': 'Sciréid',
    'Skiddy': 'Scideach',
    'Scilling': 'Scillinn',
    'Skillen': 'Scillinn',
    'Mac Skimmins': 'Mac Cuimín',
    'Skimmins': 'Mac Cuimín',
    'Skinner': 'Scinéir',
    'O Skinnion': 'Ó Scingín',
    'Skinnion': 'Ó Scingín',
    'Skivington': 'Sceimhealtún',
    'Skoolin': 'Ó Scolláin',
    'Skryne': 'de Scrín',
    'Slamon': 'Ó Sléibhín',
    'Slane': 'de Sláine',
    'O Slattery': 'Ó Slatara',
    'Slattery': 'Ó Slatara',
    'O Slevin': 'Ó Sléibhín',
    'O Slavin': 'Ó Sléibhín',
    'Slevin': 'Ó Sléibhín',
    'Slavin': 'Ó Sléibhín',
    'Mac Sleyne': 'Mac Sleimhne',
    'Sleyne': 'Mac Sleimhne',
    'Mac Sliney': 'Mac Sleimhne',
    'O Sloane': 'Ó Sluáin',
    'O Sloan': 'Ó Sluáin',
    'Sloane': 'Ó Sluáin',
    'Sloan': 'Ó Sluáin',
    'Slocombe': 'Slócam',
    'Mac Sloy': 'Mac Sluaigh',
    'Mac Slowey': 'Mac Sluaigh',
    'O Sloy': 'Ó Sluaigh',
    'O Slowey': 'Ó Sluaigh',
    'Sloy': 'Ó Sluaigh',
    'Slowey': 'Ó Sluaigh',
    'Sloyan': 'Ó Sluáin',
    'Slone': 'Ó Sluáin',
    'Small': 'Ó Caoilte',
    'Smallen': 'Ó Spealáin Ó Smealláin',
    'Smallwoods': 'Mac Conchoillín',
    'Smart': 'Smeart',
    'Smeeth': 'Smíst',
    'Smiddy': 'Smidí',
    'Smith': 'Mac Gabhann',
    'Smithwick': 'Smidic',
    'Smullen': 'Ó Spealáin Ó Smolláin',
    'Smollan': 'Ó Spealáin Ó Smolláin',
    'Smyche': 'Smíst',
    'O Snee': 'Ó Sní',
    'Snee': 'Ó Sní',
    'O Snoddy': 'Ó Snodaigh',
    'Snoddy': 'Ó Snodaigh',
    'Snow': 'an tSneachta',
    'Soghlahan': 'Ó Sochlacháin',
    'O Solan': 'Ó Sochlacháin',
    'Solan': 'Ó Sochlacháin',
    'Mac Solly': 'Mac Soilligh',
    'Solly': 'Mac Soilligh',
    'Solomans': 'Mac Solaimh',
    'Soloman': 'Mac Solaimh',
    'O Somahán': 'Ó Somacháin',
    'Somahán': 'Ó Somacháin',
    'Somers': 'Ó Somacháin',
    'Somerville': 'Ó Somacháin',
    'Soolivan': 'Ó Súilleabháin',
    'O Soran': 'Ó Soracháin',
    'O Sorahan': 'Ó Soracháin',
    'Soran': 'Ó Soracháin',
    'Sorahan': 'Ó Soracháin',
    'Mac Sorrie': 'Mac Somhairle',
    'Mac Sorley': 'Mac Somhairle',
    'Sorrie': 'Mac Somhairle',
    'Sorley': 'Mac Somhairle',
    'Soughly': 'Ó Sochlaigh',
    'O Soulaghan': 'Ó Sochlacháin',
    'Soulaghan': 'Ó Sochlacháin',
    'Souter': 'Sútar',
    'Soutar': 'Sútar',
    'Mac Spadden': 'Mac Spadáin',
    'Mac Spaddin': 'Mac Spáidín',
    'Spaight': 'Spéit',
    'Spain': 'Spáinneach',
    'Spalane': 'Ó Spealáin Ó Smolláin',
    'Mac Sparran': 'Mac an Sparáin',
    'Spearing': 'Spéiring',
    'Spearin': 'Spéiring',
    'Speeding': 'Mac Spáidín',
    'Speedy': 'Ó Fuada',
    'Speed': 'Ó Fuada',
    'Speke': 'Mac Giolla Easpaig',
    'Spellane': 'Ó Spealáin',
    'Spellissy': 'Ó Spealasa',
    'Spellman': 'Ó Spealáin',
    'Spelman': 'Ó Spealáin',
    'Spencer': 'Mac Spealáin',
    'Spenser': 'Mac Spealáin',
    'Mac Sperrin': 'Mac an Sparáin',
    'O Spillane': 'Ó Spealáin',
    'Spillane': 'Ó Spealáin',
    'Mac Spollane': 'Mac Spealáin',
    'Mac Spollan': 'Mac Spealáin',
    'Spollane': 'Mac Spealáin',
    'Spollan': 'Mac Spealáin',
    'Sporran': 'Mac an Sparáin',
    'Spratt': 'Sprat',
    'Spruhan': 'Ó Srutháin',
    'Sreenan': 'Ó Srianáin',
    'Sruffaun': 'Ó Srutháin',
    'Stack': 'Stac',
    'Stackpoole': 'de Stacapúl',
    'Stafford': 'Stafort',
    'Staines': 'de Stáineas',
    'Stalker': 'Mac an Stocaire',
    'Stancard': 'Stancard',
    'Stanford': 'de Stanfort',
    'Stanley': 'de Stainléigh',
    'Stanton': 'Stondún',
    'Stapleton': 'Mac an Ghaill',
    'Starkey': 'Starcaidh',
    'Staunton': 'Mac an Mhíle',
    'Mac Stay': 'Ó Maoilsté',
    'Stay': 'Ó Maoilsté',
    'Steadman': 'Mac Eachaidh',
    'Stead': 'Mac Eachaidh',
    'Steed': 'Mac Eachaidh',
    'Steen': 'Ó Stíbhin',
    'Mac Steen': 'Mac Stín',
    'Steen': 'Mac Stín',
    'Stenson': 'Mac Stibhin',
    'Steinson': 'Mac Stibhin',
    'Stevens': 'Mac Stiofáin',
    'Steven': 'Mac Stiofáin',
    'Stephenson': 'Mac Stiofáin',
    'Steward': 'Stíobhard',
    'Stewart': 'Stíobhard',
    'Stuart': 'Stíobhard',
    'Stinson': 'Mac Stibhin',
    'Mac Stocker': 'Mac an Stocaire',
    'Stocker': 'Mac an Stocaire',
    'Stockman': 'Stocman',
    'Stokes': 'Stóc',
    'Stone': 'Ó Maolchluiche',
    'Storan': 'Ó Stóirín',
    'O Storeen': 'Ó Stoirín',
    'Storeen': 'Ó Stoirín',
    'O Storan': 'Ó Stoirín',
    'O Storeen': 'Ó Stoirín',
    'Storan': 'Ó Stoirín',
    'Storeen': 'Ó Stoirín',
    'O Strachan': 'Ó Sraitheáin',
    'O Strahan': 'Ó Sraitheáin',
    'Strachan': 'Ó Sraitheáin',
    'Strahan': 'Ó Sraitheáin',
    'Straghan': 'Ó Sraitheáin',
    'Strain': 'Ó Sraitheáin',
    'Strange': 'Stráinse',
    'Mac Stravick': 'Mac Srabhóg',
    'Stritch': 'Straoits',
    'Strong': 'Strong',
    'Stuart': 'Stíobhard',
    'Stubbins': 'Stóibín',
    'Stubbin': 'Stóibín',
    'Studdert': 'Studart',
    'Stundon': 'Stúndún',
    'Suche': 'Súiste',
    'Suckley': 'Ó Sochlaigh',
    'Sudway': 'Ó Deisil',
    'Suel': 'Ó Súiligh',
    'O Sugrew (Sugrue)': 'Ó Siochrú',
    'Sugrew (Sugrue)': 'Ó Siochrú',
    'O Sullahan': 'Ó Súileacháin',
    'Sullahan': 'Ó Súileacháin',
    'O Sullivan': 'Ó Súilleabháin',
    'Sullivan': 'Ó Súilleabháin',
    'O Summaghan': 'Ó Somacháin',
    'Summaghan': 'Ó Somacháin',
    'Sumahean': 'Ó Somacháin',
    'Summerly': 'Ó Somacháin',
    'Summers': 'Ó Somacháin',
    'Supple': 'Suipéil',
    'Mac Surley': 'Mac Somhairle',
    'Surtill': 'Soirtéil',
    'Sutter': 'Sútar',
    'Suter': 'Sútar',
    'Suttine': 'Sutún',
    'Swaine': 'Suan',
    'Mac Swan': 'Mac Suain',
    'Swan': 'Mac Suain',
    'Swanton': 'de Suantún',
    'Swayne': 'Suan',
    'Mac Sweeney': 'Mac Suibhne',
    'Sweeney': 'Mac Suibhne',
    'Sweetman': 'Suatman',
    'Swift': 'Ó Fuada',
    'Mac Swiggan': 'Mac Suigin',
    'Swiney': 'Mac Suibhne',
    'Swine': 'Mac Suibhne',
    'Switzer': 'Suitséir',
    'Swords': 'Ó Suaird',
    'Sword': 'Ó Suaird',
    'Sylver': 'Ó hAirgeadáin',
    'Symonds': 'Mac Síomóin',
    'Symons': 'Mac Síomóin',
    'Synon': 'Ó Sionáin',
    'Synan': 'Ó Sionáin',
    'Synge': 'Sing',
    'Synnott': 'Sionóid',
    'Syron': 'Ó Sírín'
}