module.exports = {
    'Taa': 'Táth',
    'Taff': 'Táth',
    'Taafe': 'Táth',
    'Tackney': 'Ó Seasnáin',
    'Mac Tadhg': 'Mac Taidhg',
    'Tadhg': 'Mac Taidhg',
    'Tagan': 'Ó Tadhgáin',
    'Mac Taggart': 'Mac an tSagairt',
    'Taggart': 'Mac an tSagairt',
    'Mac Taghlan': 'Mac Giolla tSeachlainn',
    'Mac Taghlin': 'Mac Giolla tSeachlainn',
    'Tagney': 'Ó Teangana',
    'Mac Tague': 'Mac Taidhg',
    'O Taheny': 'Ó Teitheacháin',
    'Taheny': 'Ó Teitheacháin',
    'Talbot': 'Talbóid',
    'Tallant': 'Talant',
    'Tallon': 'Talún',
    'Tally': 'Ó Taithligh',
    'Talty': 'Ó Tailtigh',
    'Mac Tamney': 'Mac an Tiompánaigh',
    'Tandy': 'Taindí',
    'O Tangney': 'Ó Teangana',
    'Tangney': 'Ó Teangana',
    'Tankard': 'Tancard',
    'Tannan': 'Ó Tanaidheáin',
    'Tanner': 'Tanúir',
    'Tanney': 'Ó Teathnaigh',
    'O Tannian': 'O Tanaidheáin',
    'Tannian': 'O Tanaidheáin',
    'Mac Tansey': 'Mac an Tánaiste',
    'Tansey': 'Mac an Tánaiste',
    'Tarmey': 'Ó Tormaigh',
    'Tarpey': 'Ó Tarpaigh',
    'Tarrant': 'Ó Toráin',
    'O Tarsnane': 'Ó Tarsnáin',
    'Tarsnane': 'Ó Tarsnáin',
    'Mac Tarsney': 'Mac an tSasanaigh',
    'Taugher': 'Ó Tuachair',
    'Taulty': 'Ó Tailtigh',
    'Tavey': 'Mac an tSámhaigh',
    'Mac Tavish': 'Mac Támhais',
    'Taylor': 'Táilliúir',
    'Mac Teague': 'Mac Taidhg',
    'Mac Tague': 'Mac Taidhg',
    'Teahan': 'Ó Téacháin',
    'Tee': 'Ó Taidhg',
    'Teegan': 'Ó Tadhgáin',
    'teeling': 'Taoiling',
    'Mac Tier': 'Mac an tSaoir',
    'Mac Teer': 'Mac an tSaoir',
    'O Teevan': 'Ó Téimheáin',
    'Teevan': 'Ó Téimheáin',
    'O Tegan': 'Ó Tadhgáin',
    'Tegan': 'Ó Tadhgáin',
    'Mac Teggarty': 'Mac an tSagairt',
    'Mac Teggart': 'Mac an tSagairt',
    'Teggarty': 'Mac an tSagairt',
    'Teggart': 'Mac an tSagairt',
    'Tehane': 'Ó Téacháin',
    'Tehan': 'Ó Téacháin',
    'O Teheny': 'Ó Teitheacháin',
    'Teheny': 'Ó Teitheacháin',
    'Mac Teigue': 'Mac Taidhg',
    'Mac Teige': 'Mac Taidhg',
    'Teigue': 'Mac Taidhg',
    'Teige': 'Mac Taidhg',
    'Tempany': 'Mac an Tiompánaigh',
    'Tenpeny': 'Mac an Tiompánaigh',
    'Tempest': 'Mac Anfaidh',
    'Temple': 'Tiompail',
    'Tempeny': 'Mac an Tiompánaigh',
    'Tenpenny': 'Mac an Tiompánaigh',
    'Terence': 'Mac Toirealaigh',
    'Mac Ternan': 'Mac Tiarnáin',
    'Ternan': 'Mac Tiarnáin',
    'O Terney': 'Ó Tiarnaigh',
    'Terney': 'Ó Tiarnaigh',
    'Terry': 'Mac Toirealaigh',
    'Tesky': 'Teisce ',
    'O Tevlin': 'Ó Teibhlin',
    'Tevlin': 'Ó Teibhlin',
    'Tevnane': 'Ó Teimhneáin',
    'Tevnan': 'Ó Teimhneáin',
    'Tew': 'Tiú',
    'Thirkell': 'Mac Torcaill',
    'Thom': 'Tóm',
    'Thomas': 'Mac Tomáis',
    'Thompson': 'Mac Tomáis',
    'Thomson': 'Mac Tomáis',
    'Thoms': 'Mac Thómais',
    'Thoran': 'Ó Toráin',
    'Thorn': 'Ó Toráin',
    'Thornhill': 'Tornail',
    'Thornton': 'Ó Draighneáin',
    'Thulis': 'Ó Tuathaláin',
    'Toolis': 'Ó Tuathaláin',
    'Thunder': 'Tundar',
    'Thurkell': 'Mac Torcaill',
    'Thurkle': 'Mac Torcaill',
    'Thynne': 'Ó Teimhin',
    'Tidins': 'Ó Tuairisc',
    'Mac Tiernan': 'Mac Tiarnáin',
    'Tiernan': 'Mac Tiarnáin',
    'Mac Tierney': 'Mac Tarnaigh',
    'O Tierney': 'Ó Tiarnaigh',
    'Tierney': 'Ó Tiarnaigh',
    'Mac Tige': 'Mac Taidhg',
    'Tiger': 'Mac an tSagairt',
    'Mac Tigue': 'Mac Taidhg',
    'Mac Tighe': 'Mac Taidhg',
    'Tigue': 'Mac Taidhg',
    'Tighe': 'Mac Taidhg',
    'O Tigue': 'Ó Taidhg',
    'Tigue': 'Ó Taidhg',
    'Tilly': 'Ó Taithligh',
    'Mac Timblin': 'Mac Toimilín',
    'Mac Timlin': 'Mac Toimilín',
    'Timblin': 'Mac Toimilín',
    'Timlin': 'Mac Toimilín',
    'Timmons': 'Mac Toimín',
    'Timmons': 'Ó Tiomáin',
    'Timmon': 'Ó Tiomáin',
    'Mac Timney': 'Mac an Tiompánaigh',
    'O Timony': 'O Tiománaí',
    'Timony': 'O Tiománaí',
    'Timothy': 'Mac Tomaltaigh',
    'Mac Timpany': 'Mac an Tiompánaigh',
    'Timpany': 'Mac an Tiompánaigh',
    'Tinan': 'O Teimhneáin',
    'Tincler': 'Tincléir',
    'Tinin': 'Ó Teimhnín',
    'Tinney': 'Mac an tSionnaigh',
    'Tiney': 'Mac an tSionnaigh',
    'Tinsley': 'Ó Cinsealaigh',
    'Tirry': 'Tuiridh',
    'Tivane': 'Ó Téimheáin',
    'O Tivnan': 'Ó Teimhneáin',
    'Tivnan': 'Ó Teimhneáin',
    'Toale': 'Ó Tuathail',
    'Toal': 'Ó Tuathail',
    'Tobin': 'Tóibín',
    'Togher': 'Ó Tuachair',
    'Toher': 'Ó Tuachair',
    'O Toghill': 'Ó Tuathail',
    'O Tohill': 'Ó Tuathail',
    'Toghill': 'Ó Tuathail',
    'Tohill': 'Ó Tuathail',
    'Toke': 'Tóc',
    'Toland': 'Ó Tuathaláin',
    'Tolan': 'Ó Tuathaláin',
    'Tole': 'Ó Tuathail',
    'Toler': 'Ó Talchair',
    'Tolin': 'Ó Tuathaláin',
    'O Tolleran': 'Ó Talcharáin',
    'Tolleran': 'Ó Talcharáin',
    'O Toman': 'Ó Tuamáin',
    'Toman': 'Ó Tuamáin',
    'Tomblinson': 'Mac Toimilín',
    'Tomblin': 'Mac Toimilín',
    'Mac Tomilty': 'Mac Tomaltaigh',
    'Tomilty': 'Mac Tomaltaigh',
    'Tomkins': 'Tóimicín',
    'Tomkin': 'Tóimicín',
    'Tomlinson': 'Mac Toimilín',
    'Tomlins': 'Mac Toimilín',
    'Mac Tomulty': 'Mac Tomaltaigh',
    'Tomulty': 'Mac Tomaltaigh',
    'Tone': 'Tón',
    'O Tonry': 'Ó Tomhnair',
    'O Toner': 'Ó Tomhnair',
    'Tonry': 'Ó Tomhnair',
    'Toner': 'Ó Tomhnair',
    'Tooey': 'Ó Tuathaigh',
    'Tooher': 'Ó Tuachair',
    'O Toohig': 'Ó Tuathaigh',
    'Toohig': 'Ó Tuathaigh',
    'O Toohill': 'Ó Tuathail',
    'Toohill': 'Ó Tuathail',
    'Toohy': 'Ó Tuathaigh',
    'Tooke': 'Tóc',
    'Took': 'Tóc',
    'Tooker': 'Ó Tuachair',
    'O Toolan': 'Ó Tuathaláin',
    'Toolan': 'Ó Tuathaláin',
    'Mac Toole': 'Mac Tuathail',
    'O Toole': 'Ó Tuathail',
    'Toole': 'Ó Tuathail',
    'Tooley': 'Ó Tuathaile',
    'Toolis': 'Ó Tuathaláin',
    'Tooman': 'Ó Tuamáin',
    'O Toomey': 'Ó Tuama',
    'Toomey': 'Ó Tuama',
    'Toopane': 'Ó Tuamáin',
    'O Toorish': 'Ó Tuairisc',
    'Toorish': 'Ó Tuairisc',
    'Toran': 'Ó Toráin',
    'Torley': 'Mac Toirealaigh',
    'O Tormey': 'Ó Tormaigh',
    'Tormey': 'Ó Tormaigh',
    'Torney': 'Ó Torna',
    'O Torpey': 'Ó Tórpa',
    'Torpey': 'Ó Tórpa',
    'Torran': 'Ó Toráin',
    'Torrance': 'Ó Toráin',
    'Torrens': 'Ó Toráin',
    'Mac Torry': 'Mac Toirealaigh',
    'Torry': 'Mac Toirealaigh',
    'O Torry': 'Ó Toirealaigh',
    'Torry': 'Ó Toirealaigh',
    'Mac Torsney': 'Mac an tSasanaigh',
    'Torsney': 'Mac an tSasanaigh',
    'tothill': 'Ó Tuatail',
    'Tosh': 'Mac an Taoisigh',
    'Toughall': 'Ó Tuathail',
    'O Tooher': 'Ó Tuachair',
    'O Tougher': 'Ó Tuachair',
    'Tooher': 'Ó Tuachair',
    'Tougher': 'Ó Tuachair',
    'O Touhy': 'Ó Tuathaigh',
    'Touhy': 'Ó Tuathaigh',
    'O Toulhan': 'Ó Tuathaláin',
    'Toulhan': 'Ó Tuathaláin',
    'O Tourisk': 'Ó Tuairisc',
    'Tourisk': 'Ó Tuairisc',
    'O Towell': 'Ó Tuathail',
    'Towell': 'Ó Tuathail',
    'O Towey': 'Ó Toghdha',
    'Towey': 'Ó Toghdha',
    'O Towey': 'Ó Tuathaigh',
    'Towey': 'Ó Tuathaigh',
    'O Towmey': 'Ó Tuama',
    'Towmey': 'Ó Tuama',
    'Townley': 'de Túinléigh',
    'Toye': 'Ó Tuathaigh',
    'Toy': 'Ó Tuathaigh',
    'Trahey': 'Ó Troithigh',
    'Mac Trainor': 'Mac Thréinir',
    'Trainor': 'Mac Thréinir',
    'Trant': 'Treant',
    'Trassy': 'Ó Treasaigh',
    'Tarvers': 'Ó Treabhair',
    'Mac Traynor': 'Mac Thréinir',
    'Traynor': 'Mac Thréinir',
    'O Treacy': 'Ó Treasaigh',
    'Treacy': 'Ó Treasaigh',
    'Treacy': 'Ó Treasaigh',
    'Trehy': 'Ó Troithigh',
    'Trench': 'Trinse',
    'Trevors': 'Ó Treabhair',
    'Trevor': 'Ó Treabhair',
    'Trew': 'Triú',
    'Trihy': 'Ó Troithigh',
    'O Trihy': 'Ó Troithigh',
    'Trim': 'de Troim',
    'Trim-Lavery': 'Ó Labhraí Tréan',
    'Tristan': 'Trostan',
    'Tristam': 'Trostan',
    'Trodden': 'Ó Treodáin',
    'Trodden': 'Ó Treodáin',
    'Trudden': 'Ó Treodáin',
    'O Troy': 'Ó Troithigh',
    'O Trohy': 'Ó Troithigh',
    'Troy': 'Ó Troithigh',
    'Trohy': 'Ó Troithigh',
    'O Trower': 'Ó Treabhair',
    'Trower': 'Ó Treabhair',
    'Trueman': 'Triúman',
    'Tryn-Lavery': 'Ó Labhraí Tréan',
    'O Tubrit': 'Ó Tiobraide',
    'O Tubridy': 'Ó Tiobraide',
    'Tubrit': 'Ó Tiobraide',
    'Tubridy': 'Ó Tiobraide',
    'Mac Tucker': 'Mac Tuachair',
    'O Tucker': 'Ó Tuachair',
    'Tucker': 'Ó Tuachair',
    'O Tuffy': 'Ó Tofa',
    'Tuffy': 'Ó Tofa',
    'Tuite': 'Tiúit',
    'Tuke': 'Tóc',
    'Mac Tully': 'Mac an Tuile',
    'Tully': 'Mac an Tuile',
    'Mac Tumelty': 'Mac Tomaltaigh',
    'Tumelty': 'Mac Tomaltaigh',
    'Tumman': 'Ó Tuamáin',
    'Tumpane': 'Mac an Tiompánaigh',
    'Tunney': 'Ó Tonnaigh',
    'O Tunry': 'Ó Tomhrair',
    'Tunry': 'Ó Tomhrair',
    'O Tuohy': 'Ó Tuathaigh',
    'Tuohy': 'Ó Tuathaigh',
    'Turbett': 'Torbóid',
    'Turbit': 'Torbóid',
    'Turish': 'Ó Tuairisc',
    'Mac Turk': 'Mac Toirc',
    'Turk': 'Mac Toirc',
    'Turkington': 'Mac Toirc',
    'Mac Turley': 'Mac Toirealaigh',
    'Turley': 'Mac Toirealaigh',
    'Turner': 'Tornóir',
    'Turney': 'Ó Torna',
    'Tuthill': 'Ó Tuatail',
    'Tuttle': 'Ó Tuatail',
    'Tutty': 'Ó Tuataigh',
    'Twigg': 'Ó Cuaig',
    'Twigley': 'Ó Coigligh',
    'O Twohig': 'Ó Tuathaigh',
    'Twohig': 'Ó Tuathaigh',
    'O Twohill': 'Ó Tuathail',
    'Twohill': 'Ó Tuathail',
    'O Twomey': 'Ó Tuama',
    'Twomey': 'Ó Tuama',
    'Tydings': 'Ó Tuairisc',
    'Tye': 'Mac Ceanglaigh',
    'Tighe': 'Mac Ceanglaigh',
    'Tyghe': 'Ó Taidhg',
    'Tympany': 'Mac an Tiompánaigh',
    'O Tynan': 'Ó Teimhneáin',
    'Tynan': 'Ó Teimhneáin',
    'Tyne': 'Ó Teimhin',
    'Tyney': 'Mac an tSionnaigh',
    'Tyrrell': 'Tirial',
    'Tyre': 'Mac an tSaoir',
    'Tyrie': 'Mac an tSaoir',
}