module.exports = {
    'Mac Vaddock': 'Mac Mhadóc',
    'Vaddock': 'Mac Mhadóc',
    'Vadin': 'Mac Pháidín',
    'Mac Vady': 'Mac an Mhadaidh',
    'Vahey': 'Ó Fathaigh',
    'de Valera': 'de Valera',
    'Mac Vail': 'Mac Phóil',
    'Valentine': 'Vailintín',
    'de Valle': 'de Bhal',
    'Mac Vallelly': 'Mac Giolla Bhearshúiligh',
    'Vallelly': 'Mac Giolla Bhearshúiligh',
    'Vally': 'Mac an Bhallaigh',
    'Mac Vanamy': 'Mac Mheanma',
    'Vanamy': 'Mac Mheanma',
    'Mac Vann': 'Mac Bheathan',
    'Mac Vany': 'Mac an Mhanaigh',
    'Varden': 'de Bheardún',
    'Vargis': 'Ó Fearghais',
    'Vargus': 'Ó Fearghais',
    'Varian': 'Ó Bhioráin',
    'Varilly': 'Mac Giolla Bhearshúiligh',
    'Mac Varry': 'Mac Fearaigh',
    'Vaugh': 'Mac an Bheatha',
    'Vaughan': 'Uachan',
    'Vaughan': 'Ó Macháin',
    'Mac Vay': 'Mac an Bheatha',
    'Mac Veigh': 'Mac an Bheatha',
    'Mac Vey': 'Mac an Bheatha',
    'Mac Veagh': 'Mac an Bheatha',
    'Vey': 'Mac an Bheatha',
    'Veagh': 'Mac an Bheatha',
    'Veale': 'de Bhial',
    'Mac Vean': 'Mac Bheathan',
    'Veasy': 'Mac an Bheatha',
    'Mac Veety': 'Mac an Bhiataigh',
    'de Veigh': 'Mac an Bheatha',
    'de Veldon': 'Béalatún',
    'de Verdon': 'de Bheardún',
    'de Vere': 'de Bhéir',
    'de Verling': 'Feoirling',
    'de Verlin': 'Feoirling',
    'Mac Verran': 'Mac Mhearáin',
    'Mac Verry': 'Mac Fearaigh',
    'Vesey': 'Mac an Bheatha',
    'Mac Vickars': 'Mac an Bhiocáire',
    'Mac Vickar': 'Mac an Bhiocáire',
    'Vickars': 'Mac an Bhiocáire',
    'Vickar': 'Mac an Bhiocáire',
    'Mac Vicker': 'Mac an Bhiocáire',
    'Victory': 'Mac Anabaí',
    'Vincent': 'Uinseann',
    'Vincent': 'Mac Dhuibhinse',
    'Vingin': 'Ó Fiacha',
    'Mac Vitty': 'Mac an Bhiataigh',
    'Vogan': 'Ugán',
    'Mac Voy': 'Mac Fhíobhuí',
}
