module.exports = {
    'Wadden': 'Uaidín',
    'Wadding': 'Uaidín',
    'Waddock': 'Mac Mhadóc',
    'Waddick': 'Mac Mhadóc',
    'Mac Wade': 'Mac Uaid',
    'Wade': 'Mac Uaid',
    'Waldron': 'de Bhaldraithe',
    'Mac Bhaildrín': 'de Bhaldraithe',
    'Walker': 'Mac Siúlaí',
    'Wall': 'de Bhál',
    'Wallace': 'Bhailis',
    'Wallis': 'Bhailis',
    'Walrick': 'Mag Ualraig',
    'Walsee': 'Breatnach',
    'Walse': 'Breatnach',
    'Mac Walters': 'Ualtair',
    'Mac Walter': 'Ualtair',
    'Walters': 'Ualtair',
    'Walter': 'Ualtair',
    'Walton': 'de Bháltún',
    'Mac Ward': 'Mac an Bhaird',
    'Ward': 'Mac an Bhaird',
    'Mac Warnock': 'Mac Giolla Mhearnóg',
    'Warnock': 'Mac Giolla Mhearnóg',
    'Warrin': 'Ó Murnáin',
    'Warren': 'Ó Murnáin',
    'Waters': 'Ó hUisce',
    'Watterson': 'Mac Uaitéir',
    'Waterson': 'Mac Uaitéir',
    'Watson': 'Mac Uait',
    'Mac Watters': 'Mac Uaitéir',
    'Watts': 'Mac Uait',
    'Wayland': 'Ó Faoláin',
    'Weadock': 'Mac Mhadóc',
    'Weddick': 'Mac Mhadóc',
    'Weaver': 'Mac an Fhíodair',
    'Mac Weeney': 'Mac Mhaonaigh',
    'Mac Wear': 'Mac an Mhaoir',
    'Mac Weir': 'Mac an Mhaoir',
    'Weir': 'Mac an Mhaoir',
    'Wear': 'Mac an Mhaoir',
    'Welch': 'Breatnach',
    'Weldon': 'Béalatún',
    'Weldon': 'Ó Mhaoldúin (Fear Manach)',
    'Wellesley': 'Mac Bhalronta',
    'Welsh': 'Breatnach',
    'Wesley': 'Mac Bhalronta',
    'Wesley': 'Mac Bhalronta',
    'Weston': 'Uastún',
    'Whalon': 'Ó Faoláin',
    'Whealon': 'Ó Faoláin',
    'Whan': 'Mac Mhíolchon',
    'Mac Whannell': 'Mac Dhónaill',
    'Whannell': 'Mac Dhónaill',
    'Mac Whannon': 'Ó Buacháin',
    'Wharton': 'Ó hArrachtáin',
    'Whearty': 'Ó Faghartaigh',
    'Whelan': 'Ó Faoláin',
    'Whelan': 'Ó Fialáin (Fear Manach)',
    'O Whelehan': 'Ó Faoileacháin',
    'Whelehan': 'Ó Faoileacháin',
    'Whelton': 'Ó hUallacháin',
    'Mac Wherter': 'Mac Artair',
    'Whin': 'Mac Shuibhne',
    'Mac Whinney': 'Mac Shuibhne',
    'Mac Whirter': 'Mac Artair',
    'Mac Whiston': 'Mac Úistín',
    'Whitaker': 'Mac Uitheachair',
    'Whitcomb': 'Mac Thiarnáin',
    'White': 'de Faoite',
    'Mac White': 'Mac Faoitigh',
    'White': 'Ó Banáin ',
    'Whitelock': 'Ó Ceannuáin',
    'Whitehead': 'Ó Ceannuáin',
    'Whitlock': 'Ó Ceannuáin',
    'Whitesteed': 'Ó hEachuáin',
    'Whitley': 'de Fuitléigh',
    'Whitney': 'de Fuitnigh',
    'Whitty': 'de Fuite',
    'Whitty': 'Mac Faoitigh',
    'Wholey': 'Ó hUallaigh',
    'Whoolehan': 'Ó hUallacháin',
    'Whoriskey': 'Ó Fuaruisce',
    'Mac Whorter': 'Mac Artair',
    'Whyte': 'Ó Banáin',
    'Wier': 'Mac an Mhaoir',
    'Weir': 'Mac an Mhaoir',
    'Mac Wigin': 'Mag Uiginn',
    'Wigin': 'Mag Uiginn',
    'Wigmore': 'de Uigeamór',
    'Wilhair': 'Mac Giolla Chathair',
    'Mac Wilkin': 'Mac Uilcín',
    'Wilkinson': 'Mac Uilcín',
    'Wilkin': 'Mac Uilcín',
    'Mac Williams': 'Mac Uilliam',
    'Mac William': 'Mac Uilliam',
    'Williamson': 'Mac Uilliam',
    'Williams': 'Mac Uilliam',
    'Mac Willie': 'Mac Uilí',
    'Willis': 'Uilis',
    'Wills': 'Uilis',
    'Wilmott': 'Uilmit',
    'Wilmit': 'Uilmit',
    'Willmore': 'Mac Liammóir',
    'Wilson': 'Mac Liam',
    'Windham': 'Ó Gaoithín',
    'Windle': 'Uingil',
    'Wingfield': 'Uingséil',
    'Winkle': 'Uingil',
    'Wingle': 'Uingil',
    'Winn': 'Ó Gaoithín',
    'Wrynn': 'Mag Bhroin',
    'Winters': 'an Gheimhridh',
    'Wire': 'Mac an Mhaoir',
    'Wisdom': 'Ó Céile',
    'Wise': 'Uidheas',
    'Wixted': 'Uicstéid',
    'Wogan': 'Ugán',
    'Wofe': 'Ó Mactíre',
    'Wolfe': 'Ó Mactíre',
    'Wolley': 'de Bhulbh',
    'Woodlock': 'Uadlóg',
    'Woods': 'Mac Conchoille',
    'Woolahan': 'O hUallacháin',
    'Wooley': 'de Bhulbh',
    'Wordie': 'Mac Mhuireartaigh',
    'Woulfe': 'de Bhulbh',
    'Wrafter': 'Ó Reachtair',
    'Mac Wray': 'Mac Raith',
    'Wray': 'Ó Riabhaigh',
    'Wrenn': 'Mac Bhrain',
    'Wren': 'Mac Bhrain',
    'Wright': 'Mac an tSaoir',
    'Wrynn': 'Mac Bhrain',
    'Wyer': 'Mac an Mhaoir',
    'Wyndham': 'Ó Maolghaoithe',
    'Wynn': 'Ó Gaoithín',
    'Wyse': 'Uidheas',
}